### ISSUE TITLE
請益文件處理方法

### ISSUE THREAD

**Issue by XiuChen-Liu** [babysor/MockingBird#113]
想請問除了手動外，如何用程式把以下各個分開個文件
![000](https://user-images.githubusercontent.com/55180847/135702733-dba52370-350d-4ba6-843a-bdee10ab11f9.PNG)

彙整成全部一個檔案，並且在每行內容前面加上音頻檔名?
![1111](https://user-images.githubusercontent.com/55180847/135702752-8656e9ec-ddbb-4ffa-bfbc-cf8dd109913c.PNG)

我對於資料處理這塊是一個新手，想請教有沒有什麼方法，然後自己嘗試看看

**Comment by babysor** [comment]
参考 `synthesizer\preprocess.py`，把所有的txt文件拿到，组成map

**Comment by XiuChen-Liu** [comment]
好的！謝謝
