### ISSUE TITLE
切换模型之后会出现ui向右延申的问题

### ISSUE THREAD

**Issue by 2651084156** [babysor/MockingBird#115]
![图片](https://user-images.githubusercontent.com/69307837/135850408-ed00bb4a-b684-4116-ad59-b2906be1e2c0.png)
切换绿色圈处的模型会出现如图效果
![图片](https://user-images.githubusercontent.com/69307837/135850597-fda3a14d-9a5d-4552-91bd-77e827910034.png)
正常应如下图
![图片](https://user-images.githubusercontent.com/69307837/135850884-9b4934a5-b8df-44e4-8f3a-86dd9b4154f2.png)
![图片](https://user-images.githubusercontent.com/69307837/135850995-f362ab30-e97b-4742-bb10-5791b01efeb5.png)

**Comment by 2651084156** [comment]
![图片](https://user-images.githubusercontent.com/69307837/135851212-361b429e-86b4-4b8b-a312-073f16d558ed.png)
有时候还会这样

**Comment by 2651084156** [comment]
貌似句子太长没有符号分隔的话ai生成的语音会及其的奇怪

**Comment by babysor** [comment]
你不能把model放到encoder下面，而是synthesizer下

**Comment by 2651084156** [comment]
> 
> 
> 你不能把model放到encoder下面，而是synthesizer下

![图片](https://user-images.githubusercontent.com/69307837/135873020-bcb3494c-0739-4c38-8645-a9a0c50a9934.png)
他会报错，使用我两个都放了

**Comment by babysor** [comment]
报错的时候ui会被挤压，非常小的issue，看起来问题已经得到解决，如果有相关改进建议或仍存在问题可以重新打开 
It seems this issue had been handled well, please be free to reopen if got any suggestion or new problems.
