### ISSUE TITLE
Exception: No synthesizer models found in synthesizer\saved_models

### ISSUE THREAD

**Issue by Jason-hu-jav** [babysor/MockingBird#116]
Arguments:
    datasets_root:    E:\Download\aidatatang_200zh
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Traceback (most recent call last):
  File "E:\Download\MockingBird-main\MockingBird-main\demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "E:\Download\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 74, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir, seed)
  File "E:\Download\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 142, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "E:\Download\MockingBird-main\MockingBird-main\toolbox\ui.py", line 339, in populate_models
    raise Exception("No synthesizer models found in %s" % synthesizer_models_dir)
Exception: No synthesizer models found in synthesizer\saved_models
请问各位，这个可能是哪里的问题

**Comment by Jason-hu-jav** [comment]
我没学过Python，对其中的报错也不是很理解

**Comment by babysor** [comment]
没有下载或训练好的模型放在 synthesizer\saved_models 路径中

**Comment by babysor** [comment]
看起来问题已经得到解决，如果有相关改进建议或仍存在问题可以重新打开 
It seems this issue had been handled well, please be free to reopen if got any suggestion or new problems.

**Comment by Jason-hu-jav** [comment]
> 没有下载或训练好的模型放在 synthesizer\saved_models 路径中

非常感谢

**Comment by HaSaKiYasuooo** [comment]
模型自动保存，你要看back_save的值，这个值很大，可能要等很久才能看到保存的模型
