### ISSUE TITLE
请问社区预先训练好的合成器如何用？

### ISSUE THREAD

**Issue by anonymousbone** [babysor/MockingBird#118]
看教程part2.2中提供了社区预先训练好的合成器，请问是否用了这个就无需再自行训练ai？
点击了第一个网盘链接里面的文件叫「train3_200k.pt」，请问这个文件下载下来后放在哪个文件夹内？需要修改文件名称吗？
是直接放在/synthesizer/saved_models/mandarin/ 下就可以吗？我这个位置下有个叫「mandarin.pt」的文件，下载下来的直接替换mandarin.pt这个文件对吗？
如是，那替换以后直接运行工具就可以使用了对吗？
问题比较小白，望各位别介意，感谢。

**Comment by babysor** [comment]
不需要改名字 在toolbox里面下拉选择即可

**Comment by anonymousbone** [comment]
好的，感谢告知

**Comment by babysor** [comment]
看起来问题已经得到解决，如果有相关改进建议或仍存在问题可以重新打开 
It seems this issue had been handled well, please be free to reopen if got any suggestion or new problems.
