### ISSUE TITLE
训练出来的音频带电音正常吗

### ISSUE THREAD

**Issue by twilightsg** [babysor/MockingBird#119]
我训练了大约1500步出来的比51凡的电音还要电音请问这正常吗
是我参数写的不对吗
[step-1500-wave-from-mel_sample_1.zip](https://github.com/babysor/MockingBird/files/7298488/step-1500-wave-from-mel_sample_1.zip)

**Comment by babysor** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
