### ISSUE TITLE
请问训练模型的时候如何保存.....

### ISSUE THREAD

**Issue by ANINwindows** [babysor/MockingBird#120]
我知道这个问题比较傻，但是我现在不知道怎么保存，每次训练都是从头开始，求大佬指点

**Comment by ANINwindows** [comment]
> 会隔1000步自动保存，用同一个id就可以继续

您好，我程序里面使用了显卡，但是速率还是只有0.13steps/s ,Using device: cuda，我调整了Batch Size到36显存占用率已经有80%了，但是显卡使用率只有12%左右，我还需要调整什么参数呢？

**Comment by ANINwindows** [comment]
> > 主要是消耗显着存gpu占有率不高。你这有点问题什么显卡？
> 
> GTX1080ti，已经安装了CUDA和CUDNN

**Comment by ANINwindows** [comment]
我看到有篇文章遇到的问题和我差不多，都是显卡使用率忽高忽低，大约保持在10%左右

>后来我偶然为了减小最后的tensorboard log文件，我把一些用不到的tensorboard的写入比如直方图给删掉了，发现速度瞬间提上来了，然后再减小训练时的输出间隔，速度也有提升。立刻明白了，是因为训练的主要时间都花在了写日志上，文件IO耗时特别多，尤其是我设置的写入间隔还很小，所以GPU计算一瞬间，然后写很久的记录，计算一瞬间，再写很久的记录，最终导致速度特别慢。这也正是为了速度和我笔记本的GTX1050一样，因为大家比的都是写文件的速度。

![捕获](https://user-images.githubusercontent.com/44198387/136331525-2fedbb70-b699-4755-8788-b5e3f45beb38.PNG)

**Comment by babysor** [comment]
感谢 你reopen一下 我晚点加个开关把写log关掉

**Comment by ANINwindows** [comment]
好的

**Comment by babysor** [comment]
训练时输入 `-l 0`
