### ISSUE TITLE
训练到485K loss压不下去了，徘徊在0.4，如何更换模型？

### ISSUE THREAD

**Issue by LxKxC** [babysor/MockingBird#123]
如题，我已经使用 aidatatang_200zh 训练了485K step 了，不知道这个训练量是否足够，但是loss下不去了，现在想在当前训练基础上，将数据集更换成aishell3和magicdata，请问我应该如何操作？

‘ Epoch: 3/15 (1078/12249) | Loss: 0.4008 | 1.0 steps/s | Step: 485k | }’

**Comment by LxKxC** [comment]
> 预处理使用-s 输出到同一路径

谢谢作者回复，但是抱歉我还是有点不懂，您是说我预处理aishell3时，加一个-s 指定到跟aidatatang相同的路径吗？但是这个路径是指<datasets_root>？还是说<datasets_root>\aidatatang_200zh\ 之类的呢？能否给我个命令行样例，或者详细说明一下呢？

**Comment by babysor** [comment]
将 两个数据集都放在一个 <datasets_root> 下，并且在预处理的时候加入 -s 或者 skip_existing参数
... --skip_existing
这样结束后应该可以在 <datasets_root>/SV2TTS/ 文件夹中看到多个数据的处理结果

**Comment by luobingit** [comment]
@LxKxC 大佬  请教一下  在win系统上  如何手动结束训练  我按ctrl+c总是会损坏模型文件

**Comment by LxKxC** [comment]
> @LxKxC 大佬 请教一下 在win系统上 如何手动结束训练 我按ctrl+c总是会损坏模型文件

从没遇到过您这种情况，我建议训练命令增加 -b 1000 -s 1000  ，这样每1000步就自动保存和备份一次，当再次遇到模型损坏时，将最新的备份模型改名替换掉主模型即可继续训练。但是由于频繁的备份，您的硬盘可能很快就会爆满

**Comment by babysor** [comment]
> @LxKxC 大佬 请教一下 在win系统上 如何手动结束训练 我按ctrl+c总是会损坏模型文件

不科学呀，这个没发生过

**Comment by MarkIzhao** [comment]
> 



> > @LxKxC 大佬 请教一下 在win系统上 如何手动结束训练 我按ctrl+c总是会损坏模型文件
> 
> 不科学呀，这个没发生过

我也是一样  win11系统  CPU是AMD的

**Comment by MarkIzhao** [comment]
> @LxKxC 大佬 请教一下 在win系统上 如何手动结束训练 我按ctrl+c总是会损坏模型文件

请问你解决了吗？

**Comment by MarkIzhao** [comment]
> > @LxKxC 大佬 请教一下 在win系统上 如何手动结束训练 我按ctrl+c总是会损坏模型文件
> 
> 请问你解决了吗？

已解决 验证后发现是pytorch版本问题
