### ISSUE TITLE
报错：Model files not found. 

### ISSUE THREAD

**Issue by changfeng-sp** [babysor/MockingBird#133]
电脑为M1

在运行时出现以下提示：

(MockingBird) zsh@zshMacBook-Pro ~ % python /Users/zsh/Desktop/MockingBird-main/demo_toolbox.py -d /Users/zsh/Desktop
Arguments:
    datasets_root:    /Users/zsh/Desktop
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

********************************************************************************
Error: Model files not found. Follow these instructions to get and install the models:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
********************************************************************************

请问该如何解决呀？

**Comment by babysor** [comment]
是不是没有下载预先训练好的模型放在： synthesizer/saved_models 下呀

**Comment by changfeng-sp** [comment]
> 是不是没有下载预先训练好的模型放在： synthesizer/saved_models 下呀

已经放在了models文件夹下面~
![image](https://user-images.githubusercontent.com/24569163/136697706-f7997327-7646-413c-bb97-640d656592c0.png)

**Comment by babysor** [comment]
saved_models  而不是 models

**Comment by babysor** [comment]
https://github.com/babysor/MockingBird/issues/65
看起来路径格式M1可能也有问题

**Comment by changfeng-sp** [comment]
> #65 看起来路径格式M1可能也有问题

麻烦大佬帮忙解决一下，手上真的只有这台电脑了😭

**Comment by babysor** [comment]
参考一下上面这个 #65 链接
