### ISSUE TITLE
关于中英混杂。

### ISSUE THREAD

**Issue by mudong0419** [babysor/MockingBird#142]
谢谢您的分享，我想做能支持中英混杂的语音克隆。现在中文除了你提到的语料，英文还有libritts, vctk等，另外我们自己有少量的中英混杂语音。如果想做中英混杂的语音克隆，请问您有什么建议吗？多谢！

**Comment by mudong0419** [comment]
不好意思，另外想再问下，是否可以考虑使用VITS的模型结构，这样不用单独训练声学模型和vocoder,直接端到端训练模型。然后将语音克隆的相关的模块迁移到VITS模型上，训练效率应该能好一些，合成速度也更快。

**Comment by babysor** [comment]
https://github.com/babysor/MockingBird/issues/440
