### ISSUE TITLE
docker 镜像

### ISSUE THREAD

**Issue by lawler61** [babysor/MockingBird#149]
你好，可以提供个 docker 镜像吗，安装依赖、启动项目 可能对其他开发有一定成本

**Comment by lyqscmy** [comment]
https://github.com/babysor/MockingBird/issues/122#issuecomment-962391780

**Comment by luobingit** [comment]
@lyqscmy 大佬  能不能出个把此项目打包成docker镜像的教程  运维不太熟  尴尬

**Comment by wangz1yu** [comment]
docker需要https访问，求问怎么操作

**Comment by wangz1yu** [comment]
> [第122章（评论）](https://github.com/babysor/MockingBird/issues/122#issuecomment-962391780)

docker需要https访问，求问怎么操作
