### ISSUE TITLE
synthesizer训练时-b参数设置不当导致训练模型被覆盖

### ISSUE THREAD

**Issue by LxKxC** [babysor/MockingBird#152]
命令样例 
```python synthesizer_train.py -s 500 -b 500 whitecat C:\Users\z\Documents\MockingBird\data\SV2TTS\synthesizer```

训练synthesizer时，如果-b小于1000(不是1000的倍数)比如比如-b 500 （每500次备份一次模型)，由于模型名称的保存规则：

name_1k.pt
name_2k.pt
name_3k.pt
name_4k.pt

这就导致了，，，，备份的模型被覆盖掉！！！
500步的备份模型被1000步的备份模型覆盖了！！！

修正方法：

1. -b 参数值只能是1000的倍数，这样才不会覆盖
2. 或者修改py文件里面的命名规则

**Comment by babysor** [comment]
Fixed
