### ISSUE TITLE
按照#37的修改，还是一直出现杂音

### ISSUE THREAD

**Issue by alenstudent** [babysor/MockingBird#168]
按步骤准备好环境启动工具箱后，一切默认，上传目录下的temp.wav。点击 Sythesize and vcode后，第一次报跟 #37 一样的错，直接忽略，再次点击 Sythesize and vcode后，又没报错了，这时生成的是杂音。已经按照 #37 的改法修改了`synthesizer/utils/symbols.py`这个文件，要怎么修复？

**Comment by lhzwb2008** [comment]
使用v0.0.1版本，并按照#37修改，使用my_run8_25k模型，还是一堆杂音，还是有size mismatch报错，要哭了。。。。

**Comment by Kristen-PRC** [comment]
> 你可能是更新到10/23之后的版本了.建议退回去试试. @klaylizhe

您好，方便详细说一下如何回退requirement的版本吗，本人刚刚接触，不是太明白，望详细说明，谢谢
