### ISSUE TITLE
訓練hifigan聲碼器報錯

### ISSUE THREAD

**Issue by XiuChen-Liu** [babysor/MockingBird#169]
問題如標題，以下是執行後的畫面:

1
![擷取](https://user-images.githubusercontent.com/55180847/138585002-f1c394d7-be1e-45cc-807a-a5666e341cd1.PNG)

2
![111](https://user-images.githubusercontent.com/55180847/138585006-99e2e811-d4c0-4e24-af62-b7e61c2e9f9f.PNG)

3
![222](https://user-images.githubusercontent.com/55180847/138585012-290cb7f2-f87c-42b3-b2f3-0e22b5999cb5.PNG)

4
![3333](https://user-images.githubusercontent.com/55180847/138585020-e757352a-42c2-4274-9258-86cf89fe4db0.PNG)

5
![5555](https://user-images.githubusercontent.com/55180847/138585026-c5e55e05-63b3-446c-880e-73dd0e71f14e.PNG)

**Comment by babysor** [comment]
已在main修复
