### ISSUE TITLE
声音就像电钻

### ISSUE THREAD

**Issue by chenbo666-a** [babysor/MockingBird#173]
ValueError: Axis limits cannot be NaN or Inf

**Comment by hhhhhhogan** [comment]
> 参考 https://zhuanlan.zhihu.com/p/425692267 并使用模型 链接：https://pan.baidu.com/s/1fMh9IlgKJlL2PIiRTYDUvw 提取码：om7f --来自百度网盘超级会员V3的分享

这个模型是放在哪里？

**Comment by biezhi** [comment]
> > 参考 https://zhuanlan.zhihu.com/p/425692267 并使用模型 链接：https://pan.baidu.com/s/1fMh9IlgKJlL2PIiRTYDUvw 提取码：om7f --来自百度网盘超级会员V3的分享
> 
> 这个模型是放在哪里？

`synthesizer/saved_models` 目录下

**Comment by StevenLi-phoenix** [comment]
ValueError: Axis limits cannot be NaN or Inf
check this similar issue

[https://github.com/babysor/MockingBird/issues/170](https://github.com/babysor/MockingBird/issues/170)

@FrankPeng2014 @chenbo666-a @jiashihuigithub
