### ISSUE TITLE
用colab和谷歌云服务器预处理时，出现了AssertionError

### ISSUE THREAD

**Issue by kulu2001** [babysor/MockingBird#183]
~/MockingBird$ python pre.py dateAISHELL3 -d aishell3
Traceback (most recent call last):
  File "pre.py", line 57, in <module>
    assert args.datasets_root.exists()
AssertionError

colab和谷歌云都出现了相同的错误，版本都是用git clone 抓取的最新版

**Comment by kulu2001** [comment]
路径错误，已经解决

**Comment by Antislumber** [comment]
> 

大佬是什么路径问题啊，怎么解决了我预处理也遇到这个AssertionError的问题了
