### ISSUE TITLE
请教下mocking bird的头像怎么获得的？

### ISSUE THREAD

**Issue by inkzk** [babysor/MockingBird#187]
即“大脑+鸟”那个图标
感觉非常不错，是代码生成的嘛？

**Comment by kslz** [comment]
盲猜是作者找组里的美工做的 花费应该在5杯奶茶之内

**Comment by babysor** [comment]
miro 一分钱不花

**Comment by inkzk** [comment]
> miro 一分钱不花

miro.com? 自己手动做的嘛？

**Comment by babysor** [comment]
> > miro 一分钱不花
> 
> miro.com? 自己手动做的嘛？

嗯，折腾
