### ISSUE TITLE
toolbox运行时报错：Model files not found. Please download the models

### ISSUE THREAD

**Issue by LJure** [babysor/MockingBird#189]
使用的是Windows11 系统
预先训练好的模型已经按照要求放在了 synthesizer/saved_models 下
![屏幕截图 2021-11-03 231003](https://user-images.githubusercontent.com/52845776/140087860-14299828-62e6-46cd-985c-625ef8cc2b11.png)
已经检查过第三方库和FFmpeg的安装状态，使用power shell运行时会报错
![屏幕截图 2021-11-03 225425](https://user-images.githubusercontent.com/52845776/140088148-bdc14361-e290-4ffd-9fab-b126aca59567.png)

**Comment by babysor** [comment]
要在项目根目录下运行toolbox

**Comment by LJure** [comment]
> 要在项目根目录下运行toolbox

解决了，谢谢大佬🤭

**Comment by tianming937** [comment]
怎么解决的？我也是一模一样的报错。“要在项目根目录下运行toolbox”是怎么操作？

**Comment by LJure** [comment]
> 怎么解决的？我也是一模一样的报错。“要在项目根目录下运行toolbox”是怎么操作？
 就是在项目根目录下运行power shell或者cmd，或者使用cd命令将工作目录切换到项目根目录也可以

**Comment by LJure** [comment]
> 怎么解决的？我也是一模一样的报错。“要在项目根目录下运行toolbox”是怎么操作？

就是以项目根目录作为power shell 或者cmd的工作目录，在项目根目录内右键，选择“在power shell中打开”或者使用cd命令切换工作目录
