### ISSUE TITLE
按照quick start 构建，下载训练好的模型，为啥输出一直是杂音？

### ISSUE THREAD

**Issue by Huimieer** [babysor/MockingBird#196]
刚开始弄，下载社区训练好的模型，全是杂音啊。mel spectrogram明显不对

**Comment by babysor** [comment]
ceshi的模型需要将代码切换到10月20号左右的commit之后，再按issue #37 修改之后就可以用了
而作者的模型，需要将代码切换到10月20号左右的commit之后

**Comment by Huimieer** [comment]
> ceshi的模型需要将代码切换到10月20号左右的commit之后，再按issue #37 修改之后就可以用了 而作者的模型，需要将代码切换到10月20号左右的commit之后

好的，我试一下。

**Comment by ymilv** [comment]
可是作者最新的Commit是“Commits on Nov 13, 2021”啊？哪儿来的10月20日的commit？还有，“ceshi的模型需要将代码切换到10月20号左右的commit之后，再按issue #37 修改之后就可以用了，而作者的模型，需要将代码切换到10月20号左右的commit之后”，你这是写错了吧？都是要10月20日之后的？还是有一个打错字了？

**Comment by ymilv** [comment]
“ceshi的模型需要将代码切换到10月20号左右的commit之后，再按issue #37 修改之后就可以用了，而作者的模型，需要将代码切换到10月20号左右的commit之后”，你这是写错了吧？都是要10月20日之后的？还是有一个打错字了？

**Comment by babysor** [comment]
> “ceshi的模型需要将代码切换到10月20号左右的commit之后，再按issue #37 修改之后就可以用了，而作者的模型，需要将代码切换到10月20号左右的commit之后”，你这是写错了吧？都是要10月20日之后的？还是有一个打错字了？

语文差。。是切换到那个时间左右的commit，之后/再使用就可以了
