### ISSUE TITLE
关于英文语音的支持情况

### ISSUE THREAD

**Issue by hsien999** [babysor/MockingBird#214]
@babysor :
作者你好！我现在使用v0.001tag的版本，并对ReadMe中公开的4个预训练模型均进行了本地测试，其中除了ceshi模型可以较好地实现中文语音效果外，其他模型的中英文测试都有异常（即使参照issue解决了部分问题）。
现在我更倾向于实现英文语音的模仿，请问以上提到的预训练模型只针对中文语音吗？如果是的，我该如何使用本项目做英文语音的训练？

**Comment by kslz** [comment]
这个项目就是从英文语音项目分叉来的，你可以直接去看这个https://github.com/CorentinJ/Real-Time-Voice-Cloning 他们提供了效果很好的英文模型

**Comment by vkter** [comment]
使用原项目提供的英文模型得到的语音是杂音，

**Comment by vkter** [comment]
可以改进吗

**Comment by babysor** [comment]
直接训练synthesizer喂英文语料即可。encoder、vocoder可以不变

**Comment by babysor** [comment]
https://github.com/babysor/MockingBird/issues/440
