### ISSUE TITLE
载入模型pretrained-11-7-21_75k.pt。报错：size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([512, 256]).

### ISSUE THREAD

**Issue by pyli0628** [babysor/MockingBird#216]
打开demo_toolbox后，载入模型pretrained-11-7-21_75k.pt， 点击第一次synthesize，报上述size mismatch错，再点击一次synthesize可以生成。另外对synthesizer重新训练，在载入模型时也会报size mismatch错

**Comment by cuifuKim** [comment]
我也是这种情况，救命

**Comment by cuifuKim** [comment]
@babysor 求助作者，提供的模型跑出来全是类似这个情况，咋解呀

**Comment by babysor** [comment]
Fixed. 拉最新代码或在 synthesizer/hparams.py 最后一参数改为True

**Comment by WindySeason1** [comment]
俺也一样。第二次跑出来的全是杂音

**Comment by cuifuKim** [comment]
> Fixed. 拉最新代码或在 synthesizer/hparams.py 最后一参数改为True

解决了，感谢

**Comment by pyli0628** [comment]
> Fixed. 拉最新代码或在 synthesizer/hparams.py 最后一参数改为True

问题解决，非常感谢
