### ISSUE TITLE
demo闪退

### ISSUE THREAD

**Issue by 1pipi2** [babysor/MockingBird#217]
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\__init__.py", line 76, in __init__
    self.setup_events()
  File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\__init__.py", line 113, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\ui.py", line 149, in setup_audio_devices
    for device in sd.query_devices():
  File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in query_devices
    return DeviceList(query_devices(i)
  File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in <genexpr>
    return DeviceList(query_devices(i)
  File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 573, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by 1pipi2** [comment]
网页版报错
Uncaught Error】Uncaught SyntaxError: Unexpected token '<'
at:1:1 url:http://localhost:8080/
SyntaxError: Unexpected token '<'
    at Function.onload (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Magic%2520Userscript%252B%2520%253A%2520Show%2520Site%2520All%2520UserJS.user.js&id=91699e5b-1e20-450a-bbaf-8e2d6d8785d8:71:17)
    at s (:8:264)
    at eval (eval at exec_fn (:1:455), :21:226)
    at s (:8:264)
    at i (eval at exec_fn (:1:455), :3:215)
    at eval (eval at exec_fn (:1:455), :3:342)
    at :5:275
    at HTMLDocument._ (:5:294)

**Comment by babysor** [comment]
> Feel free to add your own. You can still use the toolbox by recording samples yourself. Traceback (most recent call last): File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\demo_toolbox.py", line 43, in Toolbox(**vars(args)) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 76, in **init** self.setup_events() File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 113, in setup_events self.ui.setup_audio_devices(Synthesizer.sample_rate) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\ui.py", line 149, in setup_audio_devices for device in sd.query_devices(): File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in query_devices return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 573, in query_devices name = name_bytes.decode('utf-8') UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

 查看readme的常见问题

**Comment by 1pipi2** [comment]
![image](https://user-images.githubusercontent.com/53045584/142722123-6ca27efe-c0bb-4931-afa1-dda2753f499e.png)

**Comment by 1pipi2** [comment]
> > Feel free to add your own. You can still use the toolbox by recording samples yourself. Traceback (most recent call last): File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\demo_toolbox.py", line 43, in Toolbox(**vars(args)) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 76, in **init** self.setup_events() File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 113, in setup_events self.ui.setup_audio_devices(Synthesizer.sample_rate) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\ui.py", line 149, in setup_audio_devices for device in sd.query_devices(): File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in query_devices return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 573, in query_devices name = name_bytes.decode('utf-8') UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
> 
> 查看readme的常见问题

更新数据库，也改了issue37，调整了size大小，还是报错

**Comment by babysor** [comment]
> > > Feel free to add your own. You can still use the toolbox by recording samples yourself. Traceback (most recent call last): File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\demo_toolbox.py", line 43, in Toolbox(**vars(args)) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 76, in **init** self.setup_events() File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox__init__.py", line 113, in setup_events self.ui.setup_audio_devices(Synthesizer.sample_rate) File "C:\Users\sha7dow\OneDrive - longessay\文档\GitHub\MockingBird\toolbox\ui.py", line 149, in setup_audio_devices for device in sd.query_devices(): File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in query_devices return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 559, in return DeviceList(query_devices(i) File "C:\ProgramData\Anaconda3\envs\a\lib\site-packages\sounddevice.py", line 573, in query_devices name = name_bytes.decode('utf-8') UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
> > 
> > 
> > 查看readme的常见问题
> 
> 更新数据库，也改了issue37，调整了size大小，还是报错

[不是数据库，而是](https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF)

**Comment by babysor** [comment]
@1pipi2 已经可用了吗？

**Comment by JOJOda123** [comment]
有没有闪退呢，我之前启动GUI闪退了然后按照作者这个方法就可以了，链接：https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF
