### ISSUE TITLE
生成电子杂音，按#37修改没用

### ISSUE THREAD

**Issue by jacktonshaw** [babysor/MockingBird#218]
> 
![微信截图_20211114183459](https://user-images.githubusercontent.com/94291182/141677422-429f4818-95ce-44d8-ad06-cf7ec56e71ab.png)
界面也跟https://www.bilibili.com/video/BV1uh411B7AD/展示的不一样

**Comment by jacktonshaw** [comment]
https://www.bilibili.com/video/BV1uh411B7AD/

**Comment by babysor** [comment]
看起来pytorch没装好，重新装一下

**Comment by jacktonshaw** [comment]
没有切换到tag0.01，所以不行，现在可以了

**Comment by 463315341** [comment]
> 没有切换到tag0.01，所以不行，现在可以了

请问下tag0.01是指的什么
