### ISSUE TITLE
可以音频文件导入吗

### ISSUE THREAD

**Issue by as882301** [babysor/MockingBird#222]
录音进去 那步可以 支持直接导入已有音频吗

**Comment by ffffreeyu** [comment]
> 录音进去 那步可以 支持直接导入已有音频吗
![image](https://user-images.githubusercontent.com/58197813/142602244-a53d7b78-bb04-492b-a46b-d7fedf8a245c.png)

**Comment by silenceli** [comment]
+1

**Comment by babysor** [comment]
可以的

**Comment by ffffreeyu** [comment]
![image](https://user-images.githubusercontent.com/58197813/142649782-9f88d1e5-ebc3-4fca-ad80-2844949cd7e6.png)

**Comment by as882301** [comment]
> 

好的 谢谢
