### ISSUE TITLE
在跑了一下之后更换75k的预训练模型报错

### ISSUE THREAD

**Issue by Hetols** [babysor/MockingBird#224]
按照之前issue里的方法修改了仍然报错，Tag0.0.1也不行
Arguments:
    run_id:          test
    syn_dir:         ..\DataMaker\SV2TTS\synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    log_every:       200
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\test\test.pt
Loading training data from: ..\DataMaker\SV2TTS\synthesizer\train.txt
Using model: Tacotron
Using device: cuda

Initialising Tacotron Model...

WARNING: you are using compatible mode due to wrong sympols length, please modify varible _characters in `utils\symbols.py`
Trainable Parameters: 32.866M

Loading weights at synthesizer\saved_models\test\test.pt
Traceback (most recent call last):
  File "D:\ProgrameWork\Deep\Voice\MockingBird\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "D:\ProgrameWork\Deep\Voice\MockingBird\synthesizer\train.py", line 114, in train
    model.load(weights_fpath, optimizer)
  File "D:\ProgrameWork\Deep\Voice\MockingBird\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\Users\Hetols\AppData\Roaming\Python\Python39\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([75, 512]) from checkpoint, the shape in current model is torch.Size([70, 512]).

**Comment by babysor** [comment]
是新训练的模型吗？

**Comment by Hetols** [comment]
> 是新训练的模型吗？

是在开始训练新模型后（已经生成了文件），按Ctrl+C退出控制台，替换后再次执行就会出错。
在此之后，如果删除替换的模型（重新开始） 或 替换回之前的模型，它又可以正常运行。

**Comment by Hetols** [comment]
已经解决了，11月18日更新的代码无修改+75K可以正常运行
