### ISSUE TITLE
出现很重的电子音

### ISSUE THREAD

**Issue by bitjerry** [babysor/MockingBird#226]
我没有使用数据集, 我使用的是训练好的模型pretrained-11-7-21_75k
结果合成出来的音频有很严重的电子音, 尝试合成多次都无法消除
我看到了之前您提出的解决方法'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '
但修改后反而出现了
self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\null\python3.8\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([75, 512]) from checkpoint, the shape in current model is torch.Size([70, 512]).

没有修改之前是可以正常使用的, 但会有无法消除的电子音, 我应该如何解决这个问题?

**Comment by DQ2020scut** [comment]
同问

**Comment by babysor** [comment]
> 我没有使用数据集, 我使用的是训练好的模型pretrained-11-7-21_75k 结果合成出来的音频有很严重的电子音, 尝试合成多次都无法消除 我看到了之前您提出的解决方法'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!'(),-.:;? ' 但修改后反而出现了 self.load_state_dict(checkpoint["model_state"], strict=False) File "C:\null\python3.8\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Tacotron: size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([75, 512]) from checkpoint, the shape in current model is torch.Size([70, 512]).
> 
> 没有修改之前是可以正常使用的, 但会有无法消除的电子音, 我应该如何解决这个问题?

如何是能听清楚发音 但是有电子音的话 可以看下教程中提到的使用技巧或者自己再训练。
