### ISSUE TITLE
无法运行demo_toolbox

### ISSUE THREAD

**Issue by CodeMXQ** [babysor/MockingBird#227]
打不开demo_toolbox,出现了下述情况

C:\ffmpeg-4.4.1-essentials_build\MockingBird-main>python demo_toolbox.py
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by CodeMXQ** [comment]
我重装了pyqt5，无法解决

**Comment by babysor** [comment]
系统相关信息可以贴一下吗？看情况你没有装python虚拟环境？

**Comment by CodeMXQ** [comment]
我是按照一个视频流程来的，确实没装anaconda,我去试试

**Comment by babysor** [comment]
> 我是按照一个视频流程来的，确实没装anaconda,我去试试

如果系统之前python有比较多依赖的冲突，很难跑起来

**Comment by CodeMXQ** [comment]
虽然不知道发生了什么，但是解决了，确实是要放在环境里

**Comment by CodeMXQ** [comment]
> 虽然不知道发生了什么，但是解决了，确实是要放在环境里

Warning: you did not pass a root directory for datasets as argument.

**Comment by babysor** [comment]
> > 虽然不知道发生了什么，但是解决了，确实是要放在环境里
> 
> Warning: you did not pass a root directory for datasets as argument.

百度翻译一下就知道了。。。
