### ISSUE TITLE
attention效果图不好

### ISSUE THREAD

**Issue by oerooo** [babysor/MockingBird#228]
只用了aidatatang200作为训练集，80k的时候loss大约是0.49左右，但是attention一直没有一个线性表示，这是为什么呢？还有保存的attention图是热度图么？横坐标是encoder纵坐标是decoder？
![image](https://user-images.githubusercontent.com/76580931/142973844-c477afa8-81a2-4904-959c-c0bccd0c0074.png)
![Uploading image.png…]()

**Comment by babysor** [comment]
可以在前1w步多重试一两次，可能会有意想不到的好效果
