### ISSUE TITLE
输入一个mp3报错了，请问是啥原因？

### ISSUE THREAD

**Issue by deiphi** [babysor/MockingBird#23]
![111](https://user-images.githubusercontent.com/3659715/130170666-7c9db578-6c7e-400a-aa7d-42423d26e0da.png)

**Comment by babysor** [comment]
看报错应该是格式不支持, 试一下: 在线转wav?

**Comment by deiphi** [comment]
> 看报错应该是格式不支持, 试一下: 在线转wav?

您好，试过了，还是不行。

**Comment by cronfox** [comment]
> > 看报错应该是格式不支持, 试一下: 在线转wav?
> 
> 您好，试过了，还是不行。

我看了一下sample里的文件
里头文件的采样率是16Khz
可以试试转一下

**Comment by babysor** [comment]
Duplicated with #37
