### ISSUE TITLE
方言的训练相关问题

### ISSUE THREAD

**Issue by ycMia** [babysor/MockingBird#232]
想请教如何创建一个方言数据集并合理生成模型? 目标是训练 **上海话** 以及其它吴语系方言

**Comment by babysor** [comment]
已经有足量的数据集了吗？

**Comment by ycMia** [comment]
> 已经有足量的数据集了吗？

有条件生成足量的音源样本，但是不知道训练所需的文件格式(除了.wav之外的文件)

**Comment by ycMia** [comment]
>啊
>想到应该怎么问这个问题了

请问方言在数据集内如何标注拼音呢

**Comment by babysor** [comment]
不同方言应该不太一样，举个例子我如果处理潮汕话或者粤语，可能 phenomenon 后面跟随的数字会是 1-8，而不是现在普通话的1-5

**Comment by hertz-pj** [comment]
@ycMia 方言这个问题可以群里提问，你数据没问题的话，我们可以交流一下~

**Comment by TangBunao** [comment]
> 已经有足量的数据集了吗？

请问足量的数据集是指多少呢，最低要求大概是多少呢，谢谢您

**Comment by babysor** [comment]
> > 已经有足量的数据集了吗？
> 
> 请问足量的数据集是指多少呢，最低要求大概是多少呢，谢谢您

最好是百小时级别，如果无法达到要求，就需要比较多其他专业技巧了
