### ISSUE TITLE
能输入日语吗

### ISSUE THREAD

**Issue by LxnChan** [babysor/MockingBird#233]
有足够的样本的前提下我想自己训练出来一个日语模型，不知道行不行

**Comment by babysor** [comment]
你这边有足够的数据集的话，应该是没有问题，要找到一个tts前端处理一下日语为phenomenon

**Comment by LxnChan** [comment]
> 你这边有足够的数据集的话，应该是没有问题，要找到一个tts前端处理一下日语为phenomenon

好的，我试一下。
另外您提到 `要找到一个tts前端处理一下日语为phenomenon` 是什么意思呢？求解答

**Comment by babysor** [comment]
就是把中文句子例如 “你好” 变成 “ni2 hao3”

**Comment by Emiya0415** [comment]
请问下足够的数据集指的是用许多不同人的声音的数据集来训练synthesizer模型吗？大概需要多少人和多少个小时的数据呢？
如果我只想获得一个特定的人的日语声音并且拥有该特定人的足够多声音（2000条以上），是否能够实现这一个人的日语输出呢

**Comment by babysor** [comment]
> 请问下足够的数据集指的是用许多不同人的声音的数据集来训练synthesizer模型吗？大概需要多少人和多少个小时的数据呢？ 如果我只想获得一个特定的人的日语声音并且拥有该特定人的足够多声音（2000条以上），是否能够实现这一个人的日语输出呢

看着不够，时长多少呢？

**Comment by Emiya0415** [comment]
> > 请问下足够的数据集指的是用许多不同人的声音的数据集来训练synthesizer模型吗？大概需要多少人和多少个小时的数据呢？ 如果我只想获得一个特定的人的日语声音并且拥有该特定人的足够多声音（2000条以上），是否能够实现这一个人的日语输出呢
> 
> 看着不够，时长多少呢？

15个小时左右吧，我只想要获取这一个人的声音也不可以吗

**Comment by babysor** [comment]
那你先得训练一个可用的模型，再finetune就可以

**Comment by Emiya0415** [comment]
> 那你先得训练一个可用的模型，再finetune就可以

finetune是和原来的pretrain模型进行还是和这个项目的模型进行效果会更好？还是说没进行之前也不知道结果呢。
还有如果是不同的语言的话（和这个的中文和原项目的英文不同的语言），是否需要进行2.3的训练声码器呢

**Comment by babysor** [comment]
后续讨论请移步： https://github.com/babysor/MockingBird/issues/440
