### ISSUE TITLE
请问可否设计一份训练中断后重启并避开已训练数据集的功能?

### ISSUE THREAD

**Issue by ycMia** [babysor/MockingBird#235]
如题， 在 戴尔G15 rtx3050 4G, cuda11.3 的环境下遇到了显存不足后训练中断的情况 (一天内发生三次)
在输入相同指令后，程序又把原本跑过的数据集又跑了一遍...

训练数据集使用_200zh， Batch Size =4

**Comment by ycMia** [comment]
啊，cuda版本是`V11.5.50`看错了抱歉...

**Comment by yemaohaker** [comment]
我用的是1050ti 内存不足就调小了batch_size  

一定要配置好cuda 用的是11.5版本，配置好了速递可以达到0.7-0.8左右的step/s

没配置前只有0.035step/s
差距很大

![image](https://user-images.githubusercontent.com/54471945/143535961-b907faf8-ef3b-4eb4-bdf6-7eb6c778994a.png)

**Comment by xros** [comment]
准备用m1 做训练，统一内存怕是还不如1050Ti . Pytorch在m1上目前只支持cpu

**Comment by wrk226** [comment]
数据集每次加载都会随机打乱，不需要刻意避开。
