### ISSUE TITLE
最大输入文数目

### ISSUE THREAD

**Issue by 443127316** [babysor/MockingBird#236]
作者大大，以及群里的各位大神，求助哈。

我在使用网页版的时候，发现最多只能识别10个字（不加标点符号，不加换行符）
为了增加可以识别的字符数，我更改gst_hyperparameters.py 中的 token_num = 40 但是训练之后，依然没有效果，请问如果想要支持四十个字输入，参数应该怎么调整，再次感谢，

**Comment by babysor** [comment]
你代码已经是最新的吗？这里不是修改token num而是在synthesizer inference的时候 ，有个最大iteration参数，参考demo tool的最大句长参数修改即可

**Comment by 443127316** [comment]
已经通过和大神的交流，问题解决了，在这里把方法记录一下，修改 tacotron.py 中 generate函数中的step参数，目前最新版本已经修该到了2000，已经没有字数限制了。
