### ISSUE TITLE
训练hifigan vocoder不输出.pt模型，只有log

### ISSUE THREAD

**Issue by HuaHuaOfficial** [babysor/MockingBird#237]
如题，训练能跑起来但不输出.pt。这应该不是个案了

**Comment by xros** [comment]
最好发一下系统平台配置，以及’pip freeze’ 软件版本，这样才有人会回复

**Comment by babysor** [comment]
保存点的steps之前写太多了，没有临时保存，等会修复一下。

**Comment by hertz-pj** [comment]
已解决 #240

**Comment by luobingit** [comment]
还是只输出了log，我已经把代码里面的save_every改为10了  还是不行 
![image](https://user-images.githubusercontent.com/68454150/145944273-68d73f4f-84b9-40c9-abe2-3703383e5b3a.png)

**Comment by luobingit** [comment]
@HuaHuaOfficial 大佬  你的可以了吗

**Comment by hertz-pj** [comment]
> @HuaHuaOfficial 大佬 你的可以了吗

你拉取最新版本的代码了吗？

**Comment by luobingit** [comment]
> > @HuaHuaOfficial 大佬 你的可以了吗
> 
> 你拉取最新版本的代码了吗？

拉取了 最新的main分支 训练时有个警告  然后就一直在训练 但是目录没有模型生成 只有log
![image](https://user-images.githubusercontent.com/68454150/145946615-124719ec-50aa-466b-8dbe-ce96f7a6747f.png)
![image](https://user-images.githubusercontent.com/68454150/145946668-8742b983-a1d9-4564-a432-cd8f5de3cba1.png)
![image](https://user-images.githubusercontent.com/68454150/145946767-148d0d54-1400-4094-a5fc-637110dc6507.png)

**Comment by luobingit** [comment]
最新代码训练wavernn模型时也有bug  可以试试看  我改了一下代码可以用了  因为不是专业写python的就不pr了
![image](https://user-images.githubusercontent.com/68454150/145950597-854c3875-ed6c-4597-b697-3646ff56df37.png)
![image](https://user-images.githubusercontent.com/68454150/145950596-2950173a-110e-4d03-804e-7fb5c2910b45.png)

**Comment by icendragon-diao** [comment]
> 最新代码训练wavernn模型时也有bug 可以试试看 我改了一下代码可以用了 因为不是专业写python的就不pr了 ![image](https://user-images.githubusercontent.com/68454150/145950597-854c3875-ed6c-4597-b697-3646ff56df37.png) ![image](https://user-images.githubusercontent.com/68454150/145950596-2950173a-110e-4d03-804e-7fb5c2910b45.png)

遇到同样问题，请问如何修改？

**Comment by icendragon-diao** [comment]
> 最新代码训练wavernn模型时也有bug 可以试试看 我改了一下代码可以用了 因为不是专业写python的就不pr了 ![image](https://user-images.githubusercontent.com/68454150/145950597-854c3875-ed6c-4597-b697-3646ff56df37.png) ![image](https://user-images.githubusercontent.com/68454150/145950596-2950173a-110e-4d03-804e-7fb5c2910b45.png)

我也遇到了只有log的问题，请问如何修改代码？

**Comment by HaSaKiYasuooo** [comment]
> > 最新代码训练wavernn模型时也有bug 可以试试看 我改了一下代码可以用了 因为不是专业写python的就不pr了 ![image](https://user-images.githubusercontent.com/68454150/145950597-854c3875-ed6c-4597-b697-3646ff56df37.png) ![image](https://user-images.githubusercontent.com/68454150/145950596-2950173a-110e-4d03-804e-7fb5c2910b45.png)
> 
> 我也遇到了只有log的问题，请问如何修改代码？

我也遇见了这个问题，请问你们找到了解决方法吗，我也训练了1000布只有个log文件

**Comment by HaSaKiYasuooo** [comment]
> 如题，训练能跑起来但不输出.pt。这应该不是个案了

请问一下 怎么修改源文件来保存
