### ISSUE TITLE
用社区分享的模型训练报错 不知道原因

### ISSUE THREAD

**Issue by johnwestin** [babysor/MockingBird#238]
用社区分享的模型训练报错 不知道原因 而且不知道咋保存模型 是不是必须要每500步才会自动保存 求各位大佬解惑 感谢！
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3
![屏幕截图 2021-11-28 021942](https://user-images.githubusercontent.com/95144185/143707509-5920ecfe-e109-4c2f-b383-ed77ceddb8d9.jpg)

**Comment by babysor** [comment]
不同模型后面有个代码版本的说明，你这个应该需要修改到旧版代码

**Comment by johnwestin** [comment]
大佬您好，我试着修改代码，将symbols.py第11句改成了之前的代码，但还是报错，错误代码变了，请问具体代码应该怎么修改，谢谢
![12345](https://user-images.githubusercontent.com/95144185/143729905-3e81f11e-f035-4c28-8207-6e1191b82865.jpg)
![屏幕截图 2021-11-28 123748](https://user-images.githubusercontent.com/95144185/143729906-7da71d82-0903-484a-abb4-632c0292fc5a.jpg)

**Comment by johnwestin** [comment]
> 不同模型后面有个代码版本的说明，你这个应该需要修改到旧版代码

大佬您好，我试着修改代码，将symbols.py第11句改成了之前的代码，但还是报错，错误代码变了，请问具体代码应该怎么修改，谢谢
![12345](https://user-images.githubusercontent.com/95144185/143729945-9bf24f29-54b2-46a1-85c3-9afd79433b72.jpg)
![屏幕截图 2021-11-28 123748](https://user-images.githubusercontent.com/95144185/143729947-c666859d-1a8c-4ed5-9147-df538b74426c.jpg)

**Comment by babysor** [comment]
你具体用的哪个模型？

**Comment by johnwestin** [comment]
> 你具体用的哪个模型？

您好，使用的是“pretrained-11-7-21_75k.pt”这个模型，错误代码如下，刚才使用的是issues里今天另一位大佬新传的，都显示错误代码
![12e](https://user-images.githubusercontent.com/95144185/143730403-e8de647c-83ce-4990-b9fe-2ccbe20a649c.jpg)

**Comment by babysor** [comment]
把symbols的修改改回去

**Comment by johnwestin** [comment]
您好，改回去就显示“RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3”，又回去了

**Comment by johnwestin** [comment]
> 把symbols的修改改回去

您好，改回去就显示“RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3”，又回去了

**Comment by babysor** [comment]
拉最新master的代码

**Comment by johnwestin** [comment]
> 拉最新main的代码

**Comment by johnwestin** [comment]
> 拉最新main的代码
感谢大佬 现在能运行了 再请问一下如何保存进度，是按ctrl+c吗

**Comment by johnwestin** [comment]
> 把symbols的修改改回去

感谢大佬 现在能运行了 再请问一下如何保存进度，是按ctrl+c吗

**Comment by johnwestin** [comment]
> 拉最新main的代码

感谢大佬 现在能运行了 再请问一下如何保存进度，是按ctrl+c吗

**Comment by Olivia-Ye** [comment]
> 

训练的时候通过参数可以设置多少step保存模型，多少step保存一个新的pt模型

**Comment by babysor** [comment]
> > 拉最新main的代码
> 
> 感谢大佬 现在能运行了 再请问一下如何保存进度，是按ctrl+c吗

自动保存，1000 step一次 @Olivia-Ye

**Comment by johnwestin** [comment]
> > 
> 
> 训练的时候通过参数可以设置多少step保存模型，多少step保存一个新的pt模型

感谢大佬解答

**Comment by johnwestin** [comment]
> > > 拉最新main的代码
> > 
> > 
> > 感谢大佬 现在能运行了 再请问一下如何保存进度，是按ctrl+c吗
> 
> 自动保存，1000 step一次 @Olivia-Ye

感谢大佬解答
