### ISSUE TITLE
直接用由dataset生成语音用什么好？

### ISSUE THREAD

**Issue by sovzzz** [babysor/MockingBird#246]
做一个游戏mod，想由现有的游戏语音文件来合成新配音，tarcon训练出了dataset就不知道怎么搞了。

**Comment by GITHUBGUY12357999** [comment]
Linked pull requests
Successfully merging a pull request may close this issue.

**Comment by GITHUBGUY12357999** [comment]
這個問題拉取請求已經合併，所以你可以根據鏈接的結果關閉它。謝謝

**Comment by babysor** [comment]
> 這個問題拉取請求已經合併，所以你可以根據鏈接的結果關閉它。謝謝

 这里指哪个拉取请求呢？

**Comment by GITHUBGUY12357999** [comment]
YES
YOU CAN MERGE

**Comment by GITHUBGUY12357999** [comment]
我不知道業主必須告訴我們這是指哪個問題。

**Comment by GITHUBGUY12357999** [comment]
i can close the issue, if u like me too
