### ISSUE TITLE
报错：RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

### ISSUE THREAD

**Issue by MeetSongta** [babysor/MockingBird#249]
作者你好，我使用的web.py运行的demo，百度云下载的synthesizer，生成语音的时候报错，请问有解决办法吗？
csdn的一个回答是这样的，我没找到
“”“
在训练模型的时候，需要搞清楚有没有用多GPU训练

使用pytorch正常加载模型的话：

model.load_state_dict(torch.load(model_path))
1
如果在训练的时候使用到了多GPU训练

model = torch.nn.DataParallel(model, device_ids=range(opt.ngpu))
”“”

**Comment by Howie-hxu** [comment]
你应该使用的代码版本比较新，但是百度下载的synthesizer是旧版本的，因此需要先把代码切换到旧版本，即tag v0.0.1，然后再加入#issue 37的修改，就可以跑了。
这里跟多gpu训练无关
切换分支的命令：git checkout -b local_tag_v0.0.1 v0.0.1

**Comment by babysor** [comment]
#209
