### ISSUE TITLE
在文字框写了文字，可是出來的是其它聲音，是不是文字框bug了

### ISSUE THREAD

**Issue by wangkewk** [babysor/MockingBird#25]
![image](https://user-images.githubusercontent.com/31000405/130176550-abd4baf0-0e0b-4d80-9c16-c614dbe7ae24.png)
谁能解决

**Comment by XiuChen-Liu** [comment]
> ![image](https://user-images.githubusercontent.com/31000405/130176550-abd4baf0-0e0b-4d80-9c16-c614dbe7ae24.png)
> 谁能解决

看demo影片好像是要直接用拼音

**Comment by wangkewk** [comment]
输入拼音也不行，出现的声音根本不是文字框里的，

**Comment by XiuChen-Liu** [comment]
> 输入拼音也不行，出现的声音根本不是文字框里的，

你有訓練完模型對吧

**Comment by wangkewk** [comment]
没有

**Comment by wangkewk** [comment]
訓练了一半，试了一下

**Comment by XiuChen-Liu** [comment]
> 訓练了一半，试了一下

如果拿百度雲上的模型來用，看一下 #24 討論的可能是答案
那可能要訓練完看看了

**Comment by XiuChen-Liu** [comment]
我先說我沒有看完整的代碼，但文字框不能用說不定是有哪一部分程式碼沒有 run 起來導致不能用，這是我的猜測

**Comment by wangkewk** [comment]
那我試一下，训练完看看

**Comment by babysor** [comment]
> 訓练了一半，试了一下

1. 试着用更长的句子
2. 你训练的时候,可以看下synthesizer目录下对应的plot文件夹,看看是否出现attention 对齐线,如下所示:
https://user-images.githubusercontent.com/7423248/128587252-f669f05a-f411-4811-8784-222156ea5e9d.png
如果没有,说明还没训练到位

**Comment by wangkewk** [comment]
好，我试试，这个问题先不关闭

**Comment by babysor** [comment]
已经修复了，可以拉最新代码试一下 @wangkewk
