### ISSUE TITLE
进行音频和梅尔频谱图预处理时报错

### ISSUE THREAD

**Issue by txql** [babysor/MockingBird#258]
![屏幕截图 2021-12-10 002255](https://user-images.githubusercontent.com/95873082/145435133-c344724b-9bea-4eb5-a68c-0ddee1409b72.png)

**Comment by txql** [comment]
(base) C:\Kuang\MockingBird-main>python pre.py D:\data
Using data from:
    D:\data\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|████████████████████████████████████████████████████████| 420/420 [01:00<00:00,  7.92speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "C:\Kuang\MockingBird-main\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by txql** [comment]
![image](https://user-images.githubusercontent.com/95873082/145550840-f71c3329-d735-43d2-86c6-c7f737a7684b.png)

**Comment by babysor** [comment]
没有解压，需要二度解压，详见教程
