### ISSUE TITLE
模型训练时有 Creating a tensor from a list of numpy.ndarrays is extremely slow.警告会影响训练吗

### ISSUE THREAD

**Issue by luobingit** [babysor/MockingBird#259]
![image](https://user-images.githubusercontent.com/68454150/145553333-0e8dfc70-384f-4968-87bf-09f511243dd4.png)

**Comment by luobingit** [comment]
还有我使用aishell3模型进行训练 以下两个标注的文本文件需要吗  还是只要音频文件就行
![image](https://user-images.githubusercontent.com/68454150/145557838-be3ba1cb-b8ed-46d7-8da5-3a86ba7e23ed.png)

**Comment by GENGCONG2017** [comment]
我也遇到这个情况，盼高人指点一下为何报Creating a tensor from a list of numpy.ndarrays is extremely slow。有什么办法解决吗？用的是git上master最新版本Tue Dec 7。什么都没有改动

**Comment by luobingit** [comment]
> 还有我使用aishell3模型进行训练 以下两个标注的文本文件需要吗 还是只要音频文件就行 ![image](https://user-images.githubusercontent.com/68454150/145557838-be3ba1cb-b8ed-46d7-8da5-3a86ba7e23ed.png)

看了一下源码  只要标注content.txt文件就行  可以使用程序自动标注  Java这边可以使用pinyin4j
![image](https://user-images.githubusercontent.com/68454150/145811300-a0e5670d-5bd1-4bd3-9714-84e36ba8ad95.png)

**Comment by luobingit** [comment]
> ![image](https://user-images.githubusercontent.com/68454150/145553333-0e8dfc70-384f-4968-87bf-09f511243dd4.png)

自问自答一下  这个警告应该不影响训练

**Comment by wrk226** [comment]
在“synthesizer/synthesizer_dataset.py”的76行加上下面的代码就行了：
`embeds = np.stack(embeds)`
当然，训练速度并不会变快很多。

**Comment by luobingit** [comment]
> 在“synthesizer/synthesizer_dataset.py”的76行加上下面的代码就行了： `embeds = np.stack(embeds)` 当然，训练速度并不会变快很多。

多谢

**Comment by babysor** [comment]
> 在“synthesizer/synthesizer_dataset.py”的76行加上下面的代码就行了： `embeds = np.stack(embeds)` 当然，训练速度并不会变快很多。

方便发起pr吗？

**Comment by luobingit** [comment]
@babysor 作者你好  方便发一下入群二维码吗

**Comment by wrk226** [comment]
> 方便发起pr吗？
发了pr啦

**Comment by babysor** [comment]
> @babysor 作者你好 方便发一下入群二维码吗

进群了吗？

**Comment by babysor** [comment]
> > 方便发起pr吗？
> 
> 发了pr啦

那我关闭本issue了
