### ISSUE TITLE
是小白，刚用ceshi不知道为什么出现这样的问题，请教一下大佬

### ISSUE THREAD

**Issue by lizexun** [babysor/MockingBird#260]
合成的声音只有2秒滋滋声，拉取的是最新代码，已参考#37 #209修改，
无CUDA，用的是 python demo_toolbox.py --cpu -d E:\MockingBird-Add-GST\data
库如下
![JLVH9MU_MSAVE~AY{W}FF0G](https://user-images.githubusercontent.com/62888460/145609446-9341e723-d2d8-4349-8cb2-fa5e871950c2.png)

![%YY`HJ1)8C}`F7UO3)N5IKA](https://user-images.githubusercontent.com/62888460/145609467-70e62a79-2a08-419e-9601-bb658468cc8e.png)

![I1E2M~C6Y7RZEYU)KN@D)GG](https://user-images.githubusercontent.com/62888460/145609503-c1d63f70-3458-4132-8af3-784ecd9217b4.png)

界面截图
![Y1RLL5N8U%VTRK%8GDR~ZE4](https://user-images.githubusercontent.com/62888460/145609557-4f9cd073-cc2b-4e8c-a56f-12dd2b05c3d7.png)

**Comment by godspeed-w** [comment]
同样问题，生成的只有两秒滋滋声就没别的了，望解答

**Comment by Howie-hxu** [comment]
你需要切换到tag v0.0.1的版本，然后加入#issue 37的修改。
切换tag的命令：git checkout -b local_tag_0.0.1 v0.0.1

**Comment by lizexun** [comment]
在加入#issue 37 的修改后，执行
git checkout -b local_tag_0.0.1 v0.0.1
![image](https://user-images.githubusercontent.com/62888460/145702485-2d14bd46-3721-42e3-934f-2ed163ef3289.png)
   
再python demo_toolbox.py --cpu -d E:\MockingBird-Add-GST\data
问题仍在，RuntimeError: synthesizer\saved_models\mandarin\mandarin.pt is a zip archive (did you mean to use torch.jit.load()?)
下面是数据集的截图
![image](https://user-images.githubusercontent.com/62888460/145702465-f129efb4-9d74-41f7-9d47-7b5e684dfd5a.png)

![image](https://user-images.githubusercontent.com/62888460/145702472-ee2679da-bb81-484e-a4d2-e0b4db0749c6.png)

![image](https://user-images.githubusercontent.com/62888460/145702475-cd1bc1b5-0ed0-4b8c-9f7d-56411202165a.png)

**Comment by lizexun** [comment]
> 你需要切换到标签 v0.0.1 的版本，然后加入#issue 37 的修改。 切换标签的命令：git checkout -b local_tag_0.0.1 v0.0.1

在加入#issue 37 的修改后，执行
git checkout -b local_tag_0.0.1 v0.0.1
图片

再python demo_toolbox.py --cpu -d E:\MockingBird-Add-GST\data
问题持续，RuntimeError: synthesizer\saved_models\mandarin\mandarin.pt is a zip archive (did you mean to use torch.jit.load ()?)
下面是数据集的截图
图片

图片

图片

**Comment by lizexun** [comment]
> 

大佬，请看上面

**Comment by lizexun** [comment]
> 你需要切换到标签 v0.0.1 的版本，然后加入#issue 37 的修改。 切换标签的命令：git checkout -b local_tag_0.0.1 v0.0.1

大佬，请看上面

**Comment by Howie-hxu** [comment]
运行的时候可以不用加参数-d，不加数据集也是可以的

**Comment by wrk226** [comment]
pytorch版本太低

**Comment by 1Wizzy** [comment]
> 你需要切换到tag v0.0.1的版本，然后加入#issue 37的修改。 切换tag的命令：git checkout -b local_tag_0.0.1 v0.0.1

大佬，我为什么无法切换
![image](https://user-images.githubusercontent.com/54066145/146646571-262778ad-d992-4b9b-91ca-c6e5dd1d6ce5.png)
纯小白，什么都不懂，还为此下了个
![image](https://user-images.githubusercontent.com/54066145/146646587-841922ac-33fc-45e4-9439-2f92c7179ba4.png)

**Comment by huzhugongsheng** [comment]
> 你需要切换到tag v0.0.1的版本，然后加入#issue 37的修改。 切换tag的命令：git checkout -b local_tag_0.0.1 v0.0.1

切换到tag v0.0.1的版本对我是有效的。切换到tag并不容易，除了大佬提出的方法之外，我提出个笨拙些的解决方法：之间在code的页面找到tag，点击进之后下载就行，解压后进入这个文件进行相关的操作即可。

**Comment by Howie-hxu** [comment]
> 

你下载的那个是git的GUI图形操作工具，也是可以的，可以使用Git Bash来输入切换tag的命令。
你第一个框中的错误是找不到git.exe，原因是windows的命令行窗口需要添加环境变量，把git.exe所在的目录添进去，你应该是没有添，所以就报错了，可以参考百度的这个链接尝试做一下：https://www.cnblogs.com/qingmuchuanqi48/p/12052289.html

**Comment by Howie-hxu** [comment]
> 

是的是的，这个办法好，可以直接下载对应tag打包的源文件，避免了git的操作

**Comment by Howie-hxu** [comment]
> > 你需要切换到tag v0.0.1的版本，然后加入#issue 37的修改。 切换tag的命令：git checkout -b local_tag_0.0.1 v0.0.1
> 
> 大佬，我为什么无法切换 ![image](https://user-images.githubusercontent.com/54066145/146646571-262778ad-d992-4b9b-91ca-c6e5dd1d6ce5.png) 纯小白，什么都不懂，还为此下了个 ![image](https://user-images.githubusercontent.com/54066145/146646587-841922ac-33fc-45e4-9439-2f92c7179ba4.png)

你下载的那个是git的GUI图形操作工具，也是可以的，可以使用Git Bash来输入切换tag的命令。
你第一个框中的错误是找不到git.exe，原因是windows的命令行窗口需要添加环境变量，把git.exe所在的目录添进去，你应该是没有添，所以就报错了，可以参考百度的这个链接尝试做一下：https://www.cnblogs.com/qingmuchuanqi48/p/12052289.html

**Comment by 1Wizzy** [comment]
> 

非常感谢😊

**Comment by 1Wizzy** [comment]
> > 你需要切换到tag v0.0.1的版本，然后加入#issue 37的修改。 切换tag的命令：git checkout -b local_tag_0.0.1 v0.0.1
> 
> 切换到tag v0.0.1的版本对我是有效的。切换到tag并不容易，除了大佬提出的方法之外，我提出个笨拙些的解决方法：之间在code的页面找到tag，点击进之后下载就行，解压后进入这个文件进行相关的操作即可。

这个方法也不错，谢谢了😊
