### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by pangranaaa** [babysor/MockingBird#263]
usage: demo_toolbox.py [-h] [-d DATASETS_ROOT] [-e ENC_MODELS_DIR] [-s SYN_MODELS_DIR] [-v VOC_MODELS_DIR] [--cpu] [--seed SEED] [--no_mp3_support]
demo_toolbox.py: error: argument -d/--datasets_root: expected one argument

**Comment by babysor** [comment]
看的教程太老了，这里需要输入一个音频目录，用于样本音频载入，可以是任意一个空的
