### ISSUE TITLE
如何平稳的停止训练，手动中断训练后再次训练报错RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by luobingit** [babysor/MockingBird#267]
![image](https://user-images.githubusercontent.com/68454150/145802200-eca7476e-6704-4123-a2b4-785ce2d2c3ea.png)

这个报错是因为恶意中断训练模型导致模型损坏了吗？各位大佬有解吗？训练了好久然后废了

**Comment by luobingit** [comment]
ctrl + fn + pause

**Comment by chxx** [comment]
删除之前训练生成的pt，重新训练。怀疑是训练过程升级了一些依赖，模型不兼容导致。
