### ISSUE TITLE
训练模型时显存爆了

### ISSUE THREAD

**Issue by cronfox** [babysor/MockingBird#27]
`Variable._execution_engine.run_backward(RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 4.00 GiB totalcapacity; 2.68 GiB already allocated; 0 bytes free; 2.85 GiB reserved in total by PyTorch)`

能不能提供一个调batch_size的参数? 我目前用的显卡显存只有4G(GTX1050Ti)，默认参数正常训练时经常爆掉显存....

**Comment by wangkewk** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/664找找这个，你可以

**Comment by wangkewk** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/664


你可以找找这个

**Comment by wangkewk** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/700

**Comment by babysor** [comment]
嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.

**Comment by cronfox** [comment]
> 嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.

我试着通过修改部分文件将batch_size调到6，跑的很稳定。

**Comment by XiuChen-Liu** [comment]
> > 嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.
> 
> 我试着通过修改部分文件将batch_size调到6，跑的很稳定。

可以請問是修改什麼文件呢，我看了上面的引用，研究了半天看不大懂。

**Comment by cronfox** [comment]
> > > 嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.
> > 
> > 
> > 我试着通过修改部分文件将batch_size调到6，跑的很稳定。
> 
> 可以請問是修改什麼文件呢，我看了上面的引用，研究了半天看不大懂。

需要修改 [./synthesizer/hparams.py ](https://github.com/babysor/Realtime-Voice-Clone-Chinese/blob/9f30ca8e928ae919bdcbb60ba969e8102d1bbbdf/synthesizer/hparams.py#L52) 这一部分

**Comment by XiuChen-Liu** [comment]
好的我試試，謝謝!

**Comment by XiuChen-Liu** [comment]
> 嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.

訓練vocoder時也遇到 `RuntimeError: CUDA out of memory. Tried to allocate 74.00 MiB (GPU 0; 6.00 GiB total capacity; 3.56 GiB already allocated; 14.88 MiB free; 3.74 GiB reserved 
in total by PyTorch)` 同樣更改batch size來解決嗎

**Comment by tisttsf** [comment]
> > 嗯嗯,如上所示,我之前用940MX, batch size在2是可以跑的,你这个话可以试下4.
> 
> 請問訓練 vocoder 時也遇到 `RuntimeError: CUDA out of memory. Tried to allocate 74.00 MiB (GPU 0; 6.00 GiB total capacity; 3.56 GiB already allocated; 14.88 MiB free; 3.74 GiB reserved in total by PyTorch)` 同樣更改batch size來解決嗎


我把下面代码的 12 to 2 暂时不报错了
文件:yourmainfolder\synthesizer\hparams.py中的
```
        tts_schedule = [(2,  1e-3,  20_000,  2),   # Progressive training schedule
                        (2,  5e-4,  40_000,  2),   # (r, lr, step, batch_size)
                        (2,  2e-4,  80_000,  2),   #
                        (2,  1e-4, 160_000,  2),   # r = reduction factor (# of mel frames
                        (2,  3e-5, 320_000,  2),   #     synthesized for each decoder iteration)
                        (2,  1e-5, 640_000,  2)]
```

**Comment by XiuChen-Liu** [comment]
好勒，謝謝你

**Comment by babysor** [comment]
已经update到 Readme
