### ISSUE TITLE
合成时人声电音爆裂问题

### ISSUE THREAD

**Issue by a1140314577** [babysor/MockingBird#270]
效果不是很好，有时人声还会突然中断变成电子音
![cfe7e4f1ab0762cf6bace8f690f3d20](https://user-images.githubusercontent.com/96097942/145982460-6e054aa4-ccf4-4414-a9cf-67fecd536394.png)

**Comment by babysor** [comment]
输入音频质量太差，参考 https://zhuanlan.zhihu.com/p/425692267

**Comment by a1140314577** [comment]
更换了音频和合成器好像好了一点，有个疑问是我只能用g_hifigan的vocoder，但会带有电音，一用这个vocoder就报错，请问怎么解决呢
![1639619848](https://user-images.githubusercontent.com/96097942/146293957-deeaab1a-cdee-46e6-a575-29cb5046c55a.png)

![ad0d41b2a8eac024f6e9c484e44be96](https://user-images.githubusercontent.com/96097942/146293313-2f2050fb-6089-4f96-b419-ae03f2833f3c.png)
