### ISSUE TITLE
安装 ffmpeg时的requirements.txt在哪里？

### ISSUE THREAD

**Issue by jasonyun** [babysor/MockingBird#272]
安装 ffmpeg。 1）下载 选择点击打开链接Windows对应的版本下载 2）解压 ffmpeg-xxxx.zip 文件到指定目录； 3）将解压后的文件目录中 bin 目录（包含 ffmpeg.exe ）添加进 path 环境变量中； 4）进入 cmd，输入 ffmpeg -version，可验证当前系统是否识别 ffmpeg 以及查看 ffmpeg 的版本

运行pip install -r requirements.txt 来安装剩余的必要包。

**Comment by babysor** [comment]
所以这里不是个问题吗？

**Comment by MagnoliaFly** [comment]
一开始我也有这个疑问其实，然后你其实可以跟着视频教学做，它的requirements.txt其实是这个MokingBird的代码包，里面有一个requirements.txt，下载打开进入目录跑就可以了
