### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by wangkewk** [babysor/MockingBird#28]
![image](https://user-images.githubusercontent.com/31000405/130337837-6c317318-2018-45bd-b8d9-e144b220b12a.png)
训练一半后出现这个，谁能解决help

**Comment by babysor** [comment]
一般出现这种问题都是cuda版本问题..你用了lts版本吗

**Comment by wangkewk** [comment]
> 一般出现这种问题都是cuda版本的问题..你用了lts版本吗

我用的10.2版本啊      Its 是什么

**Comment by babysor** [comment]
cuda版本更新后是不是就修复了？
