### ISSUE TITLE
能不通过gui 而通过py程序直接调用吗

### ISSUE THREAD

**Issue by Diaosi1111** [babysor/MockingBird#280]
有没有暴露出来的api，可以直接让其他程序调用

**Comment by babysor** [comment]
可以看看web部分，比较粗糙，欢迎改进。

**Comment by MagnoliaFly** [comment]
> 可以看看web部分，比较粗糙，欢迎改进。

@babysor 
抱歉又打扰您，我通过GUI版本进行合成的声音挺不错的，然后我尝试web版本，合成出来的全是恐怖的奇怪音效。。。GUI的操作是对照B站教程操作的，web版本我上传了相同的音源，然后我也看了后台确定使用的是同一个模型，实际上也只保存了一个模型，结果输出的却完全不同，这是什么原因呢？我应该怎么做呢？

**Comment by luobingit** [comment]
> > 可以看看web部分，比较粗糙，欢迎改进。
> 
> @babysor 抱歉又打扰您，我通过GUI版本进行合成的声音挺不错的，然后我尝试web版本，合成出来的全是恐怖的奇怪音效。。。GUI的操作是对照B站教程操作的，web版本我上传了相同的音源，然后我也看了后台确定使用的是同一个模型，实际上也只保存了一个模型，结果输出的却完全不同，这是什么原因呢？我应该怎么做呢？

同问

**Comment by babysor** [comment]
> > 可以看看web部分，比较粗糙，欢迎改进。
> 
> @babysor 抱歉又打扰您，我通过GUI版本进行合成的声音挺不错的，然后我尝试web版本，合成出来的全是恐怖的奇怪音效。。。GUI的操作是对照B站教程操作的，web版本我上传了相同的音源，然后我也看了后台确定使用的是同一个模型，实际上也只保存了一个模型，结果输出的却完全不同，这是什么原因呢？我应该怎么做呢？

之前这个web project是和网友一起倒腾的， 我估计是音频传到后台的预处理（采样降噪一块）有问题，可以用调试工具一步步存下来看音频。
@luobingit
