### ISSUE TITLE
如何基于ceshi.pt继续训练呢？

### ISSUE THREAD

**Issue by joshua54321** [babysor/MockingBird#281]
1.目前从测试情况来看，测试了好几位大佬提供的模型，发现目前效果最好的还是作者提供的ceshi.pt，不知道作者是基于什么参数训练的，很想依照参数训练复现一下？
2.如何在ceshi.pt的基础上进行继续训练呢?将ceshi.pt重命名为mandarin.pt进行继续训练时，初始化报如下错误：
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group，参数未做改动，batch_size用默认的12

**Comment by luobingit** [comment]
我是拉取最新的代码在 #245 的基础上继续训练的，作者分享的75k模型也是可以的

**Comment by joshua54321** [comment]
> 我是拉取最新的代码在 #245 的基础上继续训练的，作者分享的75k模型也是可以的

好的，感谢感谢！
