### ISSUE TITLE
利用脚本测试的时候出现shape不匹配问题

### ISSUE THREAD

**Issue by DanMerry** [babysor/MockingBird#282]
Traceback (most recent call last):
  File "F:/MockingBird-main/MockingBird-main/test.py", line 61, in <module>
    specs = synthesizer.synthesize_spectrograms(texts, embeds)
  File "F:\MockingBird-main\MockingBird-main\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "F:\MockingBird-main\MockingBird-main\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath, self.device)
  File "F:\MockingBird-main\MockingBird-main\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "E:\Conda\condaFile\envs\MockingBird-main\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).

**Comment by DanMerry** [comment]
望作者以及各路大神路过的时候瞅一瞅，用的模型是my_run8_25k.pt，问题应该出在synthesizer上了

**Comment by DanMerry** [comment]
parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument("-e", "--enc_model_fpath", type=Path,
                            default="./encoder/saved_models/pretrained.pt",
                            help="Path to a saved encoder")
    parser.add_argument("-s", "--syn_model_fpath", type=Path,
                        # default="synthesizer/saved_models/pretrained/pretrained.pt",
                        default="./synthesizer/saved_models/my_run8_25k.pt",
                        help="Path to a saved synthesizer")
    parser.add_argument("-v", "--voc_model_fpath", type=Path,
                        # default="vocoder/saved_models/pretrained/pretrained.pt",
                        default="./vocoder/saved_models/pretrained/pretrained_mander.pt",
                        help="Path to a saved vocoder")
    args = parser.parse_args()
    print_args(args, parser)

    check_model_paths(encoder_path=args.enc_model_fpath,
                      synthesizer_path=args.syn_model_fpath,
                      vocoder_path=args.voc_model_fpath)

    encoder.load_model(args.enc_model_fpath)
    synthesizer = Synthesizer(args.syn_model_fpath)
    vocoder.load_model(args.voc_model_fpath)

    # ***************************************** informal *****************************************
    in_fpath = r'C:\Users\think\Desktop\temp_SE\test\SSB0139\SSB01390019.wav'
    preprocessed_wav = encoder.preprocess_wav(in_fpath)
    # - If the wav is already loaded:
    original_wav, sampling_rate = librosa.load(str(in_fpath))
    preprocessed_wav = encoder.preprocess_wav(original_wav, sampling_rate)
    print("Loaded file succesfully")

    embed = encoder.embed_utterance(preprocessed_wav)
    print("Created the embedding")

    text = r'宁波大学'

    texts = [text]
    embeds = [embed]

    specs = synthesizer.synthesize_spectrograms(texts, embeds)
    spec = specs[0]
    print("Created the mel spectrogram")

    print("Synthesizing the waveform:")
    generated_wav = vocoder.infer_waveform(spec)
    generated_wav = np.pad(generated_wav, (0, synthesizer.sample_rate), mode="constant")
    generated_wav = encoder.preprocess_wav(generated_wav)
    sf.write('test.wav', generated_wav.astype(np.float32), synthesizer.sample_rate)

**Comment by DanMerry** [comment]
@babysor 作者您好 能否帮忙解决一下 hparams.py的最后一个参数已经是True

**Comment by MagnoliaFly** [comment]
#245 
用这个，这大概是唯一一个新版可用的模型了

**Comment by MagnoliaFly** [comment]
我试了一下，包括那个readme的第一个75k也是可以用的

**Comment by DanMerry** [comment]
已经成功运行批处理脚本，非常感谢#245很好用
