### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Tacotron:         size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]). 

### ISSUE THREAD

**Issue by 3maoyap** [babysor/MockingBird#284]

**Comment by huzhugongsheng** [comment]
你可以试试将synthesizer\utils文件夹里的symbols文件用记事本打开,将_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? '注释掉（即在前面加#），将_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ' 取消注释（即去掉前面的#）。

**Comment by MagnoliaFly** [comment]
#245 
用这个，这大概是唯一新版可用的了，我尝试了issue里出现过的各种模型，就这个跑起来了

**Comment by MagnoliaFly** [comment]
我试了一下，包括那个readme的第一个75k也是可以用的
