### ISSUE TITLE
关于照着视频教程做的中间出现的各种错误

### ISSUE THREAD

**Issue by MagnoliaFly** [babysor/MockingBird#286]
我除了使用了anaconda以外，完全按照视频教程一步一步做的，然后后面启动却出现
Warning: you did not pass a root directory for datasets as argument.
所以一个datasets的文件夹是必须的，那我就按教程新建并传入simple文件夹，可是
Warning: you do not have any of the recognized datasets in samples.
那就是因为没东西呗，那我想肯定是要把rty4_56k的pt文件或wav文件，放在里面，可是放在里面仍旧是一样的错误
然后我看了社区模型，全是覆盖已有的一些文件夹，也就是说，模型不会存在simple文件夹里
那我想可能是因为那是用来训练模型用的声音才放里面，先忽略掉，但是不行，直接用的话
size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
爆这个错误，我不知道是怎么一回事，有没有好哥哥可以帮帮我呢

**Comment by MagnoliaFly** [comment]
我就是在想会不会教程里少了什么步骤或者怎么样。。。

**Comment by DanMerry** [comment]
我也遇到这样的问题， 你或许可以@一下作者

**Comment by MagnoliaFly** [comment]
@babysor 下面评论区也有别的人出现了这个问题，或许是一个需要修复的BUG，有空了希望可以帮帮忙，谢谢哥哥！

**Comment by babysor** [comment]
虽然出现了warning但【一个datasets的文件夹】不是必须的，不传的情况下，输入或者选择你的音频文件就可以了。
后面的 size mismatch是因为使用的模型与代码版本不符，建议看下readme中每个模型的详细描述，

**Comment by MagnoliaFly** [comment]
> 虽然出现了warning但【一个datasets的文件夹】不是必须的，不传的情况下，输入或者选择你的音频文件就可以了。 后面的 size mismatch是因为使用的模型与代码版本不符，建议看下readme中每个模型的详细描述，

好的，谢谢了，是我没仔细搜索别的issue
写给后来的人：前面有Issue已经反馈了一样的问题，并且也有比较详细的说明，还有一些我没有尝试的方法，并且babysor说之后会有兼容性提高的版本，希望兼容性提高的更新能早一点出现吧，readme我并没有看到模型的详细描述，里面没有有关于是否新版可用的部分，但是wiki里仔细看确实说了这个问题，另外其中一个issue有人提供了新版可用的模型，大家可以去试试看，相关的问题继续在那个issue去交流吧。因为我不知道issue传送门是怎么编辑的，这里就不多说了，大家去找吧QWQ
