### ISSUE TITLE
python demo_toolbox.py -d D:\DATA\aidatatang_200zh\corpus\test报错

### ISSUE THREAD

**Issue by wang123pc** [babysor/MockingBird#293]
Warning: you do not have any of the recognized datasets in D:\DATA\aidatatang_200zh\corpus\test.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/dev
        aidatatang_200zh/corpus/test
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
为什么报错说没有可识别的数据，里面的所有文件我都解压了，求求了，还有那个<dataset_root>是不是要精确到数据集的具体文件，我用的是aidatatang_200zh的数据集

**Comment by muconai** [comment]
python demo_toolbox.py -d D:\DATA  这条你试试

**Comment by wang123pc** [comment]
> python demo_toolbox.py -d D:\DATA 这条你试试

已解决，谢谢啦
