### ISSUE TITLE
LOSS=0.269 看着没有收敛的迹象啊！

### ISSUE THREAD

**Issue by muconai** [babysor/MockingBird#294]
[](url
![step-2500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/73742351/147382038-3bf3900f-962f-4b0b-ad30-839805af859e.png)
![attention_step_2500_sample_1](https://user-images.githubusercontent.com/73742351/147382041-23d4c5fc-0367-42e3-a281-328517dcccf1.png)
)

**Comment by muconai** [comment]
4.5k
![step-4500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/73742351/147382435-854ffc7c-a692-4064-b869-32a9d3a5ea94.png)
![attention_step_4500_sample_1](https://user-images.githubusercontent.com/73742351/147382438-1616cf63-61bc-42db-9f51-386578dd60a7.png)

**Comment by babysor** [comment]
看上去还在正常的收敛过程中，如果到15k 还没有的话就重新练
