### ISSUE TITLE
有人用MacBook跑过嘛0.0

### ISSUE THREAD

**Issue by Noctise** [babysor/MockingBird#301]
<img width="1667" alt="截屏2021-12-29 下午11 19 16" src="https://user-images.githubusercontent.com/20741235/147676931-143df97f-223d-446f-8531-fc48d24b8844.png">

**Comment by absc** [comment]
我能问一下你的opencv-python是什么版本？
我运行后报了qt.qpa.plugin：Could not find the Qt platform plugin "cocoa" in ""的错误

**Comment by zhangna111** [comment]
我用macbook pro跟你是同样的问题，除了报错以外，录音不能回放，显示不了录音的图片，合成效果也不如windows好（用win10 同一代码模型做了对比）

**Comment by babysor** [comment]
错误请看 #37
