### ISSUE TITLE
mandarin_200k 如何load

### ISSUE THREAD

**Issue by aixuedegege** [babysor/MockingBird#307]
使用这个模型汇报维度不匹配 请问如何使用

**Comment by babysor** [comment]
版本问题，请细看readme或issue

**Comment by aixuedegege** [comment]
问题在这里看到了 https://github.com/babysor/MockingBird/issues/37 。能够跑通，谢了，但是还有个问题，_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '这个是用来找embedding的，这个字符集，针对不同模型是不是要单独维护一套？ 或者有什么相关论文推荐么？ 对语音合成是新手，请多指教

**Comment by babysor** [comment]
> 问题在这里看到了 #37 。能够跑通，谢了，但是还有个问题，_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!'(),-.:;? '这个是用来找embedding的，这个字符集，针对不同模型是不是要单独维护一套？ 或者有什么相关论文推荐么？ 对语音合成是新手，请多指教

不需要，只是历史遗留问题，ceshi用的是一个旧的
