### ISSUE TITLE
声码器训练问题

### ISSUE THREAD

**Issue by ZoeyCheung** [babysor/MockingBird#308]
1 默认wavernn，不加参数会报错，通过修改代码已解决。
![微信图片_20220102192404](https://user-images.githubusercontent.com/20389492/147874214-712d9395-5724-459c-aedc-f6d1f1eb4366.jpg)
2 训练hifigan声码器，同一标识再次训练时，不能继续训练，会重头开始。

**Comment by babysor** [comment]
> 1 默认wavernn，不加参数会报错，通过修改代码已解决。 ![微信图片_20220102192404](https://user-images.githubusercontent.com/20389492/147874214-712d9395-5724-459c-aedc-f6d1f1eb4366.jpg) 2 训练hifigan声码器，同一标识再次训练时，不能继续训练，会重头开始。

第二点应该不会了吧？ @hertz-pj

**Comment by ZoeyCheung** [comment]
修改1之后，wavernn是可以在第一个基础上继续训练的。但是wavernn效果测试不如hifigan的效果好，但是hifigan不能接着训练。

**Comment by hertz-pj** [comment]
> 修改1之后，wavernn是可以在第一个基础上继续训练的。但是wavernn效果测试不如hifigan的效果好，但是hifigan不能接着训练。

这个我有空改一下，可能之前没注意这个中断训练的逻辑~ @babysor

**Comment by GITHUBGUY12357999** [comment]
hi

**Comment by AyahaShirane** [comment]
hifigan还是不能接着训练，我翻看了代码好像是.\vocoder\hifigan\train.py第55行和56行调用的scan_checkpoint()函数有问题，那个函数根本没法正确的找到模型
函数原型如下：
`def scan_checkpoint(cp_dir, prefix):
    pattern = os.path.join(cp_dir, prefix + '????????')
    cp_list = glob.glob(pattern)
    if len(cp_list) == 0:
        return None
    return sorted(cp_list)[-1]`

**Comment by hertz-pj** [comment]
> hifigan还是不能接着训练，我翻看了代码好像是.\vocoder\hifigan\train.py第55行和56行调用的那个scan_checkpoint()函数有问题，那个函数根本没法正确的找到模型
> 
> 把vocoder\hifigan\utils.py:53改成` pattern = os.path.join(cp_dir, prefix + '*')`就能加载了，但后果是cuda直接炸显存，batch_size = 4 了都炸

sorry，这块一直没空处理，周末找时间处理下。另外显存炸了跟这个不确定是否有关系，你从头训练hifigan是否也会炸显存呢？

**Comment by AyahaShirane** [comment]
直接运行不会炸，而且根据我的进一步观察，输出了成功加载的提示，但其实还是没能加载进度，问题应该不只是这个

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hertz-pj** [comment]
@AyahaShirane #389 已解决。另外我这边没有发现炸显存的问题，batch_size 16的占用显存大概是8g

**Comment by AyahaShirane** [comment]
@hertz-pj 感激不尽
