### ISSUE TITLE
使用预置模型，Toobox输出的是电音

### ISSUE THREAD

**Issue by dewjiguang** [babysor/MockingBird#311]
您好，我是按照友好版教程一步一步做的https://github.com/babysor/MockingBird/wiki/Quick-Start-(Newbie)
且没有训练自己的模型，直接用给的ceshi模型，经多次测试，最后的ToolBox输出总是为杂音，如下图。
![image](https://user-images.githubusercontent.com/41632105/147910519-5eeac4f2-c9e1-4fc0-aba9-3b33387fe1e3.png)
请问是哪里出了问题呢。
另：请问该使用哪个分支，我main分支和webtoolbox分支都试过了。

**Comment by dewjiguang** [comment]
补充：查阅Issue后发现之前已经有人出过这样的问题了，按照#37中方法修改，并调整git至10.20号（如下图），再次尝试，仍然是杂音，求教该怎办
![1641201215(1)](https://user-images.githubusercontent.com/41632105/147914936-986443de-ca06-4d4b-a62a-af558f8e8d77.jpg)

**Comment by dewjiguang** [comment]
已经解决了，切换分支用的是Hard模式，忘记再改一次了.....

**Comment by tianming937** [comment]
同样问题，还未解决，请问大佬，“切换分支用的是Hard模式”是什么意思？我应该怎么操作

**Comment by MaoSheng-super** [comment]
> 已经解决了，切换分支用的是Hard模式，忘记再改一次了.....

同问：“切换分支用的是Hard模式”是什么意思？求解答
