### ISSUE TITLE
成功运行过工具箱，后来因为自己训练了一次模型就再也打不开工具箱了是什么情况？

### ISSUE THREAD

**Issue by puddinggu** [babysor/MockingBird#319]
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/dev
        aidatatang_200zh/corpus/test
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "E:\电子播发器\MockingBird-main\demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "E:\电子播发器\MockingBird-main\toolbox\__init__.py", line 76, in __init__
    self.setup_events()
  File "E:\电子播发器\MockingBird-main\toolbox\__init__.py", line 113, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "E:\电子播发器\MockingBird-main\toolbox\ui.py", line 149, in setup_audio_devices
    for device in sd.query_devices():
  File "E:\python\Lib\site-packages\sounddevice.py", line 559, in query_devices
    return DeviceList(query_devices(i)
  File "E:\python\Lib\site-packages\sounddevice.py", line 559, in <genexpr>
    return DeviceList(query_devices(i)
  File "E:\python\Lib\site-packages\sounddevice.py", line 573, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

报错是这样。
本来都可以正常打开工具箱的。 web还是可以启动，也可以合成声音。
就是工具箱打不开，这个怎么解决阿。

**Comment by puddinggu** [comment]
补充一下，工具箱会很快的闪出来一下，然后又关闭。

**Comment by puddinggu** [comment]
草。。。很怪。之前都开的好好的，根本没想过是这个问题。
有同样问题的朋友可以看一下这个
https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF

**Comment by freddy123098** [comment]
Should I check this link?
