### ISSUE TITLE
小白求助，in loading state_dict for {}:\n\t{}'.format&in loading state_dict for Tacotron

### ISSUE THREAD

**Issue by Nolan-HK** [babysor/MockingBird#320]
代码拉取最新，按照#209里的改不行，#37也试过了![problem(1).PNG](https://user-images.githubusercontent.com/62446114/148334867-ffcb49de-6f49-4c93-85bd-2a7ee5e027f8.PNG)

**Comment by Kristen-PRC** [comment]
![image](https://user-images.githubusercontent.com/90098227/148336282-ed5d88cb-9e1d-4161-ad77-bc78a3329927.png)
我也是按照#209试过了，也不好用，同求原因

**Comment by zqfzqf** [comment]
可以试一下：文字输入框里的标点只保留逗号“，”删掉其他符号，包括默认带的"！"

**Comment by Nolan-HK** [comment]
> 可以试一下：文字输入框里的标点只保留逗号“，”删掉其他符号，包括默认带的"！"

我没打开合成工具箱，现在只是在别人模型上继续训练
