### ISSUE TITLE
![image](https://user-images.githubusercontent.com/90098227/148337437-7e860c07-e763-42b0-9ecd-2a4e975b73d8.png)

### ISSUE THREAD

**Issue by Kristen-PRC** [babysor/MockingBird#321]
![image](https://user-images.githubusercontent.com/90098227/148337437-7e860c07-e763-42b0-9ecd-2a4e975b73d8.png)
求教，安装模型后运行出现Tacotron报错，已参考#37、#209均无法解决，烦请各位帮助，谢谢

_Originally posted by @Kristen-PRC in https://github.com/babysor/MockingBird/issues/245#issuecomment-1006314547_

**Comment by ZJ-CAI** [comment]
会不会是你录制的语音或者上传的音频时间太长？语音时间如果保持在10秒之内的话，那估计就是模型的问题了，换个模型试试。

**Comment by babysor** [comment]
按#209 修改没有成功吧
