### ISSUE TITLE
运行toolbox后进行录音，随后卡死

### ISSUE THREAD

**Issue by Starkxim** [babysor/MockingBird#324]
运行toolbox，使用https://github.com/babysor/MockingBird/wiki/Quick-Start-(Newbie) 中提到的模型，录音后程序卡死，
![image](https://user-images.githubusercontent.com/73403611/148560358-ca26640d-3e2b-427b-9304-b4df3c14aa86.png)
尝试选择不同的vocoder，程序也卡死
![image](https://user-images.githubusercontent.com/73403611/148560083-a48f4940-bdfc-46a5-a616-b180ffc0bf61.png)

**Comment by EnderOcelot** [comment]
重启toolbox后呢

**Comment by Starkxim** [comment]
> 

每次启动toolbox，只要选择vocoder或者进行录音，都会卡死

**Comment by babysor** [comment]
后台进程看看是否有冲突，因为调用了系统的ffmpeg，所以有可能是有兼容问题

**Comment by CherryCherries** [comment]
我也有相同的问题

**Comment by Starkxim** [comment]
> torch版本更新導致不相容 把環境的torch解除安裝 "conda uninstall pytorch" "pip uninstall torch" 安裝這個 "pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html"

非常感谢，这个问题解决了。现在能够正常运行，就是生成的声音全部是噪音，还在自己排查中。
