### ISSUE TITLE
一直出现是噪音，ValueError: Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by jiejiekii** [babysor/MockingBird#326]
按照教程打开demo_toolbox一切正常

打开窗口后，无论是加载音频文件（mp3）还是通过toolbox自己录制都会出现报错

ValueError: Axis limits cannot be NaN or Inf

所以，最后输出的音频全都是噪音。

请问大佬，这个问题要如何解决。

**Comment by babysor** [comment]
尝试过把软件窗口拉大一点吗

**Comment by absc** [comment]
我也是，在macbook上，有解决么

**Comment by YoTro** [comment]
> 
ValueError: Axis limits cannot be NaN or Inf
把软件窗口拉大之后可以解决这个问题
