### ISSUE TITLE
是否能让生成出来的语音语速变慢

### ISSUE THREAD

**Issue by Snowflake-Pink** [babysor/MockingBird#33]
用了readme网友的数据集，感觉语速过快有点不自然

**Comment by PeijiYang** [comment]
> 用了readme网友的数据集，感觉语速过快有点不自然

音频降速不变调可以参考pyrubberband，https://github.com/bmcfee/pyrubberband

**Comment by babysor** [comment]
如果你这边用aidatatang的数据慢慢跑，后面会比较自然
