### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by cancan23333** [babysor/MockingBird#330]
PS Q:\MockingBird-main> python synthesizer_train.py mandarin Q:\数据集\SV2TTS\synthesizer\
Arguments:
    run_id:          mandarin
    syn_dir:         Q:\数据集\SV2TTS\synthesizer\
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    log_every:       200
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\mandarin\mandarin.pt
Loading training data from: Q:\数据集\SV2TTS\synthesizer\train.txt
Using model: Tacotron
Using device: cuda

Initialising Tacotron Model...

Trainable Parameters: 32.869M

Loading weights at synthesizer\saved_models\mandarin\mandarin.pt
Tacotron weights loaded from step 0
Using inputs from:
        Q:\数据集\SV2TTS\synthesizer\train.txt
        Q:\数据集\SV2TTS\synthesizer\mels
        Q:\数据集\SV2TTS\synthesizer\embeds
Found 62 samples
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   10k Steps    |     8      |     0.001     |        2         |
+----------------+------------+---------------+------------------+

C:\Users\canca\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
{| Epoch: 1/1250 (8/8) | Loss: 10.02 | 0.60 steps/s | Step: 0k | }
{| Epoch: 2/1250 (8/8) | Loss: 6.688 | 0.64 steps/s | Step: 0k | }
{| Epoch: 3/1250 (8/8) | Loss: 5.300 | 0.66 steps/s | Step: 0k | }
{| Epoch: 4/1250 (8/8) | Loss: 4.547 | 0.67 steps/s | Step: 0k | }
{| Epoch: 5/1250 (8/8) | Loss: 4.038 | 0.67 steps/s | Step: 0k | }
{| Epoch: 6/1250 (8/8) | Loss: 3.700 | 0.68 steps/s | Step: 0k | }
{| Epoch: 7/1250 (8/8) | Loss: 3.432 | 0.68 steps/s | Step: 0k | }
{| Epoch: 8/1250 (8/8) | Loss: 3.218 | 0.68 steps/s | Step: 0k | }
{| Epoch: 9/1250 (8/8) | Loss: 3.039 | 0.68 steps/s | Step: 0k | }
{| Epoch: 10/1250 (8/8) | Loss: 2.887 | 0.68 steps/s | Step: 0k | }
{| Epoch: 11/1250 (8/8) | Loss: 2.759 | 0.68 steps/s | Step: 0k | }
{| Epoch: 12/1250 (8/8) | Loss: 2.645 | 0.68 steps/s | Step: 0k | }
{| Epoch: 13/1250 (3/8) | Loss: 2.610 | 0.68 steps/s | Step: 0k | }grad_norm was NaN!
{| Epoch: 13/1250 (4/8) | Loss: 2.596 | 0.68 steps/s | Step: 0k | }C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:115: block: [7,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "Q:\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "Q:\MockingBird-main\synthesizer\train.py", line 201, in train
    loss.backward()
  File "C:\Users\canca\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\canca\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by rereset** [comment]
Hi, I also met this problem when training synthesizer, how did you solve it? Looking forward to your reply! 🥺
