### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Snowfly-Guo** [babysor/MockingBird#331]
Traceback (most recent call last):
  File "demo_toolbox.py", line 1, in <module>
    from pathlib import Path
ImportError: No module named pathlib

**Comment by iOS-Kel** [comment]
兄弟解决这个问题了吗？我也遇到了

**Comment by babysor** [comment]
这个依赖就非常基础了，你是不是没运行pip install成功？？

**Comment by Snowfly-Guo** [comment]
> 这个依赖就非常基础了，你是不是没运行pip install成功？？

pip运行成功了，我是一段时间没用这个然后就这样了

**Comment by Snowfly-Guo** [comment]
> 兄弟解决这个问题了吗？我也遇到了

我也不知道怎么解决的不好意思哈
