### ISSUE TITLE
小白求助，前面所有步骤ok，运行demo_toolbox.py时Error: Model files not found.

### ISSUE THREAD

**Issue by tianming937** [babysor/MockingBird#338]
(pytorch) C:\Users\666>python D:\MockingBird-main\demo_toolbox.py
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

********************************************************************************
Error: Model files not found. Please download the models
********************************************************************************

试了好多方法都不行。各位大佬，这种问题应该怎么操作？
之前有一位仁兄，同样的报错，通过“在项目根目录下运行demo_toolbox.py文件”解决了该问题，可是本人小白，不知道应该怎么具体操作，请各位大佬指导详细一点，谢谢

**Comment by HuaHuaOfficial** [comment]
先输入一次cd D:\MockingBird-main

**Comment by tianming937** [comment]
Anaconda Prompt只能在根目录下进行切换盘符
要使用cd ..切换到上级文件夹
然后cd D:\MockingBird-main
最后python demo_toolbox.py

完美运行

**Comment by tianming937** [comment]
> 先输入一次cd D:\MockingBird-main
感谢大佬，看了你的指导，已经跑起来了

**Comment by nickxsc** [comment]
以后也可以直接 cd /d D:\MockingBird-main 连带根目录一起切换
