### ISSUE TITLE
Linux环境下 运行Python web.py后点击上传合成按钮报错ValueError: operands could not be broadcast together with shapes (2200,) (4000,) (2200,)

### ISSUE THREAD

**Issue by ONLYOURMIRACLE** [babysor/MockingBird#343]
![QQ截图20220115170332](https://user-images.githubusercontent.com/74305035/149616359-c1e3344a-21f5-4436-b42a-730b25963a98.png)
请问如何解决这个问题？

**Comment by babysor** [comment]
代码版本是最新main的吗？

**Comment by showmaker-hub** [comment]
> 代码版本是最新main的吗？

我也是这样的错误，代码是今天git拉取的，除了合成器是别人训练好的

**Comment by showmaker-hub** [comment]
![QQ截图20220116095430](https://user-images.githubusercontent.com/84022302/149644305-21df6ea9-b501-402d-988c-3bab2456fa85.png)
我跟你错误基本上一样 #

**Comment by ONLYOURMIRACLE** [comment]
代码版本是最新main！
 我或许已经找到了问题所在，可能是模型兼容性问题，详情请查看这篇回答：https://github.com/babysor/MockingBird/issues/37
