### ISSUE TITLE
Record报错

### ISSUE THREAD

**Issue by Se7entny** [babysor/MockingBird#357]
Archlinux系统用Docker使用archlinux镜像，(主要是依赖太多了，因此想用docker，防止运行失败产生过多无用依赖，真希望可以出一个官方Dockerfile)，按照快速开始(友好版)教程运行后，在点击Record录制的时候，终端报错Error querying device -1，并且无法停止，只能关闭程序

**Comment by babysor** [comment]
音频播放设备没有找到的问题，考虑搞个虚拟的

**Comment by Se7entny** [comment]
还是点Record的时候报错
Error opening InputStream: Invalid sample rate [PaErrorCode -9997]
请问这是什么原因，怎么才能解决

**Comment by babysor** [comment]
那就是音频输入设备未弄好，要搞下驱动
