### ISSUE TITLE
为啥我的训练目录下面plot是空的

### ISSUE THREAD

**Issue by ttkrpink** [babysor/MockingBird#359]
按B站上“克隆海子姐”的教程做的。
最后一步是将训练停止，用“pretrained-11-7-21_75k.pt”这个文件替换已经生成的pt文件，接着作者的模型继续训练。这里我有几个疑问。

1. 替换后的文件，随着训练的进行，文件大小不变，这个正常吗？

2. 训练开始以后，plots文件夹下面始终都是空的。现在是Epoch：3/3864。目前还是空的。

3. 之前没有替换pt文件时，plots文件夹也是空的，即使训练进行到 Epoch: 16/455 (7/22)。

谢谢指教！

**Comment by MybestFriendM** [comment]
500条会保存一次，会生成预览图
