### ISSUE TITLE
最后一步GUI打不开，没有界面

### ISSUE THREAD

**Issue by greedyMaeter** [babysor/MockingBird#366]
模型已经导入之后，但是在cmd运行demo [toolbox.py的时候没有GUI界面。]( @)
![3](https://user-images.githubusercontent.com/96109949/151954777-51c43d16-fb61-4e3a-b67c-678a662fc445.jpg)
这是怎么回事？

**Comment by Luyizhe** [comment]
同问，使用pycharm运行时候显示Process finished with exit code -1073740940 (0xC0000374)
