### ISSUE TITLE
loss只有0.14，但是注意力模型一直是一条直线

### ISSUE THREAD

**Issue by bingganhe123** [babysor/MockingBird#367]
21k，一直跑到27k也是一条直线，是不是要重头再来了>_<
![step-21000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/98812723/151955014-4e8e7e2a-7f62-4f8a-a5d8-caebc90f4f5e.png)
![attention_step_21000_sample_1](https://user-images.githubusercontent.com/98812723/151955044-e34b9d38-c082-4cf8-b4cf-b5a3e943e5c7.png)

**Comment by babysor** [comment]
很遗憾是的，如果没正确形成注意力模型，loss是没有意义的

**Comment by bingganhe123** [comment]
> 很遗憾是的，如果没正确形成注意力模型，loss是没有意义的

我重新跑了三个模型，都没有收敛的情况，请问是不是因为数据集的问题，数据集是我自己制作校对的，但是只有700条左右

**Comment by babysor** [comment]
是的，数据集的语音总和长度要在百小时级别才能有保障。你这种情况，要在别人练好的基础上继续跑你自己的数据

**Comment by 1239hy** [comment]
> 是的，数据集的语音总和长度要在百小时级别才能有保障。你这种情况，要在别人练好的基础上继续跑你自己的数据

请问大佬，要咋在别人训练好的基础上跑，我替换了别人的PT，就不能运行了。
这一步不知道具体操作，求教
saved_models、模型文件下，直接替换别人的70K，就运行不了训练了

**Comment by 1239hy** [comment]
> 是的，数据集的语音总和长度要在百小时级别才能有保障。 你这种情况，要在别人练好的基础上继续跑你自己的数据

大佬，想请教，我不能继续别人的模型训练，都说是模型和软件版本不匹配，这怎么解决？
诚心求教

> > 是的，数据集的语音总和长度要在百小时级别才能有保障。 你这种情况，要在别人练好的基础上继续跑你自己的数据
>

**Comment by babysor** [comment]
> > 是的，数据集的语音总和长度要在百小时级别才能有保障。 你这种情况，要在别人练好的基础上继续跑你自己的数据
> 
> 大佬，想请教，我不能继续别人的模型训练，都说是模型和软件版本不匹配，这怎么解决？ 诚心求教
> 
> > > 是的，数据集的语音总和长度要在百小时级别才能有保障。 你这种情况，要在别人练好的基础上继续跑你自己的数据

要根据模型，切换到对应的软件版本，学一下git
