### ISSUE TITLE
load() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by lhchpeng** [babysor/MockingBird#372]
导入音频文件出现load() takes 1 positional argument but 2 were given错误提示

**Comment by AyahaShirane** [comment]
我也遇到了这个问题

**Comment by Starkxim** [comment]
我在python pre.py <datasets_root> 这一步出现了该错误

**Comment by chenxij8** [comment]
> 把D:\Code\MockingBird-main\synthesizer.py 的146行改成 `wav = librosa.load(str(fpath), sr=hparams.sample_rate)[0]` 能解决一部分问题，但还会有新的bug
但我synthesizer.py文件为什么都没有

**Comment by Lynn-Lting** [comment]
同问，在录入语音时报错，之前都没有这种情况的，今天突然出现这样，有没有大牛指导一下是怎么回事，感谢
Traceback (most recent call last):
  File "E:\Downloads\MockingBird-main\toolbox\__init__.py", line 103, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "E:\Downloads\MockingBird-main\toolbox\__init__.py", line 170, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "E:\Downloads\MockingBird-main\synthesizer\inference.py", line 146, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
TypeError: load() takes 1 positional argument but 2 were given

**Comment by potatocnoiz** [comment]
同问 我也是导入音频报的错  之前还能正常用 今天重装了一下环境配置好了就出现了这个错误 不知道是缺了什么音频组件还是啥的

**Comment by chenxij8** [comment]
xdm，看pull questions第一条，已经修了bug了

**Comment by chenxij8** [comment]
https://github.com/babysor/MockingBird/pull/379

**Comment by babysor** [comment]
👍，高效的网友
