### ISSUE TITLE
TypeError: load() takes 1 positional argument but 2 were given报错怎么解决呢重装Anaconda也无用

### ISSUE THREAD

**Issue by Druid66** [babysor/MockingBird#377]
TypeError: load() takes 1 positional argument but 2 were given

**Comment by soulcookies** [comment]
找到了个临时的办法，把librosa库进行降级
在命令栏中输入 `pip install librosa==0.8.1` 的话我就不再出现这个错误了

**Comment by Druid66** [comment]
感谢大佬，通过pip install librosa==0.8.1实测有效
