### ISSUE TITLE
对声码器的展望

### ISSUE THREAD

**Issue by AyahaShirane** [babysor/MockingBird#383]
我发现合成器在达到一定数量的训练后，对质量影响更大的反而是声码器，hifigan能用更好的效果但始终有电噪音，现在有些新的项目采样lpcnet而非wavernn，据说是复杂度要远低于wavernn，但质量优于wavernn，可以达到类似hifigan的效果而不带电噪音，请问有考虑过引入lpcnet之类的新声码器的计划呢

**Comment by babysor** [comment]
> 我发现合成器在达到一定数量的训练后，对质量影响更大的反而是声码器，hifigan能用更好的效果但始终有电噪音，现在有些新的项目采样lpcnet而非wavernn，据说是复杂度要远低于wavernn，但质量优于wavernn，可以达到类似hifigan的效果而不带电噪音，请问有考虑过引入lpcnet之类的新声码器的计划呢

非常好的建议，你这边有推荐的paper或repo吗？

**Comment by babysor** [comment]
如果还有后续讨论请移步 #436
