### ISSUE TITLE
数据集预处理时报错

### ISSUE THREAD

**Issue by yrsn509** [babysor/MockingBird#390]
1.如果我在train目录下新建一个文件夹，并把音频文件放进去的话，pre.py就会一直卡住不动：

Using data from:
    d:\asoul\aidatatang_200zh\corpus\train
aidatatang_200zh:   0%|                                                                    | 0/1 [00:00<?, ?speakers/s]

2.如果我把音频文件直接放在tran目录下就会报这样的错误：

Using data from:
    d:\asoul\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|█████████████████████████████████████████████████████| 1226/1226 [00:05<00:00, 241.65speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "D:\MockingBird\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "D:\MockingBird\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by yrsn509** [comment]
已解决 应采用第一个办法并需要等待一段时间

**Comment by Nicksooooo** [comment]
train目录下的音频是什么格式的音乐，gz文件吗还是wav的？我是gz文件无法识别，还要一个一个解压到wav格式吗？谢谢大佬！

**Comment by wshbr1314** [comment]
同问
