### ISSUE TITLE
作者快看

### ISSUE THREAD

**Issue by PEK-ZBAA** [babysor/MockingBird#391]
作者，我给你看一眼这张照片，你看是什么原因
![屏幕截图 2022-02-15 192434](https://user-images.githubusercontent.com/71160034/154060064-7f913fd4-55c5-47df-96c4-75d10944253d.png)
生成出来有人声，说的不是人话，叫来叫去的，要不就是一堆杂音

**Comment by babysor** [comment]
模型问题，没训练好

**Comment by PEK-ZBAA** [comment]
作者，那你推荐哪个模型?发我一下

**Comment by babysor** [comment]
> 作者，那你推荐哪个模型?发我一下

拉最新代码， readme分享的我的那个，效果虽然不是最好，但后面你可以自己练。当然也可以找下issue里面其他大哥分享的
