### ISSUE TITLE
【作者快看】大家觉得哪个模型好啊？

### ISSUE THREAD

**Issue by PEK-ZBAA** [babysor/MockingBird#393]
大家好，我现在用的这个模型和原声太不像了，大家有那种克隆更真实的模型推荐吗？能发我一下吗？谢谢各位了

**Comment by luan78zaoha** [comment]
这个项目的方法还是受限于训练数据，当然数据越大越好；因为是“二阶段”模型，所以最终音质和自然度受到中间变量的匹配问题。
你想要更像一些模型。可以看下这个项目https://github.com/CMsmartvoice/One-Shot-Voice-Cloning
