### ISSUE TITLE
前所未有的问题……预处理时显示到100%，但是什么都没生成，什么情况啊

### ISSUE THREAD

**Issue by yy35959199** [babysor/MockingBird#395]
aidatatang_200zh: 100%|█████████████████████████████████████████████████████| 2247/2247 [00:08<00:00, 276.10speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "C:\WorkSpace\Project\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "C:\WorkSpace\Project\MockingBird-main\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

这是什么报错OTZ问了一圈好像没人遇到这个……

**Comment by yy35959199** [comment]
数据集在其他MockingBird那里跑的是正常的，代码用的是最新版也应该没有问题，所以是环境的问题吗……
环境是Anaconda3+python3.9+pytorch1.10.2，组件只装了readme里提过的那些OTZ

**Comment by yy35959199** [comment]
更新：
目前好像是解决了，是我音频路径放错了位置OTZ音频放在train/output里，我没建立Output文件夹
不过现在还是不知道怎么基于别人的模型来继续训练……

**Comment by babysor** [comment]
处理完之后就是运行了，这里的run id指定为别人的文件名即可

**Comment by yy35959199** [comment]
开源者您好！反复看过readme说明之后，我觉得我可能对项目的功能有一些误解？希望能够得到您的解答！


1.项目的功能是什么？
我是看B站视频才知道的，在此之前我的理解是：制作某个人A的说话音频及其对应文本，而后在训练合成器模型过后，运行工具箱或web.py时，可以通过输入一小段A的音频样本，将文本用A的声音生成音频（用谁的声音进行训练，最后就能用谁的声音说话）


但是看过Github上关于开源数据集的描述，预期状态是否是这样的：通过众多数据（许多人的声音+文本）训练合成器之后，输入一小段任意某个人的声音（比如A），再输入文本时，可以用这个人的声音生成音频？（收集足够多人的声音之后，随便来个人输入一小段声音后都能用这个人的声音说话）


2.关于使用其他人的模型：
我已经制作了一个人的数据集，放到aidatatang_200zh文件夹中，执行预处理+训练合成器后，效果不太理想，因此想接着其他人的训练集继续训练，该如何使用？
我已经下载了pretrained-11-7-21_75k.pt，那么我是需要在预处理阶段替换encoder\saved_models\pretrained.pt？
还是用这个替换synthesizer\saved_models\run_id\run_id.pt之后执行python synthesizer_train.py run_id？


3.关于hparams.py中tts_schedule的部分，您分享经验时提到50k步后loss小于0.4，tts_schedule = [(2,&nbsp; 1e-3,&nbsp; 10_000,&nbsp; 12),&nbsp; (2,&nbsp; 5e-4,&nbsp; 15_000,&nbsp; 12),...]这里是跑完10K步之后自动保存一次模型然后再跑15k步吗？50k步是10k+15k+20k...累加的结果吗？


4.我想最大程度复刻A的声音，但是A的数据只有1000多条，那么如果我加入其他数据集（比如18G的aidatatang_200zh），会影响还原A音色吗？
是否需要对hparams.py中的参数进行一些调整？


我没学过机器学习相关的知识，但是现在能尝试使用相关的技术，非常感谢您的开源付出！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 晚上9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 前所未有的问题……预处理时显示到100%，但是什么都没生成，什么情况啊 (Issue #395)





 
处理完之后就是运行了，这里的run id指定为别人的文件名即可
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wshbr1314** [comment]
这个项目代码没有问题，但是有很多环境和安装的问题让人头疼，希望开源者可以给一个很好的解决文档
