### ISSUE TITLE
如果新手不会，建议看已看这篇文章，详细的环境安装过程，内有爬坑

### ISSUE THREAD

**Issue by bravekingzhang** [babysor/MockingBird#397]
https://cloud.tencent.com/developer/article/1945440

**Comment by bravekingzhang** [comment]
不需要解决

**Comment by babysor** [comment]
感谢

**Comment by bravekingzhang** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/4476322/155311067-f0d13dea-bacc-4bd6-8502-891c2ee9929e.png">
界面交互改为这样貌似好理解点。
