### ISSUE TITLE
如何使用训练好的数据集呢

### ISSUE THREAD

**Issue by zhangykevin** [babysor/MockingBird#40]
如题~
我将百度云下载好的训练结果放在E:\Voice\trainmodel，执行python demo_toolbox.py -d E:\Voice\trainmodelc好像并不能成功运行

**Comment by Nthily** [comment]
下载好的数据集是 .pt 文件，把那些里面的什么 saved_models 文件夹丢到项目文件里面的 synthesizer/ 试试
