### ISSUE TITLE
预处理失败，求助

### ISSUE THREAD

**Issue by Xlbnas** [babysor/MockingBird#404]
C:\Users\Administrator\Downloads\MockingBird-main\MockingBird-main>python pre.py C:\Users\Administrator\Downloads -d aidatatang_200zh -n 6
Using data from:
    C:\Users\Administrator\Downloads\aidatatang_200zh\corpus\train
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\MockingBird-main\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "C:\Users\Administrator\Downloads\MockingBird-main\MockingBird-main\synthesizer\preprocess.py", line 45, in preprocess_dataset
    assert all(input_dir.exists() for input_dir in input_dirs)
AssertionError

**Comment by babysor** [comment]
数据集文件路径不正确，确认一下是否有 C:\Users\Administrator\Downloads\aidatatang_200zh\corpus\train

**Comment by NightMare-233** [comment]
感谢，我的aidatatang_200zh文件夹套了两层我没发现
顺带一提，如果只是要训练出来一个特定声音的模型而不是通用模型 ，大概需要多长时间的语音或者几条短句？我大概是2000条短句5个小时，但是训练出来的模型根本无法收敛，是一条直线。我是继续去找数据集还是接着pretrained-11-7-21_75k.pt训练比较好？

**Comment by babysor** [comment]
接着pretrained-11-7-21_75k.pt训练

**Comment by NightMare-233** [comment]
感谢

**Comment by Limingrui0** [comment]
> 感谢

请关闭 issue.
