### ISSUE TITLE
求助， No module named 'vocoder.wavernn'

### ISSUE THREAD

**Issue by hxqbeyond** [babysor/MockingBird#406]
Mac M1，所有依赖包安装完成后运行demo，提示报错，大家有没有思路；

Traceback (most recent call last):
  File "/Users/***/work/demo/MockingBird/demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/Users/***/work/demo/MockingBird/toolbox/__init__.py", line 5, in <module>
    from vocoder.wavernn import inference as rnn_vocoder
ModuleNotFoundError: No module named 'vocoder.wavernn'

**Comment by babysor** [comment]
试着在 vocoder.wavernn 目录里面加一个 __init__.py 的空文件后试试

**Comment by hxqbeyond** [comment]
> 试着在 vocoder.wavernn 目录里面加一个 **init**.py 的空文件后试试

还是照旧 困扰了一天

**Comment by babysor** [comment]
`__init__.py` 文件名字用这个

**Comment by hxqbeyond** [comment]
解决了vocoder目录下文件不齐
