### ISSUE TITLE
我能在训练途中重新进行预处理吗

### ISSUE THREAD

**Issue by yrsn509** [babysor/MockingBird#407]
比如说我想增加或修改源音频以达到更好的训练效果，又不想从头训练的话，能不能实现这种效果？

**Comment by yrsn509** [comment]
![image](https://user-images.githubusercontent.com/62604868/155872625-f2ab9c9d-ad1f-45d7-9dce-dc4afa1dafc2.png)
![image](https://user-images.githubusercontent.com/62604868/155872640-d0ef8e1a-b04e-4684-933b-45dcff4a3c59.png)
还有一个问题是明明原数据集有十几万个音频，但是预处理只生成了九万多个文件，这是为什么？

**Comment by babysor** [comment]
有一些不合格的（太短或太长）会被过滤。
但是按题目，是可以的，。
