### ISSUE TITLE
如何把一个py文件转换成ui文件？方便添加自己的功能并且再次修改界面ui

### ISSUE THREAD

**Issue by flysmart** [babysor/MockingBird#410]
求助作者及各位大佬！

**Comment by babysor** [comment]
不太明白你的意思，能讲一下需求吗

**Comment by flysmart** [comment]
就是如何修改UI界面？是直接改ui.py里面的代码吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 如何把一个py文件转换成ui文件？方便添加自己的功能并且再次修改界面ui (Issue #410)





 
不太明白你的意思，能讲一下需求吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by babysor** [comment]
只是界面的话，直接改toolbox，学一下qt5

**Comment by flysmart** [comment]
qt5在学了！ 我还想请教一下，如果只是训练synthesizer模型的话，可以不安装ffmpeg吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 如何把一个py文件转换成ui文件？方便添加自己的功能并且再次修改界面ui (Issue #410)





 
只是界面的话，直接改toolbox，学一下qt5
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
