### ISSUE TITLE
训练到39k还没有saved_models正常吗

### ISSUE THREAD

**Issue by JerryZRF** [babysor/MockingBird#412]
用的是aidatatang_200zh
{| Epoch: 1/1 (9228/10207) | Loss: 0.4928 | 0.69 steps/s | Step: 39k | }
saved_models文件夹也没有新建，自己新建了一个，用了别人训练好的，但是效果不好。就继续训练。训练了一晚上文件夹还是空的
SV2TTS文件夹25.5 GB (27,449,503,629 字节)
aidatatang_200zh文件夹32.5 GB (34,988,358,844 字节)

**Comment by flysmart** [comment]
你这32.5GB的aidatatang_200zh数据集是原本18G解压出来的吗？

**Comment by JerryZRF** [comment]
> 你这32.5GB的aidatatang_200zh数据集是原本18G解压出来的吗？

是的，但是我解压了aidatatang_200zh\corpus\train里的压缩包后没有删除压缩包，所以可能大一点

**Comment by flysmart** [comment]
好的，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 训练到39k还没有saved_models正常吗 (Issue #412)





  
你这32.5GB的aidatatang_200zh数据集是原本18G解压出来的吗？
  
是的，但是我解压了aidatatang_200zh\corpus\train里的压缩包后没有删除压缩包，所以可能大一点
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arzmi** [comment]
这么厉害？32.5GB的aidatatang_200zh 。 我的数据集自己做的才1个G

**Comment by arzmi** [comment]
你仔细看文件日期是会变动的会保存的

**Comment by JerryZRF** [comment]
> 你仔细看文件日期是会变动的会保存的

我看资源监视器里python.exe一直是写0字节/秒，倒是一直在读。
占用GPU70%，显存5G多
