### ISSUE TITLE
话说收敛曲线怎么样才算合格？

### ISSUE THREAD

**Issue by yrsn509** [babysor/MockingBird#413]
我现在收敛曲线有时能触底有时又不能触底，然后曲线有时还会发散

![attention_step_180500_sample_1](https://user-images.githubusercontent.com/62604868/156282345-463e24e7-18c6-4201-9f21-f8f3158630ae.png)

![attention_step_181000_sample_1](https://user-images.githubusercontent.com/62604868/156282367-dffc292a-e199-4db2-b54f-cab3a78021ad.png)

![attention_step_182500_sample_1](https://user-images.githubusercontent.com/62604868/156282381-ee21ce0e-5655-4d8a-b58c-5142cea1f97d.png)

![attention_step_178500_sample_1](https://user-images.githubusercontent.com/62604868/156282395-8e670143-b95a-4e01-8503-975b911ca71f.png)

**Comment by JerryZRF** [comment]
> 在练的过程中，至少要等到Plots 里面的attention图出现收敛（Convergence），才能正常发出人声，如下图出现一条明显斜线，否则就是一团奇怪噪音，对于loss数字就多寡随意，丰俭由人了。
这是原话  
话说你这个图实在哪里看的呀？我训练了24h了saved_models还是空的

**Comment by JerryZRF** [comment]
> 

我发现了，是我看错目录了。。。
是程序源码所在的MockingBird-main\synthesizer\saved_models\mandarin\plots文件夹是吧
抱歉

**Comment by babysor** [comment]
收敛已经没问题了，就看你训练数据质量和batchsize了，等loss基本不降得时候停下来试试

**Comment by DvHuang** [comment]
这条斜线应该是一条对角线，还是一条45度的斜线，这里的注意力是谁和谁之间的注意力

**Comment by DvHuang** [comment]
查了一下，这里的注意力计算的是源状态（文字编码状态）与目标状态（mel特征隐状态）之间的注意力。很多图后半部分注意力分散代表了什么？
