### ISSUE TITLE
如果对男女性声音分别训练，在克隆时按照性别选择对应模型，同等条件下，相似度会不会提高？

### ISSUE THREAD

**Issue by c6h5no2-sec** [babysor/MockingBird#417]

**Comment by c6h5no2-sec** [comment]
我感觉如果向目前的模型来说，得到的是一个平均值（男女声都有），如果分开训练应该会有用？
大佬们怎么认为我这个观点的

**Comment by babysor** [comment]
人为分类？ 如果数据集有标注性别，不如作为一个高权重得参数输入

**Comment by c6h5no2-sec** [comment]
> 

因为提供的数据集当中都存在着性别标注，不需要人工处理，所以产生了这个想法

**Comment by c6h5no2-sec** [comment]
> 人为分类？ 如果数据集有标注性别，不如作为一个高权重得参数输入

因为提供的数据集当中都存在着性别标注，不需要人工处理，所以产生了这个想法

**Comment by babysor** [comment]
如果还有后续问题请移步 #435
