### ISSUE TITLE
求助！！！在下载剩余的包 pip install -r requirements.txt 报错了 大佬知道咋解决吗

### ISSUE THREAD

**Issue by frankl07** [babysor/MockingBird#422]
以下是报错代码：
Building wheels for collected packages: ctc-segmentation, pyworld
  Building wheel for ctc-segmentation (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.7
      creating build\lib.win-amd64-3.7\ctc_segmentation
      copying ctc_segmentation\ctc_segmentation.py -> build\lib.win-amd64-3.7\ctc_segmentation
      copying ctc_segmentation\partitioning.py -> build\lib.win-amd64-3.7\ctc_segmentation
      copying ctc_segmentation\__init__.py -> build\lib.win-amd64-3.7\ctc_segmentation
      running build_ext
      building 'ctc_segmentation.ctc_segmentation_dyn' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ctc-segmentation
  Running setup.py clean for ctc-segmentation
  Building wheel for pyworld (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.7
      creating build\lib.win-amd64-3.7\pyworld
      copying pyworld\__init__.py -> build\lib.win-amd64-3.7\pyworld
      running build_ext
      skipping 'pyworld\pyworld.cpp' Cython extension (up-to-date)
      building 'pyworld.pyworld' extension
      C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-_y7fbfzj\overlay\Lib\site-packages\setuptools\dist.py:741: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        % (opt, underscore_opt)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyworld
Failed to build ctc-segmentation pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

**Comment by babysor** [comment]
额 pyworld居然需要visual c++依赖 你可以按提示先安装一下。看来有必要把vc 部分给分离出来

**Comment by frankl07** [comment]
问下是怎样把vc分离出来呀。。我这边下载了visual c++

**Comment by frankl07** [comment]
是在mocking bird 文件夹里面安装吗？

**Comment by babysor** [comment]
拉一下最新的，如果你暂时用不到voice conversion功能，再次运行 pip install 就好了

**Comment by frankl07** [comment]
谢谢！问题解决了！

**Comment by houw0517** [comment]
运行 pip install -v -e .之后
报错：
error: subprocess-exited-with-error
× python setup.py develop did not run successfully.
note: This error originates from a subprocess, and is likely not a problem with pip.

 大佬可以分享一下解决过程吗？

**Comment by PandaBalls** [comment]
怎么解决的没人说一下么？？

**Comment by PandaBalls** [comment]
> 谢谢！问题解决了！

楼主辛苦填一下坑呗

**Comment by zombob** [comment]
我来解答。
刚才在一台新windows电脑上安装运行环境，也遇到这个问题。
这个错误是由于没有vc++编译环境造成的。
其实解决方法也简单：从windows官网下载最新版的“visual studio installer”， 安装 vc++ 就行。

**Comment by 0xXPunkX** [comment]
> 拉一下最新的，如果你暂时用不到voice conversion功能，再次运行 pip install 就好了

最新的内容是哪个呀大佬

**Comment by chen-wei-lin** [comment]
我已經將下載的visual studio 2019安裝置最新，他為何依然跑出同樣的錯誤
