### ISSUE TITLE
训练自己的模型中断后，想继续训练上一次的模型，该在终端运行什么指令？

### ISSUE THREAD

**Issue by flysmart** [babysor/MockingBird#429]
我想达到的继续训练效果是指loss和步数都能接着上次的训练结果，比如我这次训练到25K步，loss=0.45，下次训练一开始就能从步数25k，loss=0.45开始 ，那么我该如何输入终端指令？我试着run_id都不变，文件命名也不做任何改动，直接运行python synthesizer_train.py mandarin <datasets_root>/SV2TTS/synthesizer 结果生成了新的训练log，步数和loss也是重头开始的

**Comment by JerryZRF** [comment]
从理论上来说，是接着上次继续的
![image](https://user-images.githubusercontent.com/77944884/156972494-8053854c-7467-4b7e-9ba2-f77c4c2ac37d.png)

**Comment by flysmart** [comment]
我之前在win上试是重来的...
看了你的回答，我又在linux服务器上试了，确实是接着的  多谢指点！

**Comment by JerryZRF** [comment]
> 我之前在win上试是重来的... 看了你的回答，我又在linux服务器上试了，确实是接着的 多谢指点！

我这个就是windows，你在执行`python synthesizer)train.py`时可以加上参数
-s 是指每训练多少steps就保存一下，默认是1000
-b 是指每训练多少steps就备份一下，默认是25000
更多参数打开文件看
