### ISSUE TITLE
无法启动web

### ISSUE THREAD

**Issue by JerryZRF** [babysor/MockingBird#430]
最新的commit
输入`python web.py`报错
> Loaded synthesizer models: 1
Loaded encoder "pretrained.pt" trained to step 1594501
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Building hifigan
Traceback (most recent call last):
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\web.py", line 6, in <module>
    app = webApp()
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\web\__init__.py", line 35, in webApp
    gan_vocoder.load_model(Path("vocoder/saved_models/pretrained/g_hifigan.pt"))
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\vocoder\hifigan\inference.py", line 28, in load_model
    with open(config_fpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: './vocoder/saved_models/24k/config.json'

**Comment by Chopin68** [comment]
我也是一样的情况

**Comment by babysor** [comment]
已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试

**Comment by JerryZRF** [comment]
> 已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试
是不是还有bug
`def load_model(weights_fpath, config_fpath="./vocoder/hifigan/config_16k.json", verbose=True):`
少了一个_
文件名是config_16k_.json

**Comment by babysor** [comment]
已经改了，感谢
