### ISSUE TITLE
使用新版本遇到问题

### ISSUE THREAD

**Issue by Chopin68** [babysor/MockingBird#432]
我在使用hifigan这一vocoder时候会出现以下错误，听不到合成的声音
Read ['欢迎使用工具箱', '现已支持中文输入']
Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']

| Generating 1/1

Done.

Traceback (most recent call last):
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 144, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 284, in vocode
    self.init_vocoder()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 456, in init_vocoder
    model_config_fpath = model_config_fpaths[0]
IndexError: list index out of range

但使用pretrained则不会有该情况出现，可以听到合成后的声音

**Comment by babysor** [comment]
已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试

**Comment by Chopin68** [comment]
> 已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试

Read ['欢迎使用工具箱', '现已支持中文输入']
Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']

| Generating 1/1


Done.

Building hifigan
Traceback (most recent call last):
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 144, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 284, in vocode
    self.init_vocoder()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 465, in init_vocoder
    vocoder.load_model(model_fpath, model_config_fpath)
  File "Z:\deeplearing_project\MockingBird-main\vocoder\hifigan\inference.py", line 28, in load_model
    with open(config_fpath) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

重新下载了整个zip，hifigan还是会出现错误

Read ['欢迎使用工具箱', '现已支持中文输入']
Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']

| Generating 1/1


Done.

Traceback (most recent call last):
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 144, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 305, in vocode
    breaks = [np.zeros(int(0.15 * sample_rate))] * len(breaks)
UnboundLocalError: local variable 'sample_rate' referenced before assignment

这是使用Griffin-Lim的错误

**Comment by babysor** [comment]
> > 已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试
> 
> Read ['欢迎使用工具箱', '现已支持中文输入'] Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']
> 
> | Generating 1/1
> 
> Done.
> 
> Building hifigan Traceback (most recent call last): File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 144, in func = lambda: self.synthesize() or self.vocode() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 284, in vocode self.init_vocoder() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 465, in init_vocoder vocoder.load_model(model_fpath, model_config_fpath) File "Z:\deeplearing_project\MockingBird-main\vocoder\hifigan\inference.py", line 28, in load_model with open(config_fpath) as f: TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> 重新下载了整个zip，hifigan还是会出现错误
> 
> Read ['欢迎使用工具箱', '现已支持中文输入'] Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']
> 
> | Generating 1/1
> 
> Done.
> 
> Traceback (most recent call last): File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 144, in func = lambda: self.synthesize() or self.vocode() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 305, in vocode breaks = [np.zeros(int(0.15 * sample_rate))] * len(breaks) UnboundLocalError: local variable 'sample_rate' referenced before assignment
> 
> 这是使用Griffin-Lim的错误

把vocoder\hifigan\config_16k.json 放到 vocoder\saved models\pretrained 里面十四hi

**Comment by Chopin68** [comment]
> > > 已修复：config默认路径错误，你拉下最新代码 git pull origin/main 试试
> > 
> > 
> > Read ['欢迎使用工具箱', '现已支持中文输入'] Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']
> > | Generating 1/1
> > Done.
> > Building hifigan Traceback (most recent call last): File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 144, in func = lambda: self.synthesize() or self.vocode() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 284, in vocode self.init_vocoder() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 465, in init_vocoder vocoder.load_model(model_fpath, model_config_fpath) File "Z:\deeplearing_project\MockingBird-main\vocoder\hifigan\inference.py", line 28, in load_model with open(config_fpath) as f: TypeError: expected str, bytes or os.PathLike object, not NoneType
> > 重新下载了整个zip，hifigan还是会出现错误
> > Read ['欢迎使用工具箱', '现已支持中文输入'] Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']
> > | Generating 1/1
> > Done.
> > Traceback (most recent call last): File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 144, in func = lambda: self.synthesize() or self.vocode() File "Z:\deeplearing_project\MockingBird-main\toolbox__init__.py", line 305, in vocode breaks = [np.zeros(int(0.15 * sample_rate))] * len(breaks) UnboundLocalError: local variable 'sample_rate' referenced before assignment
> > 这是使用Griffin-Lim的错误
> 
> 把vocoder\hifigan\config_16k.json 放到 vocoder\saved models\pretrained 里面十四hi

成功了，hifigan可以成功合成，但是使用Griffin-Lim还是会出现以下错误：
Read ['欢迎使用工具箱', '现已支持中文输入']
Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']

| Generating 1/1


Done.

Traceback (most recent call last):
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 144, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "Z:\deeplearing_project\MockingBird-main\toolbox\__init__.py", line 305, in vocode
    breaks = [np.zeros(int(0.15 * sample_rate))] * len(breaks)
UnboundLocalError: local variable 'sample_rate' referenced before assignment

**Comment by ptilopsisG** [comment]
请问为什么我更换了新版本的MockingBird-main以后就打不开MockingBird-main了，输入运行命令后会报这个错误
C:\jr\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "C:\jr\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\jr\MockingBird-main\toolbox\__init__.py", line 6, in <module>
    import ppg_extractor as extractor
  File "C:\jr\MockingBird-main\ppg_extractor\__init__.py", line 6, in <module>
    from .frontend import DefaultFrontend
  File "C:\jr\MockingBird-main\ppg_extractor\frontend.py", line 5, in <module>
    from torch_complex.tensor import ComplexTensor
ModuleNotFoundError: No module named 'torch_complex'

**Comment by babysor** [comment]
> 请问为什么我更换了新版本的MockingBird-main以后就打不开MockingBird-main了，输入运行命令后会报这个错误 C:\jr\MockingBird-main>python demo_toolbox.py Traceback (most recent call last): File "C:\jr\MockingBird-main\demo_toolbox.py", line 2, in from toolbox import Toolbox File "C:\jr\MockingBird-main\toolbox__init__.py", line 6, in import ppg_extractor as extractor File "C:\jr\MockingBird-main\ppg_extractor__init__.py", line 6, in from .frontend import DefaultFrontend File "C:\jr\MockingBird-main\ppg_extractor\frontend.py", line 5, in from torch_complex.tensor import ComplexTensor ModuleNotFoundError: No module named 'torch_complex'

还是落后一两个commit，再拉一下最新

**Comment by ptilopsisG** [comment]
>更换了，但是还是不行
 C:\jr\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "C:\jr\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\jr\MockingBird-main\toolbox\__init__.py", line 9, in <module>
    from utils.f0_utils import compute_f0, f02lf0, compute_mean_std, get_converted_lf0uv
  File "C:\jr\MockingBird-main\utils\f0_utils.py", line 3, in <module>
    import pyworld
ModuleNotFoundError: No module named 'pyworld'

**Comment by Chopin68** [comment]
> 

你的环境还没装好吧

**Comment by ptilopsisG** [comment]
是在安装时pyworld报错了，一直装不上pyworld

**Comment by SnowFish00** [comment]
> 是在安装时pyworld报错了，一直装不上pyworld

pip install pyworld

**Comment by SwordMasterJS** [comment]
同上，
然后执行： pip install pyworld
返回：Could not build wheels for pyworld, which is required to install pyproject.toml-based projects
意思是还需要用pyproject.toml去管理？

**Comment by SwordMasterJS** [comment]
![image](https://user-images.githubusercontent.com/32394118/158585036-caba6f52-8623-405d-ae9e-858278b3e25b.png)

看了，我可能缺了Visual C++ 14.我去搞一下

**Comment by SnowFish00** [comment]
> ![图像](https://user-images.githubusercontent.com/32394118/158585036-caba6f52-8623-405d-ae9e-858278b3e25b.png)
> 
> 看了，我可能缺了visual C++ 14.我去搞一下

下一个visual studio 链接：https://visualstudio.microsoft.com/zh-hans/  安装时选择c++ 的拓展安装完成即可

**Comment by SwordMasterJS** [comment]
解决了，确实是以上问题
