### ISSUE TITLE
训练过程中报错

### ISSUE THREAD

**Issue by JerryZRF** [babysor/MockingBird#434]
> {| Epoch: 1/1 (400/52340) | Loss: 0.4498 | 0.55 steps/s | Step: 27k | }Traceback (most recent call last):
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer\train.py", line 255, in train
    eval_model(attention=np_now(attention[sample_idx][:, :attention_len]),
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer\train.py", line 287, in eval_model
    wav = audio.inv_mel_spectrogram(mel_prediction.T, hparams)
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer\audio.py", line 91, in inv_mel_spectrogram
    S = _mel_to_linear(_db_to_amp(D + hparams.ref_level_db), hparams)  # Convert back to linear
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer\audio.py", line 165, in _mel_to_linear
    _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\synthesizer\audio.py", line 169, in _build_mel_basis
    assert hparams.fmax <= hparams.sample_rate // 2
AssertionError

我修改过mandarin.json，但又改回了原状，不知道是不是这个问题
~~~json
{"sample_rate": 14000, "n_fft": 800, "num_mels": 80, "hop_size": 200, "win_size": 800, "fmin": 55, "min_level_db": -100, "ref_level_db": 20, "max_abs_value": 4.0, "preemphasis": 0.97, "preemphasize": true, "tts_embed_dims": 512, "tts_encoder_dims": 256, "tts_decoder_dims": 128, "tts_postnet_dims": 512, "tts_encoder_K": 5, "tts_lstm_dims": 1024, "tts_postnet_K": 5, "tts_num_highways": 4, "tts_dropout": 0.5, "tts_cleaner_names": ["basic_cleaners"], "tts_stop_threshold": -3.4, "tts_schedule": [[2, 0.001, 10000, 14], [2, 0.0005, 15000, 14], [2, 0.0002, 20000, 14], [2, 0.0001, 30000, 14], [2, 5e-05, 40000, 14], [2, 1e-05, 60000, 14], [2, 5e-06, 140000, 14], [2, 3e-06, 320000, 14], [2, 1e-06, 640000, 14]], "tts_clip_grad_norm": 1.0, "tts_eval_interval": 500, "tts_eval_num_samples": 1, "tts_finetune_layers": [], "max_mel_frames": 900, "rescale": true, "rescaling_max": 0.9, "synthesis_batch_size": 16, "signal_normalization": true, "power": 1.5, "griffin_lim_iters": 60, "fmax": 7600, "allow_clipping_in_normalization": true, "clip_mels_length": true, "use_lws": false, "symmetric_mels": true, "trim_silence": true, "speaker_embedding_size": 256, "silence_min_duration_split": 0.4, "utterance_min_duration": 1.6, "use_gst": true, "use_ser_for_gst": true}
~~~

**Comment by babysor** [comment]
fmax，sample rate不能乱改把。。
