### ISSUE TITLE
求助执行requirements.txt时报No module named 'pyworld'是什么问题？？

### ISSUE THREAD

**Issue by bricklayers** [babysor/MockingBird#444]
已是最新代码
E:\MockingBird\MockingBird>python demo_toolbox.py
Traceback (most recent call last):
  File "E:\MockingBird\MockingBird\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "E:\MockingBird\MockingBird\toolbox\__init__.py", line 9, in <module>
    from utils.f0_utils import compute_f0, f02lf0, compute_mean_std, get_converted_lf0uv
  File "E:\MockingBird\MockingBird\utils\f0_utils.py", line 3, in <module>
    import pyworld
ModuleNotFoundError: No module named 'pyworld'

**Comment by babysor** [comment]
BUG 待修复

**Comment by 463315341** [comment]
pip安装pyworld不就可以了

**Comment by shenjusanfen** [comment]
pip pyworld安装失败

**Comment by shenjusanfen** [comment]
我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 求助执行requirements.txt时报No module named 'pyworld'是什么问题？？ (Issue #444)





 
是的，使用 pip install pyworld 单独去安装也是失败，可能是我电脑环境的问题，这时我尝试的全装  pyworld 的历史版本竟然成功了
 
https://pypi.org/project/pyworld/#history
 pip install pyworld==0.2.12
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shenjusanfen** [comment]
> 

你下载的是哪个版本的

**Comment by bricklayers** [comment]
> 0.2.12

**Comment by shenjusanfen** [comment]
> > 0.2.12

好的

**Comment by shenjusanfen** [comment]
> > 0.2.12还是安装失败，错误为
ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\树林耶\\AppData\\Local\\Temp\\pip-install-vlnx96ap\\pyworld_ba3f67a25ede499eb3eb0fdbc186f129\\setup.py'"'"'; __file__='"'"'C:\\Users\\树林耶\\AppData\\Local\\Temp\\pip-install-vlnx96ap\\pyworld_ba3f67a25ede499eb3eb0fdbc186f129\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\树林耶\AppData\Local\Temp\pip-wheel-duqz_bk4'
       cwd: C:\Users\树林耶\AppData\Local\Temp\pip-install-vlnx96ap\pyworld_ba3f67a25ede499eb3eb0fdbc186f129\
  Complete output (13 lines):
  D:\Anaconda\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pyworld
  copying pyworld\__init__.py -> build\lib.win-amd64-3.9\pyworld
  running build_ext
  skipping 'pyworld\pyworld.cpp' Cython extension (up-to-date)
  building 'pyworld.pyworld' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyworld

**Comment by fuyzh** [comment]
试试这个 https://blog.csdn.net/vans05/article/details/116994443 安装c++编译工具后再pip install pyworld

**Comment by shenjusanfen** [comment]
我也好了

**Comment by TervorPO** [comment]
> 试试这个 [https://blog.csdn.net/vans05/article/details/116994443 ](https://blog.csdn.net/vans05/article/details/116994443) 安装c++编译工具后再pip install pyworld

差点给我C盘炸了，还是
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

**Comment by shenjusanfen** [comment]
OSError: Failed to open file b'C:\\Users\\\xe6\xa0\x91\xe6\x9e\x97\xe8\x80\xb6\\AppData\\Local\\Temp\\scipy-xa_hg05d'
这个错误需要怎么修改
