### ISSUE TITLE
搭建环境，最后一步MODULE FILES NOT FOUND, 这个怎么解决？多谢

### ISSUE THREAD

**Issue by LewisJia** [babysor/MockingBird#457]
![image](https://user-images.githubusercontent.com/101646047/158387906-b9b4105e-045e-40b5-b06e-5c6823fdbcaf.png)
大佬们帮看下，谢谢

**Comment by Chopin68** [comment]
你没有模型他怎么运行

**Comment by LewisJia** [comment]
> 

Synthesizer/Saved_models 里面已经放了下载的模型，重启也是了，还是一样的提示
