### ISSUE TITLE
帮忙看一下，训练到了57k,还没有收敛，是不是废了？

### ISSUE THREAD

**Issue by tsyj9850** [babysor/MockingBird#458]
![attention_step_57500_sample_1](https://user-images.githubusercontent.com/101625479/158527714-7a9152c3-d8b1-4c7d-96f8-44545ef0398f.png)

![step-57500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/101625479/158527480-86662900-5ab4-4eaf-bc36-4924a7c2eb11.png)

**Comment by babysor** [comment]
虽然可能问题已经在群上得到答复了，但这里补充一下回答：是的
