### ISSUE TITLE
运行报错缺少pyworld，安装visualstudio后pip install pyworld后报错如下，求解。

### ISSUE THREAD

**Issue by JOKERSLION** [babysor/MockingBird#462]
Collecting pyworld
  Using cached pyworld-0.3.0.tar.gz (212 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in d:\anaconda\data\lib\site-packages (from pyworld) (1.19.3)
Requirement already satisfied: cython>=0.24.0 in d:\anaconda\data\lib\site-packages (from pyworld) (0.29.24)
Building wheels for collected packages: pyworld
  Building wheel for pyworld (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      C:\Users\73465\AppData\Local\Temp\pip-build-env-_ap7ysdb\overlay\Lib\site-packages\setuptools\dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\pyworld
      copying pyworld\__init__.py -> build\lib.win-amd64-3.9\pyworld
      running build_ext
      skipping 'pyworld\pyworld.cpp' Cython extension (up-to-date)
      building 'pyworld.pyworld' extension
      creating build\temp.win-amd64-3.9
      creating build\temp.win-amd64-3.9\Release
      creating build\temp.win-amd64-3.9\Release\lib
      creating build\temp.win-amd64-3.9\Release\lib\World
      creating build\temp.win-amd64-3.9\Release\lib\World\src
      creating build\temp.win-amd64-3.9\Release\pyworld
      D:\visualstudio\visualstudio\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ilib\World\src -IC:\Users\73465\AppData\Local\Temp\pip-build-env-_ap7ysdb\overlay\Lib\site-packages\numpy\core\include -ID:\Anaconda\DATA\include -ID:\Anaconda\DATA\Include -ID:\visualstudio\visualstudio\VC\Tools\MSVC\14.29.30133\include /EHsc /Tplib\World\src\cheaptrick.cpp /Fobuild\temp.win-amd64-3.9\Release\lib\World\src\cheaptrick.obj
      cheaptrick.cpp
      lib\World\src\cheaptrick.cpp(10): fatal error C1083: 无法打开包括文件: “math.h”: No such file or directory
      error: command 'D:\\visualstudio\\visualstudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

**Comment by babysor** [comment]
最新代码移除这个依赖了，可以拉下来试试

**Comment by JOKERSLION** [comment]
> 最新代码移除这个依赖了，可以拉下来试试
解决了，感谢

**Comment by lhzwangwei** [comment]
你好 请问怎么解决的啊
我也遇到了这个问题
