### ISSUE TITLE
在训练synthesizer为什么会无缘无故的报AssertionError

### ISSUE THREAD

**Issue by liulife** [babysor/MockingBird#463]
Traceback (most recent call last):
  File "C:\file\speach\MockingBird\pre.py", line 57, in <module>
    assert args.datasets_root.exists()
AssertionError
![image](https://user-images.githubusercontent.com/59240904/159122550-fdbe1295-fcd0-468c-bcd5-b645c3e141c7.png)

**Comment by babysor** [comment]
路径错误，拼错了

**Comment by babysor** [comment]
或者，你在C盘指定得H盘导致得

**Comment by liulife** [comment]
> 或者，你在C盘指定得H盘导致得

谢谢大哥，问题已经解决了
