### ISSUE TITLE
算我求各位的了别用那狗💩百度云了

### ISSUE THREAD

**Issue by Shaun-Fong** [babysor/MockingBird#466]
传个其它网盘不香吗？干嘛非得用这狗💩百度云呢？

我现在看到百度云盘图标我就犯恶心

巨恶心的那种

非得用网盘那也有一堆可代替的

[天翼云盘](https://cloud.189.cn)也稳
[蓝奏云](https://www.lanzou.com/)也好用得一比

**Comment by wrk226** [comment]
别的网盘好用的原因正是用的人少要抢占市场，如果用户体量达到百度云这个级别那也会变得和百度云一样的，所以你这个问题无解。

**Comment by saxiang** [comment]
谁说的 阿里云盘 yyds

**Comment by SunchinSekian** [comment]
我也觉得！！！！！！！1

**Comment by alexZrAl** [comment]
不知道G drive行不行，反正现在能上github的人多半都能上google

**Comment by litterGuy** [comment]
下载速度绝了
一下午了一个没下载下来
