### ISSUE TITLE
奇怪的注意力模型和较低的Loss是什么情况？以及训练vocoder时失败

### ISSUE THREAD

**Issue by Okimoto-TK** [babysor/MockingBird#467]
**注意力模型居然不是斜的，是直的，而且位于顶部，但是Loss值降低到了0.19。**
**wavrnn不能训练，也没有报错，hifigan显存不够。**

**1k**
![step-1000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192266-af8b1a59-ad6b-4843-8a09-12706578cc31.png)
![attention_step_1000_sample_1](https://user-images.githubusercontent.com/75235761/159192273-9f118433-c232-4238-9998-bccc9070648c.png)
一开始的时候没在意。

**3k**
![step-3000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192289-6c0a32e9-4a20-43e0-9501-d98dd4326318.png)
![attention_step_3000_sample_1](https://user-images.githubusercontent.com/75235761/159192291-1f694d47-a3a6-46a2-8b16-1ab61a792184.png)
这里有事出去了一下，回来就发现问题了。

**5k**
![step-5000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192343-2e635485-9f9f-4bce-95b0-01787058dfd7.png)
![attention_step_5000_sample_1](https://user-images.githubusercontent.com/75235761/159192349-8e9c7619-e428-4327-902d-1ad5e0f2dee0.png)

**10k**
![step-10000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192362-9bb45e00-1f51-4169-80d8-bcb882113a93.png)
![attention_step_10000_sample_1](https://user-images.githubusercontent.com/75235761/159192368-a99d6ddb-8f82-49b1-82c1-98cbd812d59a.png)

**16k**
![step-16000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192381-bb3eb561-f7ac-4e29-9abf-a4fd0032e6a5.png)
![attention_step_16000_sample_1](https://user-images.githubusercontent.com/75235761/159192393-859b52b4-204d-4545-b322-f4d8b1c4f59d.png)

**21k**
![step-21000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/75235761/159192396-59babf99-b58e-46e9-b87e-82643a56435c.png)
![attention_step_21000_sample_1](https://user-images.githubusercontent.com/75235761/159192400-e348f183-88db-4aea-bc94-f5848326e707.png)
然后我回来直接终止训练了。工具箱下测试了一下，不是杂音但也不是人话……

我考虑是不是官方自带vocoder的问题，打算自己训练vocoder，但是wavrnn运行直接退出，无报错。batchsize设置4。
![image](https://user-images.githubusercontent.com/75235761/159192649-b6d96ee5-50f3-4d1f-9696-9ee73bef0122.png)

hifigan也不能训练，batchsize设置4。
![image](https://user-images.githubusercontent.com/75235761/159192570-59417a0c-0348-4e6a-9668-5671a1140cdd.png)

在训练hifigan时还有以下提示
![image](https://user-images.githubusercontent.com/75235761/159192588-3b6cd419-07b5-4650-9d0c-5f387fa3dfa4.png)

**Comment by Okimoto-TK** [comment]
Python 版本：3.7.9
CUDA 版本：11.3
pyTorch 版本：1.11.0
GPU：1060
数据集：aidatatang_200zh

**Comment by babysor** [comment]
sorry，练坏了，要重新开始。到15k的时候还是再顶部就重试把，一开始会有一定失败率
