### ISSUE TITLE
小白求教，这样是正常收敛中的效果吗

### ISSUE THREAD

**Issue by 1239hy** [babysor/MockingBird#474]
![step-76500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/102406483/160229807-38b028c1-eb2d-4759-b047-5f94d27edccd.png)
![attention_step_76500_sample_1](https://user-images.githubusercontent.com/102406483/160229834-845223b9-bd77-4dbc-a2ef-10e84330a7fc.png)

换了新的数据，继续训练的，之前到67K。
现在一直76
这样是正常的吗？现在是继续训练，还是重新开始
求教大佬感谢

**Comment by babysor** [comment]
你这个看起来要正常了，再跑一会
