### ISSUE TITLE
求助作者，无法接着别人模型训练问题

### ISSUE THREAD

**Issue by 1239hy** [babysor/MockingBird#478]
请问是不是修改use_gstuse_ser_for_gst，
两项都修改了，还是一直不能运行
这要怎么办
![QQ图片20220327101314](https://user-images.githubusercontent.com/102406483/160263715-835a65e3-b8dd-4662-899b-e91ac8637ddb.png)

**Comment by babysor** [comment]
模型版本太老 需要切换到老版本

**Comment by 1239hy** [comment]
> 模型版本太老 需要切换到老版本

谢谢大佬的回去，能不能帮我看一下。我的训练线从开始就在顶端到15K还是顶

图

![step-500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/102406483/160281619-10996f1a-d76e-4f09-abc3-64b96aff498e.png)
![attention_step_500_sample_1](https://user-images.githubusercontent.com/102406483/160281622-edfd7d67-eeb7-4b46-b0c8-49598d7e33f4.png)
![Uploading step-15000-mel-spectrogram_sample_1.png…]()
![Uploading attention_step_15000_sample_1.png…]()

**Comment by babysor** [comment]
#437
