### ISSUE TITLE
请教作者，训练成果问题

### ISSUE THREAD

**Issue by 1239hy** [babysor/MockingBird#481]
纯小白想请问，接着pretrained-11-7-21_75k继续训练
模型成果是不是我提供的数据集声音
完成后是我的声音吗？
感谢，还要训练超过75K吗？

**Comment by 1239hy** [comment]
请问从75K到85K，LOSS一直在0.6上下这样正常吗

**Comment by 1239hy** [comment]
到110K还是LOSS下不来还是0.6，这样正常吗，可以继续还是要返工？
返工的话要调整啥嘛？
![attention_step_104500_sample_1](https://user-images.githubusercontent.com/102406483/160376694-7fe0dc66-7714-46b1-b3dd-6e8c37c006a7.png)
![step-104500-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/102406483/160376708-633b44af-56cc-4590-acfb-259d395b202d.png)

**Comment by babysor** [comment]
完成后会接近你的声音，但看起来你的语音质量不高，导致loss不怎么降低了

**Comment by 1239hy** [comment]
> 完成后会接近你的声音，但看起来你的语音质量不高，导致loss不怎么降低了

谢谢大佬的回复，我自己做的语音都是短句，那我要增加语音量还是改一下句长呢？
万分感谢

**Comment by Chopin68** [comment]
> > 完成后会接近你的声音，看起来你的声音怎么不高，导致损失不降低但
> 
> 谢谢大佬的回复，我自己做的都是短句，那我要 感谢增加语音量还是改一下句长呢？

看起来你的数据集不够多 而且不够清晰 并且没有经过筛选，或者你的声音比较特别 不然训练这么多次 还是迁移学习的情况下不可能是这个loss的

**Comment by babysor** [comment]
> > 完成后会接近你的声音，但看起来你的语音质量不高，导致loss不怎么降低了
> 
> 谢谢大佬的回复，我自己做的语音都是短句，那我要增加语音量还是改一下句长呢？ 万分感谢

多一点语音量，尽可能到小时级别

**Comment by sxwzxc** [comment]
Hello...
