### ISSUE TITLE
能出一个视频教程嘛

### ISSUE THREAD

**Issue by ffspig** [babysor/MockingBird#49]
本人是一个小白，真的尝试去做了，好在一些安装下载配置别人有出教程，但不同人出的并不连贯，让我产生一种莫名其妙的感觉，很多东西在于细节，也许他所讲授的方法适用于这个特定的问题，但并不适用于项目，拜托了

**Comment by babysor** [comment]
网友正在制作中，很快会发布了

**Comment by aiwibadi** [comment]
同求，小白，需要基础的安装视频以及操作视频，或者稍微详细点操作文档！亦或者有靓仔辅助可以有偿付些费用

**Comment by babysor** [comment]
社区视频教程：
https://www.bilibili.com/video/BV1DL4y1q7VL
@FangPengbo @aiwibadi @lcp580 
看看是否可以做个更好得  @kulu2001
