### ISSUE TITLE
训练合成器时无法收敛

### ISSUE THREAD

**Issue by wangqiuyangaki** [babysor/MockingBird#491]
**问题简述**
使用自己的数据集训练合成器模型的时候的时候，在预处理之后训练合成器并将合成器替换成既有model后产生的图并没有收敛。

**复现与环境**

参照www.bilibili.com/video/BV1dq4y137pH 进行的复现。代码版本为main branch，首先进行数据预处理之后参考视频里的首先进行合成器训练，然后用pretrained-11-7-21 替换掉当前mode 继续进行训练。发现图并没有收敛。
**截图**
[![qX67L9.png](https://s1.ax1x.com/2022/04/06/qX67L9.png)](https://imgtu.com/i/qX67L9)
[![qX6bZR.png](https://s1.ax1x.com/2022/04/06/qX6bZR.png)](https://imgtu.com/i/qX6bZR)

**Comment by babysor** [comment]
看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误

**Comment by wangqiuyangaki** [comment]
> 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误

我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。

**Comment by babysor** [comment]
> > 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误
> 
> 我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。

路径是否正确…如果一切正确 起始step会是比较大的值

**Comment by wangqiuyangaki** [comment]
> 



> > > 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误
> > 
> > 
> > 我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。
> 
> 路径是否正确…如果一切正确 起始step会是比较大的值
## 使用的cmd为：
 python synthesizer_train.py xxxx G:\\data\\SV2TTS\\synthesizer
xxxx 就是main branch 文件里model的名字。是我用pretrained 替换的（就改了pretrained的名字）。

**Comment by babysor** [comment]
> > 
> 
> > > > 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误
> > > 
> > > 
> > > 我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。
> > 
> > 
> > 路径是否正确…如果一切正确 起始step会是比较大的值
> 
> ## 使用的cmd为：python synthesizer_train.py xxxx G:\data\SV2TTS\synthesizer
> xxxx 就是main branch 文件里model的名字。是我用pretrained 替换的（就改了pretrained的名字）。

有点奇怪，那你截图的文件夹路径是？

**Comment by wangqiuyangaki** [comment]
> > > 
> > 
> > 
> > > > > 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误
> > > > 
> > > > 
> > > > 我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。
> > > 
> > > 
> > > 路径是否正确…如果一切正确 起始step会是比较大的值
> > 
> > 
> > ## 使用的cmd为：python synthesizer_train.py xxxx G:\data\SV2TTS\synthesizer
> > xxxx 就是main branch 文件里model的名字。是我用pretrained 替换的（就改了pretrained的名字）。
> 
> 有点奇怪，那你截图的文件夹路径是？

是main branch 文件夹里save_models，我的model 的plot里的图。

**Comment by wangqiuyangaki** [comment]
> > > 
> > 
> > 
> > > > > 看步数不对，没有成功基于 pretrained-11-7-21 训练，确认一下文件名没有错误
> > > > 
> > > > 
> > > > 我中途强制退出了，因为一直没有呈现收敛感觉图不对。请问需要我一直train吗？文件名是使用 pretrained-11-7-21 然后改成自己的model的名字（按照视频里的操作）来的。
> > > 
> > > 
> > > 路径是否正确…如果一切正确 起始step会是比较大的值
> > 
> > 
> > ## 使用的cmd为：python synthesizer_train.py xxxx G:\data\SV2TTS\synthesizer
> > xxxx 就是main branch 文件里model的名字。是我用pretrained 替换的（就改了pretrained的名字）。
> 
> 有点奇怪，那你截图的文件夹路径是？

data  和 程序并不在一个directory里

**Comment by babysor** [comment]
目前判断是路径问题，你确认一下训练打印时的路径里是不是你下载的预训练模型

**Comment by wangqiuyangaki** [comment]
> 目前判断是路径问题，你确认一下训练打印时的路径里是不是你下载的预训练模型

还有就是预处理时没有像视频教程里那样打印出no words，请问这是正常情况吗

**Comment by babysor** [comment]
> > 目前判断是路径问题，你确认一下训练打印时的路径里是不是你下载的预训练模型
> 
> 还有就是预处理时没有像视频教程里那样打印出no words，请问这是正常情况吗

正常

**Comment by wangqiuyangaki** [comment]
> > > 目前判断是路径问题，你确认一下训练打印时的路径里是不是你下载的预训练模型
> > 
> > 
> > 还有就是预处理时没有像视频教程里那样打印出no words，请问这是正常情况吗
> 
> 正常

排查了一下，我训练用的是git bash的命令行，不是powershell也不是cmd，是不是这里的路径问题呢？但是我现在用powershell train发现速度非常慢。。。

**Comment by wangqiuyangaki** [comment]
又重新测试了一下， 路径都正确的情况下，steps仍旧只有500

**Comment by wangqiuyangaki** [comment]
解决了，我之前一直用的git bash 调用的py文件，导致了路径不对，使用cmd后就正确了。
