### ISSUE TITLE
librosa reports warning as "From version 0.10 passing these as positional arguments will result in an error" that massed up the console output.

### ISSUE THREAD

**Issue by moosewoler** [babysor/MockingBird#496]
预处理时报warning：
![图片](https://user-images.githubusercontent.com/526821/162190595-c94c3057-5f6f-485a-a5e7-87e697785e49.png)
修改encoder/audio.py第59、60行如图可去除报警：
![图片](https://user-images.githubusercontent.com/526821/162192284-e9748ace-d380-4dc3-ad81-7050cd9cd8e3.png)

相关包版本：

```
Package                 Version
----------------------- ---------------
librosa                 0.9.1
torch                   1.9.0
torchaudio              0.9.0a0+33b2469
torchfile               0.1.0
torchvision             0.10.0
```

I have no idea why the version of librosa differs from ` requirements.txt`.

git状态：

```
(mockingbird) moose@dl:~/p_project/20220406_MockingBird/MockingBird-github$ git status
位于分支 main
您的分支与上游分支 'origin/main' 一致。

尚未暂存以备提交的变更：
  （使用 "git add <文件>..." 更新要提交的内容）
  （使用 "git checkout -- <文件>..." 丢弃工作区的改动）

        修改：     encoder/audio.py
        修改：     synthesizer/preprocess.py
        修改：     web/config/default.py
```

**Comment by babysor** [comment]
Could you please callout a pull request and I will review ASAP?

**Comment by moosewoler** [comment]
> 

natürlich

**Comment by Vedarutvija** [comment]
Hi, I'm having the same issue, how to solve it @moosewoler

**Comment by JalleyLin** [comment]
I also have the same problem. how to solve it?

**Comment by daozhi0921** [comment]
Does this warning affect the results of model training?   How can I solve it?
