### ISSUE TITLE
关于能不能使用gpu训练

### ISSUE THREAD

**Issue by wangqiuyangaki** [babysor/MockingBird#501]
**问题简述**
想问一下能不能通过GPU训练呢（具体就是用synthesizer_train的时候能不能使用GPU？

**复现与环境**
我搜了一下，将synthesizer_train头部加上了 
[![Le3P5d.png](https://s1.ax1x.com/2022/04/12/Le3P5d.png)](https://imgtu.com/i/Le3P5d)
请问下这样就可以使用GPU训练了么？

**Comment by wangqiuyangaki** [comment]
已解决，问题在于pytorch是cpu版本，uninstall后重新下载即可

**Comment by GUGUGU-01** [comment]
加了那个代码才能用GPU吗

**Comment by akiaki1996** [comment]
> 加了那个代码才能用GPU吗

是的，让你使用gpu而不是cpu
