### ISSUE TITLE
模型无法学习8k赫兹以上的音频信息

### ISSUE THREAD

**Issue by 584761274** [babysor/MockingBird#507]
![微信图片_20220418123334](https://user-images.githubusercontent.com/75121140/163754928-af30c682-4813-40b2-aba9-5439f46d60c8.png)
上图为输出的音频，无法输出8k赫兹以上的声音
![微信图片_20220418123337](https://user-images.githubusercontent.com/75121140/163754952-925f4c98-ea1d-4a45-b350-dcbd13cda8d3.png)
下图为数据集中的音频

**Comment by 584761274** [comment]
不知道应该调整哪个参数

**Comment by babysor** [comment]
fmax 全文搜索一下
