### ISSUE TITLE
训练模型时 不调用GPU

### ISSUE THREAD

**Issue by FirstMelody** [babysor/MockingBird#52]
3990x+两张3090
0.12-0.086step/s
CPU占用为70%
GPU无占用
![image_2021-08-27_09-53-22](https://user-images.githubusercontent.com/80917076/131061099-748e6755-afb7-481c-9f22-33c88835d127.png)
![image_2021-08-27_09-49-06](https://user-images.githubusercontent.com/80917076/131061116-93ed1ba2-72e6-4017-8684-8a82e5fc4298.png)
![image_2021-08-27_09-49-54](https://user-images.githubusercontent.com/80917076/131061119-d16996a0-6866-4039-b30e-d18c9a7d51cb.png)

**Comment by FirstMelody** [comment]
![image](https://user-images.githubusercontent.com/80917076/131282015-a4b2f3fa-875b-45a3-a2c3-f0b0bb8b98e4.png)
成功调用了 但是又有了新的问题诶...

**Comment by babysor** [comment]
> ![image](https://user-images.githubusercontent.com/80917076/131282015-a4b2f3fa-875b-45a3-a2c3-f0b0bb8b98e4.png)
> 成功调用了 但是又有了新的问题诶...

看起来像手动停止了训练，你可以加微信群咨询

**Comment by FirstMelody** [comment]
> > ![image](https://user-images.githubusercontent.com/80917076/131282015-a4b2f3fa-875b-45a3-a2c3-f0b0bb8b98e4.png)
> > 成功调用了 但是又有了新的问题诶...
> 
> 看起来像手动停止了训练，你可以加微信群咨询

在哪里加群？

**Comment by oceanarium** [comment]
> > > ![image](https://user-images.githubusercontent.com/80917076/131282015-a4b2f3fa-875b-45a3-a2c3-f0b0bb8b98e4.png)
> > > 成功调用了 但是又有了新的问题诶...
> > 
> > 
> > 看起来像手动停止了训练，你可以加微信群咨询
> 
> 在哪里加群？

![WechatIMG54](https://user-images.githubusercontent.com/7423248/130546423-5588bc46-af02-4eda-a122-f64d8f4b7627.jpeg)

**Comment by babysor** [comment]
已解决

**Comment by jephsdge** [comment]
> 已解决

问一下怎么解决的

**Comment by GUGUGU-01** [comment]
> 已解决

同样用不了GPU 可以给个群吗
