### ISSUE TITLE
python3 运行demo_toolbox.py的时候提示 Error: Model files not found. Please download the models

### ISSUE THREAD

**Issue by kirin0926** [babysor/MockingBird#524]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型

**Screenshots[截图（如有）]**
If applicable, add screenshots to help
<img width="571" alt="image" src="https://user-images.githubusercontent.com/17965372/165520089-6559daf8-eb9f-42d4-86e0-91745516f116.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/17965372/165520273-45558385-928d-4ad7-ac44-050a203c8779.png">
缺少了这些模块，可以通过brew安装吗，还是要用pip安装，希望一个大佬来讲解下

**Comment by babysor** [comment]
没有模型文件，要按readme下载

**Comment by kirin0926** [comment]
> 

谢啦，我去看看

**Comment by yuzhishen** [comment]
@babysor 报错一样，但是pt文件已经在E:\code\opensource\MockingBird\synthesizer\saved_models下了，在MockingBird目录下运行demo_toolbox，issues里相关错误都试过了，还是不行。怎么排查一下这问题呢？？ts~
