### ISSUE TITLE
大佬声码器预处理报错

### ISSUE THREAD

**Issue by 1239hy** [babysor/MockingBird#527]
请教这是什么情况
![sunlogin_20220503011318](https://user-images.githubusercontent.com/102406483/166295088-45aeb273-cb72-499c-9ac4-cd463a435038.gif)

**Comment by babysor** [comment]
路径拼错单词

**Comment by 1239hy** [comment]
> 路径拼错单词

谢谢大佬了，一直在这里跟你学习。。
感谢感谢
