### ISSUE TITLE
请问在运行python demo_toolbox.py时出现无法解码的问题

### ISSUE THREAD

**Issue by C-hello** [babysor/MockingBird#534]
版本是python3.8
图片如下：
![图片](https://user-images.githubusercontent.com/104720135/166918396-5601aad0-f601-4687-8c7b-796b2723ad92.png)
这是python的问题还是demo_toolbox.py的问题或其他的？

**Comment by babysor** [comment]
看下readme里面的Q&A

**Comment by C-hello** [comment]
里面似乎没有我遇到的问题 @babysor

**Comment by babysor** [comment]
https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF

**Comment by C-hello** [comment]
谢谢
