### ISSUE TITLE
不认识的错误，有谁教教吗

### ISSUE THREAD

**Issue by NONAME-2121237** [babysor/MockingBird#536]
Loaded encoder "pretrained.pt" trained to step 1594501
Synthesizer using device: cuda
Trainable Parameters: 32.869M
Traceback (most recent call last):
  File "C:\Users\abc\Documents\yvyinhechengqi\MockingBird-main\toolbox\__init__.py", line 259, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds, style_idx=int(self.ui.style_slider.value()), min_stop_token=min_token, steps=int(self.ui.length_slider.value())*200)
  File "C:\Users\abc\Documents\yvyinhechengqi\MockingBird-main\synthesizer\inference.py", line 93, in synthesize_spectrograms
    self.load()
  File "C:\Users\abc\Documents\yvyinhechengqi\MockingBird-main\synthesizer\inference.py", line 71, in load
    self._model.load(self.model_fpath, self.device)
  File "C:\Users\abc\Documents\yvyinhechengqi\MockingBird-main\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]).
        size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]).
        size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]).
        size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]).
        size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048]).
就是这样，不能正常运行，会出现杂音而且输出的音频长度和我输入的字段长度无关
![屏幕截图 2022-05-05 231745](https://user-images.githubusercontent.com/104999550/166956245-19bc6dd3-73d5-4d48-ac95-690bf51b08bd.png)

**Comment by SunchinSekian** [comment]
换个模型，这个模型有兼容性问题

**Comment by NONAME-2121237** [comment]
> 换个模型，这个模型有兼容性问题

谢谢解决了，请问有训练好的hifigan_vocoder吗，我不知道怎么训练wavernn_vocoder,按照作者写的直接运行就提示没有指定vocoder的类型
