### ISSUE TITLE
有无大佬看看这是啥问题

### ISSUE THREAD

**Issue by SchweitzerGAO** [babysor/MockingBird#537]
**Summary[问题简述（一句话）]**
我在实验室的机器上训练，使用的是我自己收集的，并且用aishell3数据集格式标注的数据，总是报这个错误（见截图）
**Env & To Reproduce[复现与环境]**
OS: CentOS 7
Python: Anaconda+python 3.8
pytorch:1.11.0
CUDA:11.4

**Screenshots[截图（如有）]**
![image](https://user-images.githubusercontent.com/64410968/166958716-7c5fb945-72d3-4869-b2a9-b0da07c4aeb4.png)

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
Look in the original repo RTVC and search ValueError in issues I saw the same problem being answered before.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
Send your full notebook for better debug if you wish.

**Comment by SchweitzerGAO** [comment]
> Send your full notebook for better debug if you wish.

Many thanks if that's convenient for you. By the way, could you please give me the link of the 'original repo of RTVC' please?

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning

**Comment by SchweitzerGAO** [comment]
Thanks @zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z but which issue exactly did you referred to? I found many similar issues...
