### ISSUE TITLE
在生成录音时闪退

### ISSUE THREAD

**Issue by wangqinNick** [babysor/MockingBird#54]
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
python: src/hostapi/alsa/pa_linux_alsa.c:3641: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed.
Aborted (core dumped)

**Comment by betsyalan** [comment]
同样的问题。我使用的是ubuntu系统。
