### ISSUE TITLE
训练synthesizer时，如何获得已经收敛的模型？

### ISSUE THREAD

**Issue by Emiya0415** [babysor/MockingBird#550]
晚上挂着训练日语模型的时候，今早起来突然发现在18000step和19500step的时候已经完全收敛了，但是还在挂着一直训练，好像没有自动保存的样子。怎么获得对应step的模型？
18000step
![attention_step_18000_sample_1](https://user-images.githubusercontent.com/41981371/168208843-d4201776-fa6b-432c-a52c-1b5a17336629.png)
:
19500ste
![attention_step_19500_sample_1](https://user-images.githubusercontent.com/41981371/168208879-0523515a-8e83-40d7-951b-6f6e2d440fa9.png)
p
由于一直挂着，现在已经到25k了，自动保存的好像也是25k的
25000:
![attention_step_25500_sample_1](https://user-images.githubusercontent.com/41981371/168208911-82e7ae94-ef90-4021-805c-4805b9b8b2ed.png)
有办法获得对应step的模型吗，还是只能人工看收敛的时候停止训练？

**Comment by Emiya0415** [comment]
好像找不回来了，pt文件被覆盖了，只能在synthesizer_train.py里面修改每500步备份一次了。其他人看到的话也请注意这点

**Comment by babysor** [comment]
对的，但是可以再训练一段时间，loss和效果比较满意的时候。
