### ISSUE TITLE
Signal passing ERROR 

### ISSUE THREAD

**Issue by Vedarutvija** [babysor/MockingBird#557]
![image](https://user-images.githubusercontent.com/52282654/168531337-180b50ee-fa72-4338-84da-82e5be73992a.png)
Librosa reports and ERROR: Pass y=[-0.0043335  -0.04104614 -0.10864258 ...  0.12042236  0.09857178
  0.03143311] as keyword args. From version 0.10 passing these as positional arguments will result in an error

Can someone help me solve this

**Comment by babysor** [comment]
This is just a future warning that talks us to upgrade dependency but everything still works. I wish you can help to get rid of this warning by passing the right order of parameters

**Comment by babysor** [comment]
> This is just a future warning that talks us to upgrade dependency but everything still works. I wish you can help to get rid of this warning by passing the right order of parameters

https://github.com/babysor/MockingBird/pull/498 it's fixed by someone, you can pull and verify it.
