### ISSUE TITLE
200zh数据集解压后，第一步预处理报错

### ISSUE THREAD

**Issue by pythonerrnewer** [babysor/MockingBird#56]
(RVCC) D:\Realtime-Voice-Clone-Chinese-main\Realtime-Voice-Clone-Chinese-main>python synthesizer_preprocess_audio.py D:\data\
Arguments:
    datasets_root:   D:\data
    out_dir:         D:\data\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   False
    dataset:         aidatatang_200zh

Using data from:
    D:\data\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|████████████████████████████████████████████████████████| 420/420 [01:02<00:00,  6.71speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 64, in <module>
    preprocess_dataset(**vars(args))
  File "D:\Realtime-Voice-Clone-Chinese-main\Realtime-Voice-Clone-Chinese-main\synthesizer\preprocess.py", line 76, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by KyleCaiW** [comment]
www.openslr.org/62/

**Comment by AeroXi** [comment]
我也遇到了同样的问题

**Comment by babysor** [comment]
> 我也遇到了同样的问题

一般就是数据路径有误

**Comment by tisttsf** [comment]
同样问题,解决了吗?怎么解决的?数据集的内容要解压吗?
> aidatatang_200zh\corpus
里的tar.gz格式内容要解压吗?

**Comment by pythonerrnewer** [comment]
> 同样问题,解决了吗?怎么解决的?数据集的内容要解压吗?
> 
> > aidatatang_200zh\corpus
> > 里的tar.gz格式内容要解压吗?

对，全都解压

**Comment by braveboymy** [comment]
遇到了同样的问题，我把corpus下所有压缩文件都解压为单独文件夹了，还是报错

(yuyi_copy) E:\clonevoice\MockingBird>python pre.py F:\dataset\
Using data from:
    F:\dataset\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|████████████████████████████████████████████████████████| 185/185 [00:23<00:00,  7.77speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "pre.py", line 73, in <module>
    preprocess_dataset(**vars(args))
  File "E:\clonevoice\MockingBird\synthesizer\preprocess.py", line 82, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

目录格式如下：


![image](https://user-images.githubusercontent.com/35607138/136074539-9501b95b-642c-4e1a-802e-44d17794124d.png)

**Comment by Feyman91** [comment]
请问楼主解决了吗

**Comment by HaSaKiYasuooo** [comment]
这里也是一个坑，数据太多了，我用了4000个音频丢进去，一样的报错，减少数据量
