### ISSUE TITLE
运行pip install -r requirements.txt 来安装剩余的必要包时出错

### ISSUE THREAD

**Issue by worlol** [babysor/MockingBird#561]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.
运行pip install -r requirements.txt 来安装剩余的必要包时出错
**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型、
**Screenshots[截图（如有）]**
If applicable, add screenshots to help
![~3@{I3@IT%BOVDRZ2)E%1I9](https://user-images.githubusercontent.com/105853222/169274037-297fea56-6f5b-46b2-879d-42d8ba2c77d5.png)

![16 %JH0EG5%$Y6UP)JNH54](https://user-images.githubusercontent.com/105853222/169274066-1e6d2d32-3db3-47ee-8c97-5121dd694d77.png)

**Comment by lianchenxiang** [comment]
I encounter this problem too

**Comment by babysor** [comment]
Pyworld requires to install C++ compiler, please make sure yours is correctly installed.

**Comment by bilibini** [comment]
我也是同样的问题，我用的是python3.8版本，报错主要是pyworld模块，感觉问题应该是出在python版本兼容的问题。
![image](https://user-images.githubusercontent.com/57828856/174485119-2c00f7b3-b7d9-4202-a3e0-715738dca124.png)
pyworld模块目前最新版本只支持python3.7。

**Comment by babysor** [comment]
windows的pyworld可以支持3.9，但我额外按提示安装了C++ compiler,

**Comment by Allenwsz12** [comment]
请问这个问题现在有解决方案了吗？ @worlol

**Comment by lianchenxiang** [comment]
应该在anaconda的虚拟环境下安装剩余安装包；

按照教程一步一步来没有问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] 运行pip install -r requirements.txt 来安装剩余的必要包时出错 (Issue #561)





 
请问这个问题现在有解决方案了吗？ @worlol
