### ISSUE TITLE
vocoder comparison

### ISSUE THREAD

**Issue by ireneb612** [babysor/MockingBird#572]
Is there a comparison between vocoders?

**Comment by babysor** [comment]
People usually downloaded different pretrained and compared. But I prefer you read papers regarding their difference and apply the right one according to your requirement.

**Comment by ireneb612** [comment]
OK, because I trained the models from the original repository, but I want to try to train a new vocoder, do you know which files I should modify?

**Comment by babysor** [comment]
> OK, because I trained the models from the original repository, but I want to try to train a new vocoder, do you know which files I should modify?

The folder of vocoder should be the place to go. Are you trying to do this from the original repository or this one w/ well-constructed new vocoders?

**Comment by ireneb612** [comment]
@babysor with this one! But I got en error that I reported in a new ISSUE about a module in fre gan.
