### ISSUE TITLE
stft_loss

### ISSUE THREAD

**Issue by ireneb612** [babysor/MockingBird#577]
I tried to use the FREGAN vocoder but I got this error!

_**ModuleNotFoundError: No module named 'vocoder.fregan.stft_loss'**_

And indeed there is not such script

**Comment by babysor** [comment]
@flysmart Any idea?

**Comment by flysmart** [comment]
> @flysmart Any idea?



> @flysmart Any idea?

I have submitted a new PR: Added missing files for Fre-GAN

**Comment by flysmart** [comment]
> @flysmart Any idea?

I have submitted a new PR: Added missing files for Fre-GAN

**Comment by flysmart** [comment]
> I tried to use the FREGAN vocoder but I got this error!
> 
> _**ModuleNotFoundError: No module named 'vocoder.fregan.stft_loss'**_
> 
> And indeed there is not such script

Shífēn gǎnxiè nǐ tíchūle wèntí, qǐng děngdài dàimǎ gēngxīn jiějué gāi wèntí
23 / 5,000
翻译结果
Thank you very much for asking the question, please wait for the code update to resolve the issue

**Comment by flysmart** [comment]
> I tried to use the FREGAN vocoder but I got this error!
> 
> _**ModuleNotFoundError: No module named 'vocoder.fregan.stft_loss'**_
> 
> And indeed there is not such script

Thank you very much for asking the question, please wait for the code update to resolve the issue

**Comment by babysor** [comment]
Fixed.
