### ISSUE TITLE
打开web端后，左侧显示模式选择，但是右侧报错，如下

### ISSUE THREAD

**Issue by novolands** [babysor/MockingBird#578]
ImportError: DLL load failed while importing shell: 找不到指定的程序。
Traceback:
File "D:\anaconda\envs\aivoice\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
File "C:\Users\giant\AppData\Local\Temp\tmpp_sbx1jh.py", line 14, in <module>
    render_streamlit_ui()
File "D:\voice\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 838, in render_streamlit_ui
    opyrator = getOpyrator(mode)
File "D:\voice\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 818, in getOpyrator
    from mkgui.app import synthesize
File "D:\voice\MockingBird-main\mkgui\app.py", line 6, in <module>
    from encoder import inference as encoder
File "D:\voice\MockingBird-main\encoder\inference.py", line 3, in <module>
    from encoder.audio import preprocess_wav   # We want to expose this function from here
File "D:\voice\MockingBird-main\encoder\audio.py", line 7, in <module>
    import librosa
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\util\__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
File "D:\anaconda\envs\aivoice\lib\site-packages\librosa\util\files.py", line 28, in <module>
    __data_path = os.environ.get("LIBROSA_DATA_DIR", pooch.os_cache("librosa"))
File "D:\anaconda\envs\aivoice\lib\site-packages\pooch\utils.py", line 99, in os_cache
    return Path(appdirs.user_cache_dir(project))
File "D:\anaconda\envs\aivoice\lib\site-packages\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
File "D:\anaconda\envs\aivoice\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
请问有没有大佬知道如何解决

**Comment by novolands** [comment]
问题已经解决了，pywin32版本过低导致的，安装了最新版后问题解决

**Comment by JackShaw2333** [comment]
我也遇到了同样的问题，然而我是在使用pywin32最新版（304）遇到的。 故特此对本issue的解决方法进行补充。我是通过将pywin32降级到303版本解决了这个error，`pip install pywin32 --upgrade pywin32==303`

以下是我的环境信息，仅供参考。
os: win10 21h2 19044.1806
python: 3.9.12

absl-py                 1.1.0
altair                  4.2.0
aniso8601               9.0.1
appdirs                 1.4.4
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
asttokens               2.0.5
attrs                   21.4.0
audioread               2.1.9
backcall                0.2.0
beautifulsoup4          4.11.1
bleach                  5.0.0
blinker                 1.4
brotlipy                0.7.0
cachetools              5.2.0
certifi                 2022.6.15
cffi                    1.15.0
charset-normalizer      2.0.4
ci-sdr                  0.0.0
click                   8.1.3
colorama                0.4.5
ConfigArgParse          1.5.3
cryptography            37.0.1
ctc-segmentation        1.7.1
cycler                  0.11.0
Cython                  0.29.30
debugpy                 1.6.0
decorator               5.1.1
defusedxml              0.7.1
dill                    0.3.5.1
Distance                0.1.3
einops                  0.4.1
entrypoints             0.4
espnet                  202205
espnet-tts-frontend     0.0.3
executing               0.8.3
fast-bss-eval           0.1.3
fastjsonschema          2.15.3
filelock                3.7.1
Flask                   2.1.2
Flask-Cors              3.0.10
flask-restx             0.5.1
Flask-WTF               1.0.1
fonttools               4.33.3
g2p-en                  2.1.0
gevent                  21.8.0
gitdb                   4.0.9
GitPython               3.1.27
google-auth             2.8.0
google-auth-oauthlib    0.4.6
greenlet                1.1.2
grpcio                  1.47.0
h5py                    3.7.0
humanfriendly           10.0
idna                    3.3
importlib-metadata      4.12.0
inflect                 5.6.0
ipykernel               6.15.0
ipython                 8.4.0
ipython-genutils        0.2.0
ipywidgets              7.7.1
itsdangerous            2.1.2
jaconv                  0.3
jamo                    0.4.1
jedi                    0.18.1
Jinja2                  3.1.2
joblib                  1.1.0
jsonpatch               1.32
jsonpointer             2.3
jsonschema              4.6.0
jupyter-client          7.3.4
jupyter-core            4.10.0
jupyterlab-pygments     0.2.2
jupyterlab-widgets      1.1.1
kaldiio                 2.17.2
kiwisolver              1.4.3
librosa                 0.9.1
llvmlite                0.38.1
Markdown                3.3.7
MarkupSafe              2.1.1
matplotlib              3.5.2
matplotlib-inline       0.1.3
mistune                 0.8.4
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
multiprocess            0.70.13
munkres                 1.1.4
nbclient                0.6.4
nbconvert               6.5.0
nbformat                5.4.0
nest-asyncio            1.5.5
nltk                    3.7
notebook                6.4.12
numba                   0.55.2
numpy                   1.19.3
oauthlib                3.2.0
packaging               21.3
pandas                  1.4.3
pandocfilters           1.5.0
parso                   0.8.3
pickleshare             0.7.5
Pillow                  9.0.1
pip                     21.2.4
pooch                   1.6.0
prometheus-client       0.14.1
prompt-toolkit          3.0.29
protobuf                3.19.4
psutil                  5.9.1
pure-eval               0.2.2
pyarrow                 8.0.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pydeck                  0.7.1
Pygments                2.12.0
Pympler                 1.0.1
pynndescent             0.5.7
pyOpenSSL               22.0.0
pyparsing               3.0.9
pypinyin                0.44.0
PyQt5                   5.15.7
PyQt5-Qt5               5.15.2
PyQt5-sip               12.11.0
pyreadline3             3.4.1
pyrsistent              0.18.1
PySocks                 1.7.1
python-dateutil         2.8.2
pytorch-wpe             0.0.1
pytz                    2022.1
pytz-deprecation-shim   0.1.0.post0
PyWavelets              1.3.0
pywin32                 303
pywinpty                2.0.5
pyworld                 0.3.0
PyYAML                  5.4.1
pyzmq                   23.2.0
regex                   2022.6.2
requests                2.27.1
requests-oauthlib       1.3.1
resampy                 0.2.2
rsa                     4.8
scikit-learn            1.1.1
scipy                   1.8.1
semver                  2.13.0
Send2Trash              1.8.0
sentencepiece           0.1.96
setuptools              61.2.0
six                     1.16.0
smmap                   5.0.0
sounddevice             0.4.4
SoundFile               0.10.3.post1
soupsieve               2.3.2.post1
stack-data              0.3.0
streamlit               1.8.0
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
terminado               0.15.0
threadpoolctl           3.1.0
tinycss2                1.1.1
toml                    0.10.2
toolz                   0.11.2
torch                   1.11.0
torch-complex           0.4.3
torchaudio              0.11.0
torchfile               0.1.0
torchvision             0.12.0
tornado                 6.1
tqdm                    4.64.0
traitlets               5.3.0
typeguard               2.13.3
typing_extensions       4.1.1
tzdata                  2022.1
tzlocal                 4.2
umap-learn              0.5.3
unicodedata2            14.0.0
Unidecode               1.3.4
urllib3                 1.26.9
validators              0.20.0
visdom                  0.1.8.9
watchdog                2.1.9
wcwidth                 0.2.5
webencodings            0.5.1
webrtcvad-wheels        2.0.10.post2
websocket-client        1.3.3
Werkzeug                2.1.2
wheel                   0.37.1
widgetsnbextension      3.6.1
win-inet-pton           1.1.0
wincertstore            0.2
WTForms                 3.0.1
zipp                    3.8.0
zope.event              4.5.0
zope.interface          5.4.0

**Comment by white0rchardpUnK** [comment]
> 

同样遇到报错，尝试降级pywin后终于显示出真正的bug，未安装vc++套件，安装后编译成功（win1122H2
![2022-10-26_224449](https://user-images.githubusercontent.com/6168406/198062151-7a94b8f0-4dba-4d0d-98e0-79f33db8c48b.jpg)
![2022-10-26_224621](https://user-images.githubusercontent.com/6168406/198062273-3bcddb7e-c8ad-43b3-a410-11ebe70840ae.jpg)
![2022-10-26_225816](https://user-images.githubusercontent.com/6168406/198062313-cf6c2d49-d0e1-42cf-bd3a-234030bb7c46.jpg)
