### ISSUE TITLE
加载音频程序未响应

### ISSUE THREAD

**Issue by 6Bpencle** [babysor/MockingBird#58]
cuda 10.2
python 3.9.6
pytorch 1.9.0
已添加训练好的数据集

D:\Realtime-Voice-Clone-Chinese-main>python demo_toolbox.py -d D:\Realtime-Voice-Clone-Chinese-main --no_mp3_support
Arguments:
    datasets_root:    D:\Realtime-Voice-Clone-Chinese-main
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   True
然后再也没有输出

![image](https://user-images.githubusercontent.com/31346958/131167569-4d1100d7-b4e0-456a-9df3-b541fe4cc3d0.png)

**Comment by babysor** [comment]
你的数据集都在这个文件夹下吗？

**Comment by 6Bpencle** [comment]
> 你的数据集都在这个文件夹下吗？

通过重新安装pytorch解决了

**Comment by XiuChen-Liu** [comment]
> > 你的数据集都在这个文件夹下吗？
> 
> 通过重新安装pytorch解决了

請問你也是在訓練完模型後，鍵入  `python demo_toolbox.py -d <datasets_root>` 打開toolbox時沒有如視頻一樣加載數據集嗎
如果是這樣你是安裝什麼版本的 pytorch 呢?

**Comment by 6Bpencle** [comment]
> > > 你的数据集都在这个文件夹下吗？
> > 
> > 
> > 通过重新安装pytorch解决了
> 
> 請問你也是訓練完模型後，鍵入 `python demo_toolbox.py -d <datasets_root>` 打開toolbox時沒有如視頻一樣加載數據集嗎
> 如果是這樣你是安裝什麼版本的 pytorch 呢?

我用的是别人已经训练好的模型（README里面的Baidu Yun链接）， Pytorch在Windows下最好使用CPU版本，CUDA版本的兼容性不是很好
训练用的语料库，如aidatatang_200zh，需要解压，不是.tgz/.tar文件直接放在一个文件夹下
![image](https://user-images.githubusercontent.com/31346958/131207278-fb5105a7-0660-459f-b903-6b0dd4393e9c.png)
如图，我的<datasets_root>就是D:\Realtime-Voice-Clone-Chinese-main

**Comment by XiuChen-Liu** [comment]
> > > > 你的数据集都在这个文件夹下吗？
> > > 
> > > 
> > > 通过重新安装pytorch解决了
> > 
> > 
> > 請問你也是訓練完模型後，鍵入 `python demo_toolbox.py -d <datasets_root>` 打開toolbox時沒有如視頻一樣加載數據集嗎
> > 如果是這樣你是安裝什麼版本的 pytorch 呢?
> 
> 我用的是别人已经训练好的模型（README里面的Baidu Yun链接）， Pytorch在Windows下最好使用CPU版本，CUDA版本的兼容性不是很好
> 训练用的语料库，如aidatatang_200zh，需要解压，不是.tgz/.tar文件直接放在一个文件夹下
> ![image](https://user-images.githubusercontent.com/31346958/131207278-fb5105a7-0660-459f-b903-6b0dd4393e9c.png)
> 如图，我的<datasets_root>就是D:\Realtime-Voice-Clone-Chinese-main

謝謝你的回覆，因為我使用的是 aishell3 數據集，在跑這段程式碼時沒有成功加載進 toolbox，不知道是不是代碼要修改一下才能適應 aishell3數據集，我再去試試 !

**Comment by XiuChen-Liu** [comment]
謝謝你的回覆，因為我使用的是 aishell3 數據集，在跑這段程式碼時沒有成功加載進 toolbox，不知道是不是代碼要修改一下才能適應 aishell3數據集，我再去試試 !
