### ISSUE TITLE
使用版本7f799d322f7599跑模型pretrained-11-7-21_75k.pt时遇到报错：raise ValueError("Axis limits cannot be NaN or Inf")

### ISSUE THREAD

**Issue by kate123wong** [babysor/MockingBird#581]
**Summary[问题简述（一句话）]**
使用版本`7f799d322f7599`跑模型pretrained-11-7-21_75k.pt时遇到报错：`raise ValueError("Axis limits cannot be NaN or Inf")`
**Env & To Reproduce[复现与环境]**
+ 环境
    + mac电脑
    + python3.9.12
    + torch1.7.1
+ commit log 版本:
```
commit 7f799d322f7599d466c61a527e8c01ef117a4ed2
Author: babysor00 <babysor00@gmail.com>
Date:   Sat Apr 30 10:31:01 2022 +0800

    Tell the hifigan type of a vocoder model by searching full text
```

+ 模型
pretrained-11-7-21_75k.pt

**Screenshots[截图（如有）]**
<img width="1107" alt="截屏2022-05-26 上午8 07 05" src="https://user-images.githubusercontent.com/49824982/170388979-c04c54f6-64bf-4aa3-a7f9-675f17e1ca65.png">

**Comment by JXTang-syc** [comment]
#571

**Comment by kate123wong** [comment]
解决了，谢谢！

**Comment by lcvslc** [comment]
> 解决了，谢谢！

请问这个问题要怎么解决
