### ISSUE TITLE
vocoder pt

### ISSUE THREAD

**Issue by ireneb612** [babysor/MockingBird#583]
I'm training a HIFI vocoder for now and I  was wondering which is the difference between the **do_hifigan.pt** and the **g_hifigan.pt** !
Also I noticed that the gound_truth argument in the vocoder_train.py script is not actually used in the train script, Am I wrong?

**Comment by babysor** [comment]
Is do_hifigan your own trained model?

**Comment by ireneb612** [comment]
@babysor Idk, i I get these two .pt when doing the training, the g_hifigan.pt is much smaller in size.
Another question, I am at:
**Steps : 29000, Gen Loss Total : 26.293, Mel-Spec. Error : 0.344, s/b : 1.412**

is it normal that the voice is still robotic? How many steps should i normally do? 

Thank you

**Comment by ireneb612** [comment]
@babysor Also I have tried your vocoder, the pretrained one and it is robotic too :(

**Comment by babysor** [comment]
29000 steps is far too early to have a good result.
