### ISSUE TITLE
大概一个数据集多少次会过拟合？

### ISSUE THREAD

**Issue by JXTang-Nocturne** [babysor/MockingBird#585]
我训练我老师的专用合成器，大概300句，结果练了不到1000下，就开始原地波动了，换数据集的话loss又从0.7开始，降了0.02又不动了，请问是因为过拟合了吗？该如何解决？

**Comment by babysor** [comment]
确实快速过拟合了。增加更多数据集（有不同句子）

**Comment by JXTang-Nocturne** [comment]
> 确实快速过拟合了。增加更多数据集（有不同句子）

请问作者，我修改过saved_every和log_every参数，与这有关吗

**Comment by babysor** [comment]
> > 确实快速过拟合了。增加更多数据集（有不同句子）
> 
> 请问作者，我修改过saved_every和log_every参数，与这有关吗

没有关系

**Comment by JXTang-Nocturne** [comment]
> 没有关系

谢谢
