### ISSUE TITLE
根据作者训练进度继续训练合成器报错

### ISSUE THREAD

**Issue by JXTang-Nocturne** [babysor/MockingBird#592]
size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
是顺着my_run8_25k.pt练的
顺着pretrained-11-7-21_75k.pt就没问题

**Comment by Summerxu86** [comment]
请问如何根据作者训练进度继续训练呢？我想顺着pretrained-11-7-21_75k.pt，应该把这个pt文件重命名吗？然后放到哪个文件夹下呢？

**Comment by Summerxu86** [comment]
> size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]). 是顺着my_run8_25k.pt练的 顺着pretrained-11-7-21_75k.pt就没问题



> size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]). 是顺着my_run8_25k.pt练的 顺着pretrained-11-7-21_75k.pt就没问题

请问如何根据作者训练进度继续训练呢？我想顺着pretrained-11-7-21_75k.pt，应该把这个pt文件重命名吗？然后放到哪个文件夹下呢？

**Comment by Noct-Cp** [comment]
> 请问如何根据作者训练进度继续训练呢？我想顺着pretrained-11-7-21_75k.pt，应该把这个pt文件重命名吗？然后放到哪个文件夹下呢？

就是先开始训练，等那个epoch出来了之后ctrl c终止，进入synthesizer/saved_models/<模型名称>文件夹，将<模型名称>.pt删掉，然后把pretrained-11-7-21_75.pt拷进去，改名为<模型名称>.pt，再次训练就行了
（<模型名称>就是您的新模型的名字）

**Comment by Summerxu86** [comment]
kill -9 进程号终止可以吗？



---- 回复的原邮件 ----
| 发件人 | YuChen ***@***.***> |
| 日期 | 2022年07月09日 13:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [babysor/MockingBird] 根据作者训练进度继续训练合成器报错 (Issue #592) |

请问如何根据作者训练进度继续训练呢？我想顺着pretrained-11-7-21_75k.pt，应该把这个pt文件重命名吗？然后放到哪个文件夹下呢？

就是先开始训练，等那个epoch出来了之后ctrl c终止，进入synthesizer/saved_models/<模型名称>文件夹，将<模型名称>.pt删掉，然后把pretrained-11-7-21_75.pt拷进去，改名为<模型名称>.pt，再次训练就行了
（<模型名称>就是您的新模型的名字）

**Comment by Noct-Cp** [comment]
> kill -9 进程号终止可以吗？

应该可以
