### ISSUE TITLE
使用aishell3數據集，關於Warning: you do not have any of the recognized datasets的問題

### ISSUE THREAD

**Issue by XiuChen-Liu** [babysor/MockingBird#61]
請問我在輸入 `python demo_toolbox.py -d C:\aishell3_data` 後卻沒有像視頻一樣預先載入訓練好的Dataset是哪邊出狀況了嗎?
(我的檔案存放路徑:  `C:\aishell3_data\aishell3`)

![Inked1630119737056_LI](https://user-images.githubusercontent.com/55180847/131204408-24f8dd7a-0216-4bd4-baa8-20a955926327.jpg)
![1630119755557](https://user-images.githubusercontent.com/55180847/131204414-fa40e810-b0b0-4fe8-a32a-bf4265d6d88a.jpg)

**Comment by XiuChen-Liu** [comment]
如有使用 aidatatang_200zh 數據集發生一樣問題的，可以參考 #58。

**Comment by babysor** [comment]
Fix in main branch, please verify

**Comment by XiuChen-Liu** [comment]
好勒謝謝作者，我試試，這個issues先關閉

**Comment by MC-dusk** [comment]
我用magicdata的dev数据集也遇到了相同的问题，报错找不到可识别的数据集，但没加载数据集也能用，所以这一步到底有什么用呢？
