### ISSUE TITLE
生成完语音会释放内存嘛，总是内存占满

### ISSUE THREAD

**Issue by zhzhongshi** [babysor/MockingBird#611]
https://github.com/AkashiCoin/nonebot_plugin_mockingbird/issues/10
如上，

**Comment by babysor** [comment]
> [AkashiCoin/nonebot_plugin_mockingbird#10](https://github.com/AkashiCoin/nonebot_plugin_mockingbird/issues/10) 如上，

好像确实内存有引用到音频，你找到位置了吗？
