### ISSUE TITLE
Web server 无法跑起来

### ISSUE THREAD

**Issue by jearton** [babysor/MockingBird#613]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型

Debian 11
Python 3.9

```
git clone --depth=1 https://github.com/babysor/MockingBird.git
pip install torch torchvision
apt update && apt install -y ffmpeg make automake gcc g++
cd MockingBird && pip install -r requirements.txt
pip install webrtcvad-wheels typer pydantic fastapi loguru cn2an
```

**Screenshots[截图（如有）]**
If applicable, add screenshots to help
![image](https://user-images.githubusercontent.com/10370433/173192639-5297680b-bf4f-43dc-a901-3c0a74c2071b.png)

**Comment by babysor** [comment]
有个依赖版本有问题，你指定一下 click<=8.0.4 试试

**Comment by jearton** [comment]
@babysor 我已经解决了，我还自己打了一个docker镜像，可以正常使用。https://hub.docker.com/r/jearton1024/mocking-bird

欢迎试用一下，提点建议，我会不断改进的。

**Comment by Jinkeee** [comment]
> @babysor 我已经解决了，我还自己打了一个docker镜像，可以正常使用。https://hub.docker.com/r/jearton1024/mocking-bird
> 
> 欢迎试用一下，提点建议，我会不断改进的。

您好，请问您是怎么解决这个问题的？

**Comment by gfhjjk** [comment]
@jearton 你的docker镜像没有模型吗，打开8080网页里没有合成模型

**Comment by jearton** [comment]
> @jearton 你的docker镜像没有模型吗，打开8080网页里没有合成模型

模型都在data目录下面，可以从宿主机上挂载进去，再重启容器就能看到了

**Comment by jesuiskiki** [comment]
> @babysor 我已经解决了，我还自己打了一个docker镜像，可以正常使用。https://hub.docker.com/r/jearton1024/mocking-bird
> 
> 欢迎试用一下，提点建议，我会不断改进的。

你好，我是个 docker 新手，请问拉取这个镜像后，执行 docker run -it jearton1024/mocking-bird /bin/bash 返回：

init samples...
init models for encoder...
init models for vocoder...
Running web server...
2023-11-16 06:04:04.197 INFO    matplotlib.font_manager: generated new fontManager

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.3:8080
  External URL: http://46.3.242.192:8080

但是在浏览器中打开 http://46.3.242.192:8080 或 http://172.17.0.3:8080 都显示“无法访问此页面”
请问会是什么原因？谢谢！
