### ISSUE TITLE
下载完成后，确保 xxx.pt 格式的文件放在代码库的 synthesizer\saved_models文件夹下，是什么意思？

### ISSUE THREAD

**Issue by iOS-Kel** [babysor/MockingBird#617]
<img width="1060" alt="图片" src="https://user-images.githubusercontent.com/22427032/173240380-775b3b23-3c4d-4b70-b831-aeaf233bdf79.png">

<img width="625" alt="图片" src="https://user-images.githubusercontent.com/22427032/173240469-a721760f-bb30-4463-bc73-973190f64eda.png">

<img width="841" alt="图片" src="https://user-images.githubusercontent.com/22427032/173240542-432beb4c-56d6-4768-83dd-45bb756dff97.png">

**Comment by babysor** [comment]
synthesizer放到synthesizer/saved_models
另两个也是分别放到对应得saved_models下
