### ISSUE TITLE
请问这段源码是不是有问题？

### ISSUE THREAD

**Issue by jearton** [babysor/MockingBird#624]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.

中文说明对不上吧，extractor不是特征提取模型吗？

![image](https://user-images.githubusercontent.com/10370433/174426187-61f32dee-872f-4ace-86f3-5660d4f1b101.png)

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型

master分支，mkgui/app_vc.py

**Screenshots[截图（如有）]**
If applicable, add screenshots to help

**Comment by babysor** [comment]
已修复，下次可以试着直接改，发起pr，成为贡献者
