### ISSUE TITLE
is not supported, please vote for it in https://github.com/babysor/MockingBird/issues/10

### ISSUE THREAD

**Issue by 18klove** [babysor/MockingBird#625]
Traceback (most recent call last):
  File "MockingBird-main\pre.py", line 55, in <module>
    assert args.dataset in recognized_datasets, 'is not supported, please vote for it in https://github.com/babysor/MockingBird/issues/10'
AssertionError: is not supported, please vote for it in https://github.com/babysor/MockingBird/issues/10
预训练就这样了，什么原因

**Comment by babysor** [comment]
没正确指定数据集类型，贴一下命令？

**Comment by 18klove** [comment]
能教我具体怎么操作吗&nbsp; 谢谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月21日(星期二) 晚上11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [babysor/MockingBird] is not supported, please vote for it in https://github.com/babysor/MockingBird/issues/10 (Issue #625)





 
没正确指定数据集类型，贴一下命令？

**Comment by 18klove** [comment]
怎么操作

**Comment by babysor** [comment]
请使用正确的issue提问，这里的问题没头没尾，无法知道你要操作什么
