### ISSUE TITLE
linux下文件目录路径问题， \\识别不了

### ISSUE THREAD

**Issue by markjun** [babysor/MockingBird#627]
![image](https://user-images.githubusercontent.com/12456223/175273013-bd1a099a-41aa-4d14-a079-1d48539def26.png)
修改过mkgui/app.py里面的目录
![image](https://user-images.githubusercontent.com/12456223/175273225-99a28846-07ea-4454-aad0-673f36f3f1dc.png)
但是还是有很多目录原因，请问有linux的分支或者如何转换下么

另外，这个报错我注释掉了
![image](https://user-images.githubusercontent.com/12456223/175273470-224ea541-4db9-4929-b9fb-74fca18fd669.png)

py: 3.9.0
![image](https://user-images.githubusercontent.com/12456223/175505862-3d2d6d26-c14d-4d76-ab20-8db2c7dfb422.png)

**Comment by markjun** [comment]
![image](https://user-images.githubusercontent.com/12456223/175279777-15902837-7004-45a1-8966-4bb53cd3d7b1.png)
求救

**Comment by babysor** [comment]
路径问题我已经修复推到了main。
看你右面这里好像是 sounddevice依赖有问题，可能是python 3.9下载这个依赖版本有误，试着指定一个兼容的
