### ISSUE TITLE
plots and mels are removed during training

### ISSUE THREAD

**Issue by lawrence124** [babysor/MockingBird#632]
plots and mels are mistakenly removed during training

windows 11, pytorch 1.9.0, cuda 11.1, mockingbird downloaded on 1st of July 2022

![image](https://user-images.githubusercontent.com/29505986/176909837-900a900f-efb9-49e8-9024-398d64ee5caf.png)

from what i understand, the code in train.py is intended to keep the most updated 20 plots/mels...but seems it removes all

![image](https://user-images.githubusercontent.com/29505986/176910107-5ac2bf73-c8d9-417b-85e9-5f7463566d2a.png)

**Comment by MarkIzhao** [comment]
请问解决了吗？我遇到了一样的情况  windows 11, pytorch 1.10.2, cuda 11.3

**Comment by MarkIzhao** [comment]
{| Epoch: 624/1179 (73/73) | Loss: 0.3658 | 1.0 steps/s | Step: 119k | }
{| Epoch: 625/1179 (73/73) | Loss: 0.3747 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 626/1179 (73/73) | Loss: 0.3779 | 1.0 steps/s | Step: 119k | }
{| Epoch: 627/1179 (73/73) | Loss: 0.3655 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 628/1179 (73/73) | Loss: 0.3729 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 629/1179 (73/73) | Loss: 0.3694 | 1.0 steps/s | Step: 119k | }
{| Epoch: 630/1179 (73/73) | Loss: 0.3718 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 631/1179 (10/73) | Loss: 0.3757 | 1.0 steps/s | Step: 120k | }Input at step 120000: wo3 gan3 jue2 na4 ge4 huai4 dan4 shi4 zen3 me5 lian4 cheng2 de5~______________________________________________________________________________________________
{| Epoch: 631/1179 (73/73) | Loss: 0.3823 | 1.1 steps/s | Step: 120k | }
{| Epoch: 632/1179 (73/73) | Loss: 0.3770 | 1.0 steps/s | Step: 120k | }
{| Epoch: 633/1179 (73/73) | Loss: 0.3740 | 1.0 steps/s | Step: 120k | }
{| Epoch: 634/1179 (73/73) | Loss: 0.3723 | 1.0 steps/s | Step: 120k | }
{| Epoch: 635/1179 (73/73) | Loss: 0.3750 | 1.0 steps/s | Step: 120k | }
{| Epoch: 636/1179 (73/73) | Loss: 0.3715 | 1.0 steps/s | Step: 120k | }
{| Epoch: 637/1179 (72/73) | Loss: 0.3797 | 1.0 steps/s | Step: 120k | }Input at step 120500: zhe4 ge4 ni3 bu2 shi4 mei2 chi1 bao3~______________________________________________________________________
{| Epoch: 637/1179 (73/73) | Loss: 0.3781 | 1.0 steps/s | Step: 120k | }
{| Epoch: 638/1179 (73/73) | Loss: 0.3752 | 1.0 steps/s | Step: 120k | }
{| Epoch: 639/1179 (73/73) | Loss: 0.3719 | 1.0 steps/s | Step: 120k | }}
{| Epoch: 640/1179 (73/73) | Loss: 0.3714 | 1.0 steps/s | Step: 120k | }}
{| Epoch: 641/1179 (73/73) | Loss: 0.3697 | 0.97 steps/s | Step: 120k | }
{| Epoch: 642/1179 (73/73) | Loss: 0.3778 | 0.98 steps/s | Step: 120k | }
{| Epoch: 643/1179 (73/73) | Loss: 0.3722 | 0.98 steps/s | Step: 120k | }
{| Epoch: 644/1179 (61/73) | Loss: 0.3695 | 0.96 steps/s | Step: 121k | }Input at step 121000: ni3 yi2 ding4 shi4 ba3 wo3 de5 ben3 zhi4 kan4 qing1 chu3 le5~__________________________________________
{| Epoch: 644/1179 (73/73) | Loss: 0.3712 | 0.97 steps/s | Step: 121k | }
{| Epoch: 645/1179 (32/73) | Loss: 0.3713 | 0.97 steps/s | Step: 121k | }

**Comment by MarkIzhao** [comment]
{| Epoch: 624/1179 (73/73) | Loss: 0.3658 | 1.0 steps/s | Step: 119k | }
{| Epoch: 625/1179 (73/73) | Loss: 0.3747 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 626/1179 (73/73) | Loss: 0.3779 | 1.0 steps/s | Step: 119k | }
{| Epoch: 627/1179 (73/73) | Loss: 0.3655 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 628/1179 (73/73) | Loss: 0.3729 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 629/1179 (73/73) | Loss: 0.3694 | 1.0 steps/s | Step: 119k | }
{| Epoch: 630/1179 (73/73) | Loss: 0.3718 | 1.0 steps/s | Step: 119k | }}
{| Epoch: 631/1179 (10/73) | Loss: 0.3757 | 1.0 steps/s | Step: 120k | }Input at step 120000: wo3 gan3 jue2 na4 ge4 huai4 dan4 shi4 zen3 me5 lian4 cheng2 de5~______________________________________________________________________________________________
{| Epoch: 631/1179 (73/73) | Loss: 0.3823 | 1.1 steps/s | Step: 120k | }
{| Epoch: 632/1179 (73/73) | Loss: 0.3770 | 1.0 steps/s | Step: 120k | }
{| Epoch: 633/1179 (73/73) | Loss: 0.3740 | 1.0 steps/s | Step: 120k | }
{| Epoch: 634/1179 (73/73) | Loss: 0.3723 | 1.0 steps/s | Step: 120k | }
{| Epoch: 635/1179 (73/73) | Loss: 0.3750 | 1.0 steps/s | Step: 120k | }
{| Epoch: 636/1179 (73/73) | Loss: 0.3715 | 1.0 steps/s | Step: 120k | }
{| Epoch: 637/1179 (72/73) | Loss: 0.3797 | 1.0 steps/s | Step: 120k | }Input at step 120500: zhe4 ge4 ni3 bu2 shi4 mei2 chi1 bao3~______________________________________________________________________
{| Epoch: 637/1179 (73/73) | Loss: 0.3781 | 1.0 steps/s | Step: 120k | }
{| Epoch: 638/1179 (73/73) | Loss: 0.3752 | 1.0 steps/s | Step: 120k | }
{| Epoch: 639/1179 (73/73) | Loss: 0.3719 | 1.0 steps/s | Step: 120k | }}
{| Epoch: 640/1179 (73/73) | Loss: 0.3714 | 1.0 steps/s | Step: 120k | }}
{| Epoch: 641/1179 (73/73) | Loss: 0.3697 | 0.97 steps/s | Step: 120k | }
{| Epoch: 642/1179 (73/73) | Loss: 0.3778 | 0.98 steps/s | Step: 120k | }
{| Epoch: 643/1179 (73/73) | Loss: 0.3722 | 0.98 steps/s | Step: 120k | }
{| Epoch: 644/1179 (61/73) | Loss: 0.3695 | 0.96 steps/s | Step: 121k | }Input at step 121000: ni3 yi2 ding4 shi4 ba3 wo3 de5 ben3 zhi4 kan4 qing1 chu3 le5~__________________________________________
{| Epoch: 644/1179 (73/73) | Loss: 0.3712 | 0.97 steps/s | Step: 121k | }
{| Epoch: 645/1179 (32/73) | Loss: 0.3713 | 0.97 steps/s | Step: 121k | }

训练了十三个小时，一条预览图都没有

**Comment by lawrence124** [comment]
> 请问解决了吗？我遇到了一样的情况 windows 11, pytorch 1.10.2, cuda 11.3

just comment out the block of code, line 268-278, so it wont delete/remove the plots image 

it is just a quick fix, will not a fix of what the author intend to do (keep only the latest 20 files)

**Comment by MarkIzhao** [comment]
> > 请问解决了吗？我遇到了一样的情况 windows 11， pytorch 1.10.2， cuda 11.3
> 
> 只需注释掉代码块，第268-278行，因此它不会删除/删除绘图图像
> 
> 它只是一个快速修复，不会修复作者打算做的事情（只保留最新的20个文件）

好的 非常感谢

**Comment by babysor** [comment]
fixed in last trunk of code，please verify and close this issue
