### ISSUE TITLE
web界面 AI拟音  提示No such file or directory:错误  求解  谢谢 

### ISSUE THREAD

**Issue by yxwudi** [babysor/MockingBird#635]
错误界面
![捕获](https://user-images.githubusercontent.com/108532659/177673466-c793dc8a-042c-432a-9266-4fbea2985629.PNG)

**Comment by odinggg** [comment]
项目路径下新建文件夹wavs就行了

**Comment by yxwudi** [comment]
谢谢&nbsp; &nbsp; 好了&nbsp; &nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babysor/MockingBird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月9日(星期六) 上午10:41
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [babysor/MockingBird] web界面 AI拟音  提示No such file or directory:错误  求解  谢谢  (Issue #635)





 
项目路径下新建文件夹wavs就行了
