### ISSUE TITLE
这样正常么 pre.py

### ISSUE THREAD

**Issue by Limingrui0** [babysor/MockingBird#651]
准备 aishell3 时 94 秒一个人。

conda python 3.9 cuda 10.2 torch 1.9.0 vision 0.10.0

![image](https://user-images.githubusercontent.com/65227354/179400835-43cd51cc-ec0a-4601-8fe5-91df315999be.png)

**Comment by babysor** [comment]
正常，aishell预处理约4小时，可以看下怎么通过缓存降低计算时间？
