### ISSUE TITLE
运行pip install -r requirements.txt 来安装剩余的必要包。  本步骤报错。

### ISSUE THREAD

**Issue by pzhyyd** [babysor/MockingBird#659]
Collecting pytz-deprecation-shim
  Using cached https://mirrors.aliyun.com/pypi/packages/eb/73/3eaab547ca809754e67e06871cff0fc962bafd4b604e15f31896a0f94431/pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Using cached https://mirrors.aliyun.com/pypi/packages/89/2d/49329ebec33b14dae61ecc8c85abe596341832fa36c4bcd3d99fddda018b/tzdata-2022.1-py2.py3-none-any.whl (339 kB)
Building wheels for collected packages: ctc-segmentation, pyworld
  Building wheel for ctc-segmentation (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'G:\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\驿 迪\\AppData\\Local\\Temp\\pip-install-3pzcee3t\\ctc-segmentation_0c410bfa3f27404a9b4c45e8b15eb36b\\setup.py'"'"'; __file__='"'"'C:\\Users\\驿迪\\AppData\\Local\\Temp\\pip-install-3pzcee3t\\ctc-segmentation_0c410bfa3f27404a9b4c45e8b15eb36b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\驿迪\AppData\Local\Temp\pip-wheel-ibop6woa'
       cwd: C:\Users\驿迪\AppData\Local\Temp\pip-install-3pzcee3t\ctc-segmentation_0c410bfa3f27404a9b4c45e8b15eb36b\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\ctc_segmentation
  copying ctc_segmentation\ctc_segmentation.py -> build\lib.win-amd64-3.9\ctc_segmentation
  copying ctc_segmentation\partitioning.py -> build\lib.win-amd64-3.9\ctc_segmentation
  copying ctc_segmentation\__init__.py -> build\lib.win-amd64-3.9\ctc_segmentation
  running build_ext
  building 'ctc_segmentation.ctc_segmentation_dyn' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for ctc-segmentation
  Running setup.py clean for ctc-segmentation
  Building wheel for pyworld (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'G:\Anaconda3\python.exe' 'G:\Anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\驿迪\AppData\Local\Temp\tmpmkyamjn5'
       cwd: C:\Users\驿迪\AppData\Local\Temp\pip-install-3pzcee3t\pyworld_968cc4a95e404047bd2e743cd355bd23
  Complete output (15 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte (sitecustomize.py, line 21)
  G:\Anaconda3\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pyworld
  copying pyworld\__init__.py -> build\lib.win-amd64-3.9\pyworld
  running build_ext
  skipping 'pyworld\pyworld.cpp' Cython extension (up-to-date)
  building 'pyworld.pyworld' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
Failed to build ctc-segmentation pyworld
ERROR: Could not build wheels for pyworld which use PEP 517 and cannot be installed directly

**Comment by pzhyyd** [comment]
需要去下载 "Microsoft C++ Build Tools":           https://visualstudio.microsoft.com/visual-cpp-build-tools/
进网页下载
![image](https://user-images.githubusercontent.com/44706193/179780268-b2e58d2d-1e7a-4632-98fc-206842160902.png)

**Comment by Element-Square** [comment]
跟个鬼似的, 处理了七八个问题还有   没完没了

**Comment by Element-Square** [comment]
![9bd3984e2b44ff2578c4ffba675ce84](https://user-images.githubusercontent.com/55553696/181707985-3b956dae-de5d-46a7-afd3-4d16608384b9.jpg)
安装试试

**Comment by LegendRGC** [comment]
useful!
