### ISSUE TITLE
Add Spanish language trainset support

### ISSUE THREAD

**Issue by noobperezesp** [babysor/MockingBird#66]
Now I have a lot of demand for Spanish dubbing, so I hope someone add the support of Spanish language training set. 

Ahora tengo mucha demanda de doblaje en español, así que espero que alguien añada el soporte del set de formación en español.

**Comment by babysor** [comment]
I was planning to support multi-language. If you were familiar with python, I could show you how you may try to support by changing couple files in this repo.

**Comment by EkinUstundag** [comment]
> I was planning to support multi-language. If you were familiar with python, I could show you how you may try to support by changing couple files in this repo.

Hi. My friend and I are trying to do in Turkish. Could you help us a little?

**Comment by babysor** [comment]
> > I was planning to support multi-language. If you were familiar with python, I could show you how you may try to support by changing couple files in this repo.
> 
> Hi. My friend and I are trying to do in Turkish. Could you help us a little?

You could email me and setup a topic thread

**Comment by EkinUstundag** [comment]
> > > I was planning to support multi-language. If you were familiar with python, I could show you how you may try to support by changing couple files in this repo.
> > 
> > 
> > Hi. My friend and I are trying to do in Turkish. Could you help us a little?
> 
> You could email me and setup a topic thread

I sent an email titled "Help for Turkish Voice Cloning". I'll be glad if you could help us.

**Comment by babysor** [comment]
> > > > I was planning to support multi-language. If you were familiar with python, I could show you how you may try to support by changing couple files in this repo.
> > > 
> > > 
> > > Hi. My friend and I are trying to do in Turkish. Could you help us a little?
> > 
> > 
> > You could email me and setup a topic thread
> 
> I sent an email titled "Help for Turkish Voice Cloning". I'll be glad if you could help us.

Did u receive my reply?
