### ISSUE TITLE
训练模型时这个问题怎么办？？疑似N卡内存不够。 CUDA out of memory. Tried to allocate 122.00 MiB (GPU 0; 4.00 GiB total capacity; 3.15 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch

### ISSUE THREAD

**Issue by pzhyyd** [babysor/MockingBird#669]
**Summary[问题简述（一句话）]**
训练模型时这个问题怎么办？？疑似N卡内存不够。 
CUDA out of memory. Tried to allocate 122.00 MiB (GPU 0; 4.00 GiB total capacity; 3.15 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch

**Env & To Reproduce[复现与环境]**
python3.9、NVIDIA GeForce GTX 1050Ti（4GB）

**Screenshots[截图（如有）]**
![image](https://user-images.githubusercontent.com/44706193/180253285-302435e2-2996-47b5-befb-044b723ef8fd.png)
![image](https://user-images.githubusercontent.com/44706193/180253371-a666d28d-e506-4c57-a397-78126c8950ae.png)

**Comment by pzhyyd** [comment]
运行起来N卡的状态。
![image](https://user-images.githubusercontent.com/44706193/180254436-02d42f82-ecd0-41bd-8dfa-114b59455240.png)

**Comment by pzhyyd** [comment]
![image](https://user-images.githubusercontent.com/44706193/180254576-ef035531-7eec-4126-aace-b50eed5a43e5.png)

**Comment by VERT2022** [comment]
訓練模型顯存不足
訓練合成器時：將 synthesizer/hparams.py中的batch_size參數調小

//調整前
tts_schedule = [(2,  1e-3,  20_000,  12),   # Progressive training schedule
                (2,  5e-4,  40_000,  12),   # (r, lr, step, batch_size)
                (2,  2e-4,  80_000,  12),   #
                (2,  1e-4, 160_000,  12),   # r = reduction factor (# of mel frames
                (2,  3e-5, 320_000,  12),   #     synthesized for each decoder iteration)
                (2,  1e-5, 640_000,  12)],  # lr = learning rate
//調整後
tts_schedule = [(2,  1e-3,  20_000,  8),   # Progressive training schedule
                (2,  5e-4,  40_000,  8),   # (r, lr, step, batch_size)
                (2,  2e-4,  80_000,  8),   #
                (2,  1e-4, 160_000,  8),   # r = reduction factor (# of mel frames
                (2,  3e-5, 320_000,  8),   #     synthesized for each decoder iteration)
                (2,  1e-5, 640_000,  8)],  # lr = learning rate

**Comment by pzhyyd** [comment]
> 
是调整这个位置么

![image](https://user-images.githubusercontent.com/44706193/180370623-923633aa-dfeb-4ebe-a60c-44917668a619.png)

还是这里呢
![image](https://user-images.githubusercontent.com/44706193/180370755-e3c63fee-9058-4d0e-ac5e-acd3bec10fd3.png)

**Comment by pzhyyd** [comment]
> 

![image](https://user-images.githubusercontent.com/44706193/180370914-8b17ae64-0d49-4c3f-b1eb-2aa67da432b3.png)
gai'wei改为这样可以么

**Comment by babysor** [comment]
差不多

**Comment by pzhyyd** [comment]
> 訓練模型顯存不足 訓練合成器時：將 synthesizer/hparams.py中的batch_size參數調小
> 
> //調整前 tts_schedule = [(2, 1e-3, 20_000, 12), # Progressive training schedule (2, 5e-4, 40_000, 12), # (r, lr, step, batch_size) (2, 2e-4, 80_000, 12), # (2, 1e-4, 160_000, 12), # r = reduction factor (# of mel frames (2, 3e-5, 320_000, 12), # synthesized for each decoder iteration) (2, 1e-5, 640_000, 12)], # lr = learning rate //調整後 tts_schedule = [(2, 1e-3, 20_000, 8), # Progressive training schedule (2, 5e-4, 40_000, 8), # (r, lr, step, batch_size) (2, 2e-4, 80_000, 8), # (2, 1e-4, 160_000, 8), # r = reduction factor (# of mel frames (2, 3e-5, 320_000, 8), # synthesized for each decoder iteration) (2, 1e-5, 640_000, 8)], # lr = learning rate

感谢指导，已成功开始训练了

**Comment by z1139147357** [comment]
> 

我已经把batch_size调整到4了，还是出现同样的问题，唉。。。

**Comment by by517840374** [comment]
> 

你是不是没装cuda?我没装之前也是这样，或者更换一下pytorch 版本
