### ISSUE TITLE
开始使用CPU训练 现在该如何改用GPU训练 尝试各种办法都不行

### ISSUE THREAD

**Issue by b95595** [babysor/MockingBird#670]
Using model: Tacotron
Using device: cpu

**Comment by VERT2022** [comment]
安装gpu版本的pytorch，电脑系统的cuda版本要和pytorch里面的一致
python里面执行torch.cuda.is_available()后，结果为True就可以了，建议安装pytorch 1.11.0 + cuda 11.5
