### ISSUE TITLE
运行python demo_toolbox.py -d .\samples报错

### ISSUE THREAD

**Issue by hengshizhi** [babysor/MockingBird#694]
运行python demo_toolbox.py -d .\samples报错
代码版本：最新
![QQ图片20220802224227](https://user-images.githubusercontent.com/87295882/182505836-4571425e-3c7d-4bbf-bdae-317ca2b3055c.png)

**Comment by AlanBook** [comment]
我也是这个错误。
而且之前在运行pip install -r requirements.txt安装其他库的时候，pyworld无法安装，
报错为
【pip】解决ERROR: Could not build wheels for pyworld which use PEP 517 and cannot be installed directly

**Comment by hengshizhi** [comment]
你好。已收到你的邮件，我会在尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by AlanBook** [comment]
谢谢您的来信，期待您的下次来信~我会阅读您的来信，请放心~

**Comment by AlanBook** [comment]
谢谢您的来信，期待您的下次来信~我会阅读您的来信，请放心~

**Comment by hengshizhi** [comment]
你好。已收到你的邮件，我会在尽快处理。————————————这是来自QQ邮箱的自动回复邮件。
