### ISSUE TITLE
在使用Anaconda的情况下，不能打开程序，提示缺少大量module。

### ISSUE THREAD

**Issue by hqysc** [babysor/MockingBird#704]
作者大大您好，我在使用Anaconda的情况下启动demo_toolbox.py，出现无法启动问题，报错缺少大量模块。
在安装环境时完全按照文档流程，不知该如何解决，向您请教一下。

![QQ截图20220810202715](https://user-images.githubusercontent.com/32790987/183903099-05b484df-26a3-4a59-8a3b-de034b500069.png)

**Comment by AlanBook** [comment]
在pip install -r requirements.txt那一步不能报错，文件里面的模块需要正确安装
再试试这个指令

**Comment by hqysc** [comment]
解决了，是pywin32版本的问题，304无法打开，降级300后可以正常打开程序，用pip install pywin32==300解决
