### ISSUE TITLE
plz provide google drive link for pretrained model

### ISSUE THREAD

**Issue by Michaelwhite34** [babysor/MockingBird#73]
the baidu netdisk download is terrible for ordinary users.

**Comment by miven** [comment]
You can try this
https://github.com/miven/Realtime-Voice-Clone-Chinese/releases/tag/0.1

**Comment by Michaelwhite34** [comment]
> You can try this
> https://github.com/miven/Realtime-Voice-Clone-Chinese/releases/tag/0.1

This is life savior,I have a questiion tho.Is the pretrained model folder structure the same as the original repo.i.e. create a folder name saved_models and a folder pretrained,then put the pt file in it.

**Comment by Michaelwhite34** [comment]
I get it now,it will search subfolders..After opening the GUI,I get the warning "you did not pass a root directory for datasets as argument"
