### ISSUE TITLE
数据预处理时检测不出数据集

### ISSUE THREAD

**Issue by zzhbb2002** [babysor/MockingBird#746]
各位大佬为什么程序检测不出来train文件夹下的WAV文件啊
![image](https://user-images.githubusercontent.com/114280102/192084054-f35830ea-21f5-4f9f-a072-06e6a059495f.png)
![image](https://user-images.githubusercontent.com/114280102/192084067-1ffa205b-856a-46f6-a8c3-26f7868bfe13.png)

**Comment by babysor** [comment]
名字试着去掉全字符括号试试

**Comment by zzhbb2002** [comment]
问题解决了，是TRANS.txt内容格式问题
