### ISSUE TITLE
执行命令python pre.py D:\video-srt-gui-ffm -d aidatatang_200zh 预处理报错 用的是GPU

### ISSUE THREAD

**Issue by mochaYJ12138** [babysor/MockingBird#754]
D:\video-srt-gui-ffm\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|██████████████████████████████████████████████████████████| 66/66 [00:01<00:00, 35.62speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "D:\video-srt-gui-ffm\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "D:\video-srt-gui-ffm\MockingBird-main\synthesizer\preprocess.py", line 88, in preprocess_dataset
    **print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
**ValueError: max() arg is an empty sequence****

**Comment by wshbr1314** [comment]
你好，能不能给一个截图看看，具体音频是什么？最后文件夹是什么样子的，我也是这个问题，麻烦了
