### ISSUE TITLE
有没有在macbook上成功的同学，我配置完成后没有报错信息，但是一直是沙沙的声音，不清楚是什么原因

### ISSUE THREAD

**Issue by zhuzhihui** [babysor/MockingBird#760]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型
mac OS Monterey 12.5
Python 3.9.2 

**Screensho

<img width="1300" alt="截屏2022-10-07 00 26 04" src="https://user-images.githubusercontent.com/16750537/194367418-49c0c63b-b7d5-4d76-9738-4340db7c0325.png">
2524e6d77.png">
<img width="1669" alt="截屏2022-10-07 00 27 14" src="https://user-images.githubusercontent.com/16750537/194367712-1d2b7bd2-5704-4aa8-9d25-dcb1b41d9866.png">

ts[截图（如有）]**
If applicable, add screenshots to help

**Comment by babysor** [comment]
模型没放对，synthesizer怎么会选一个wavernn呢
