### ISSUE TITLE
在win10.64下多次打开并移动MockingBird-main文件夹后出现ModuleNotFoundError: No module named 'synthesizer.models.tacotron

### ISSUE THREAD

**Issue by KauBuo** [babysor/MockingBird#769]
打开过一次工具箱后按键全是灰色，于是关闭。
并将MockingBird-main文件夹从d盘的desktop中移动到d盘根目录，再次打开后出现
ModuleNotFoundError: No module named 'synthesizer.models.tacotron‘

![MEFJ{{3)69`R9)@F2GUZ90K](https://user-images.githubusercontent.com/116176798/196700882-ee07e0d6-9454-42dd-b306-f81fe460867c.png)
![K077_JWZZ@V0$FXV1E0NU_8](https://user-images.githubusercontent.com/116176798/196701146-d616b657-d2bc-4f2c-9a5d-3b4ffefea217.png)

**Comment by babysor** [comment]
windows cmd的特点，不能这样跨盘调用
