### ISSUE TITLE
encoder加载速度很慢以及输出是杂音的问题

### ISSUE THREAD

**Issue by 576272658** [babysor/MockingBird#77]
请问一下各位大佬，我是按照Quick Start (Newbie)一步一步来的，以前并没有怎么接触过python，目前安装的是python3.9+anaconda3.pytorch版本是1.9 cuda10.2，显卡3070ti，cuda驱动都安好了
import torch;, 回车以后没有反应， torch.cuda.is_available() 以后会出来一个True
ffmpeg安装的是ffmpeg-n4.4-83-gb1f2d203c0-win64-gpl-4.4.zip这个版本

运行pip install -r requirements.txt 来安装剩余的必要包。
安装 webrtcvad 用 pip install webrtcvad-wheels。
这两步都没有错误提示

模型使用的miven大佬的包
python demo_toolbox.py -d .\samples启动

![微信图片_20210908010252](https://user-images.githubusercontent.com/90212433/132383603-ac86034f-ca29-4533-8baa-fc372020a371.png)

然后可以打开toolbox

但是在点击Record录音以后就会卡死
![微信图片_20210908010256](https://user-images.githubusercontent.com/90212433/132383825-4b0c68e1-e3d9-4c18-83cb-83d127c1aed1.png)

经过测试等待发现要将近一个小时才能加载encoder
![微信图片_20210908010529](https://user-images.githubusercontent.com/90212433/132383903-da10165a-4dfd-481f-8a48-099ee4800dc5.png)
这是第一个问题

第二个问题就是加载好以后可以正常录音使用，但是生成的声音不管输入文字还是拼音播放出来的都是杂音
![微信截图_20210908010647](https://user-images.githubusercontent.com/90212433/132384029-efb71b09-5a15-495b-b997-749e18947584.png)

请问一下应该怎么解决呢

文件中：synthesizer/utils/symbols.py 第11行的symbols 改为：
_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '

这个解决方法已经试过了但是还是杂音

**Comment by 576272658** [comment]
经过研究，发现卸载pytorch1.9 cuda10.2版本，重新安装pytorch cpu版本以后加载encoder速度正常，生成的声音也不是杂音了。请问一下是程序对于cuda的支持有问题吗还是我本地cuda配置有问题

**Comment by 576272658** [comment]
又测试了一下，新建虚拟环境，安装CUDA11.4，pytorch 1.90版本好像是无法使用，pytorch更新到最新每日版以后可以正常使用，就是加载速度比cpu慢一点，大概需要2-3秒，cpu版本的加载速度只需要50ms。生成声音正常
估计是cuda10.2版本有一些bug

**Comment by babysor** [comment]
听着像你的显卡驱动也有问题，试着升级一下？ @576272658

**Comment by 576272658** [comment]
> 听着像你的显卡驱动也有问题，试着升级一下？ @576272658

驱动是最新版的，感觉可能是cuda10.2对3070ti支持还不太好
