### ISSUE TITLE
关于弃用百度网盘的提案

### ISSUE THREAD

**Issue by legiorange** [babysor/MockingBird#78]
因为限制
我强烈推荐训练后的数据集丢到 ‘Google网盘’ 、‘Dropbox’、及‘MEGA’ 甚至基于 IPFS的存储服务中.
也推荐采用 Resilio Sync来同步数据集

这样方便广大的国内外开发人员训练更好的模型或者基于模型进行实验

**Comment by babysor** [comment]
这里是指预训练模型吧？数据集的话应该公开可以下载

**Comment by legiorange** [comment]
> 这里是指预训练模型吧？数据集的话应该公开可以下载

对。
百度网盘。。对国外用户不是很友好。

**Comment by babysor** [comment]
将补充google 云盘+百度云盘的模型，可以关注一下今天更新的
