### ISSUE TITLE
UnicodeEncodeError: 'cp950' codec can't encode character '\u2f24' in position 153: illegal multibyte sequence

### ISSUE THREAD

**Issue by XiuChen-Liu** [babysor/MockingBird#79]
在執行 `python vocoder_preprocess.py <datasets_root>` 時遇到的錯誤，上網查詢一下發現是編碼問題，請問我可以更改程式裡的哪部分代碼去解決這個問題呢?
![WeChat 圖片_20210909001330](https://user-images.githubusercontent.com/55180847/132545963-b902fb19-a6f3-417a-8079-b6b0d83e1654.png)

**Comment by XiuChen-Liu** [comment]
問題已經解決，透過以下方法：
1. 查看 `yourdataset\SV2TTS\vocoder\synthesized.txt` 執行時停止在哪一行
2. 根據上述查詢到的去尋找 `yourdataset\SV2TTS\synthesizer\train.txt` 中相同行數的資料
3. 將沒轉換好的字手動轉換 （我這邊是「大」這個字沒轉好，所以改完後用 `ctal+F`搜尋其他「大」字一併做更改）

這是我的解決方法，我將關閉這個 issue

**Comment by babysor** [comment]
> 問題已經解決，透過以下方法：
> 
> 1. 查看 `yourdataset\SV2TTS\vocoder\synthesized.txt` 執行時停止在哪一行
> 2. 根據上述查詢到的去尋找 `yourdataset\SV2TTS\synthesizer\train.txt` 中相同行數的資料
> 3. 將沒轉換好的字手動轉換 （我這邊是「大」這個字沒轉好，所以改完後用 `ctal+F`搜尋其他「大」字一併做更改）
> 
> 這是我的解決方法，我將關閉這個 issue

是因为用了繁体字吗？

**Comment by XiuChen-Liu** [comment]
> 是因为用了繁体字吗？

感覺不是，只有其中兩筆資料的「大」字在預處理時並沒有轉換好，可能是格式問題
但非常奇怪，這兩筆資料中只有「大」字沒被轉換，其他字都有成功轉換
