### ISSUE TITLE
合成器训练的loss一直在0.49附近震荡，无法降低

### ISSUE THREAD

**Issue by ngbruce** [babysor/MockingBird#799]
你好，想请教一下，使用了 aidatatang_200zh，aishell3，magicdata 这三个数据集合并在一起训练合成器，大概从50k步开始，运行到123k步，loss值都在0.49附近震荡，没法进一步收敛。
请指教一下方向，应该如何处理。
另外，请问有没有可供交流的微信群或QQ群？谢谢！
![屏幕截图 2022-12-09 200136](https://user-images.githubusercontent.com/68752507/206699187-21942172-7f49-4759-9e08-494c69dcaed2.png)
![屏幕截图 2022-12-09 200207](https://user-images.githubusercontent.com/68752507/206699204-a8ed530f-08cf-4d9f-8a0e-d98d78fc0773.png)

**Comment by jerrytt** [comment]
steps是不是有点少 我觉得大概训练到600k 的底子为基础。
然后针对不同的 声音自己做训练集 才能达到说的过去的效果吧。
我目前用的 issue里不记得谁分享的650k 模型。基础上 对自己想要的声音做训练。 之后效果 感觉 真的不错。
嘿嘿。

**Comment by ngbruce** [comment]
> steps是不是有点少 我觉得大概训练到600k 的底子为基础。 然后针对不同的 声音自己做训练集 才能达到说的过去的效果吧。 我目前用的 issue里不记得谁分享的650k 模型。基础上 对自己想要的声音做训练。 之后效果 感觉 真的不错。 嘿嘿。

感觉有点问题，作者在readme里说他自己训练在50k步之后就降到0.4以下，B站有位up主分享的36k步的模型，用起来效果比我的123k步的明显好。
你说的650k的模型，能否放网盘分享一下？ :)

**Comment by jerrytt** [comment]
> > steps是不是有点少 我觉得大概训练到600k 的底子为基础。 然后针对不同的 声音自己做训练集 才能达到说的过去的效果吧。 我目前用的 issue里不记得谁分享的650k 模型。基础上 对自己想要的声音做训练。 之后效果 感觉 真的不错。 嘿嘿。
> 
> 感觉有点问题，作者在readme里说他自己训练在50k步之后就降到0.4以下，B站有位up主分享的36k步的模型，用起来效果比我的123k步的明显好。 你说的650k的模型，能否放网盘分享一下？ :)

链接: https://pan.baidu.com/s/1pxyvk94ftgnxdZwGZNGOGQ 提取码: ruje

**Comment by ngbruce** [comment]
> > > steps是不是有点少 我觉得大概训练到600k 的底子为基础。 然后针对不同的 声音自己做训练集 才能达到说的过去的效果吧。 我目前用的 issue里不记得谁分享的650k 模型。基础上 对自己想要的声音做训练。 之后效果 感觉 真的不错。 嘿嘿。
> > 
> > 
> > 感觉有点问题，作者在readme里说他自己训练在50k步之后就降到0.4以下，B站有位up主分享的36k步的模型，用起来效果比我的123k步的明显好。 你说的650k的模型，能否放网盘分享一下？ :)
> 
> 链接: https://pan.baidu.com/s/1pxyvk94ftgnxdZwGZNGOGQ 提取码: ruje

好的，谢谢你！ 另外请问有没有交流群之类的，求带 :)
