### ISSUE TITLE
这是Real-Time-Voice-Cloning项目的复刻版?

### ISSUE THREAD

**Issue by FatTigerWang** [babysor/MockingBird#82]
你这个项目与[Real-Time-Voice-Cloning](https://github.com/CorentinJ/Real-Time-Voice-Cloning)项目的区别是? 看起来是它的复刻版.

**Comment by FatTigerWang** [comment]
从原始库抄过来也不fork, 也不说明出处, 还起了个名字 MockingBird, 建议改为 CopyBird 或者 叫 ChineseLocalizationBird.

**Comment by babysor** [comment]
> 从原始库抄过来也不fork, 也不说明出处, 还起了个名字 MockingBird, 建议改为 CopyBird 或者 叫 ChineseLocalizationBird.

所有Readme都注明了，也说明了区别。
