### ISSUE TITLE
报错：pre.py: error: the following arguments are required: datasets_root

### ISSUE THREAD

**Issue by SacredDreams** [babysor/MockingBird#831]
请大神指点一下这是怎么回事：pre.py: error: the following arguments are required: datasets_root
翻译给的：需要以下参数：datasets_root
我执行的命令：pre.py D:\Data\Python -d aidatatang_200zh -n 7

**Comment by SacredDreams** [comment]
我自己解决了

**Comment by gaoyiyao** [comment]
请问是怎么解决的
