### ISSUE TITLE
執行demo_toolbox.py Error in sys.excepthook 沒有其它訊息

### ISSUE THREAD

**Issue by nethawkChen** [babysor/MockingBird#844]
**Summary[问题简述（一句话）]**
python demo_toolbox.py -d .\samples 畫面閃爍一下就消失

Arguments:
    datasets_root:          samples
    vc_mode:                False
    enc_models_dir:         data\ckpt\encoder
    syn_models_dir:         data\ckpt\synthesizer
    voc_models_dir:         data\ckpt\vocoder
    extractor_models_dir:   data\ckpt\ppg_extractor
    convertor_models_dir:   data\ckpt\ppg2mel
    cpu:                    False
    seed:                   None
    no_mp3_support:         False

Error in sys.excepthook:

Original exception was:

**Env & To Reproduce[复现与环境]**
Windows 11
Python 3.9.12

**Comment by RubickDong** [comment]
遇到了同样的问题

**Comment by nethawkChen** [comment]
我在 Windows 10 同樣的安裝步驟是成功的﹐執行 demo_toolbox.py 也可以正常開啟畫面
是否不支援 Windows 11 ？ 還是需要額外的什麼設定？

**Comment by DayJun** [comment]
toolbox/ui.py中282行的print中的file=sys.stderr删掉即可

**Comment by nethawkChen** [comment]
> toolbox/ui.py中282行的print中的file=sys.stderr删掉即可

在 Win 11 環境這麼做﹐確實畫面正常開啟了﹐謝謝

**Comment by NanaZZZ0104** [comment]
> toolbox/ui.py中282行的print中的file=sys.stderr删掉即可

我的这个在第284行，不过删了依然没什么用。
