### ISSUE TITLE
win11启动\demo_toolbox.py 报错 Error in sys.excepthook: 按照#844修改依旧

### ISSUE THREAD

**Issue by kiveno** [babysor/MockingBird#847]
win11启动\demo_toolbox.py 报错 Error in sys.excepthook: 按照#844修改依旧

![image](https://user-images.githubusercontent.com/20217142/223896418-f1a80c0e-d97e-4636-9c76-5fb9d6e2ad1b.png)
![image](https://user-images.githubusercontent.com/20217142/223896526-cf4b809e-4179-4b93-8ad8-05c273604e4c.png)

**Comment by kiveno** [comment]
https://github.com/babysor/MockingBird/issues/844

**Comment by kiveno** [comment]
> win11启动\demo_toolbox.py 报错 Error in sys.excepthook: 按照#844修改依旧
> 
> ![image](https://user-images.githubusercontent.com/20217142/223896418-f1a80c0e-d97e-4636-9c76-5fb9d6e2ad1b.png) ![image](https://user-images.githubusercontent.com/20217142/223896526-cf4b809e-4179-4b93-8ad8-05c273604e4c.png)

**Comment by kiveno** [comment]
模型文件放错位置了

**Comment by bubbl000** [comment]
这个需要怎么解决，我出现的问题跟你的一样，你说的模型文件放错位置 具体需要怎么操作 好难呀
