### ISSUE TITLE
使用AISHELL3训练合成器，最终不能正确读出文本框中的内容，而是隔一个合成一个，这是什么问题？

### ISSUE THREAD

**Issue by Rita-ritally** [babysor/MockingBird#86]
使用之前的代码时一直运行没有问题。使用AISHELL3自己训练了合成器，使用自己的模型时出现了不能正确读出文本框里面的文字的问题。例如输入“欢迎使用工具箱”只能合成“迎 用 具箱”的mel谱。希望尽快得到答复，谢谢～

**Comment by Rita-ritally** [comment]
`Loaded encoder "pretrained.pt" trained to step 1564501
Synthesizer using device: cuda
Trainable Parameters: 30.875M
Traceback (most recent call last):
  File "F:\cuc\2021\Realtime-tacotron-Chinese\toolbox\__init__.py", line 236, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "F:\cuc\2021\Realtime-tacotron-Chinese\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "F:\cuc\2021\Realtime-tacotron-Chinese\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "F:\cuc\2021\Realtime-tacotron-Chinese\synthesizer\models\tacotron.py", line 497, in load
    self.load_state_dict(checkpoint["model_state"])
  File "C:\Users\Rita\Anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]). `

**Comment by Rita-ritally** [comment]
查看了SV2TTS/synthesizer中的train.txt文件，发现在预处理数据集时将拼音转化成了下图中的形式。
每个字的拼音都是重复了一个，所以导致最终测试时隔一个合成一个的问题。请问这个要如何解决？
<img width="1604" alt="E171392F-A59C-42E9-BDDB-2BF7C81ACD38" src="https://user-images.githubusercontent.com/45085467/133578815-97450072-2bde-409f-90f2-b976a4ee4a70.png">

**Comment by Rita-ritally** [comment]
解决了！！！由于aishell3的数据预处理延用的是aidatatang的，所以导致读取和转录的时候每个字的拼音出现了两次！在preprocess_speaker.py中新增AISHELL3的预处理函数，并将res列表中的数据隔一个读取一个即可～
<img width="585" alt="571D848E-23C7-4D95-A0CA-5B6034026DC0" src="https://user-images.githubusercontent.com/45085467/133608437-d608863e-f801-4980-b537-01ee9de88ae5.png">

**Comment by Rita-ritally** [comment]
作者使用aishell3数据集时是否出现这个问题？

**Comment by babysor** [comment]
> 作者使用aishell3数据集时是否出现这个问题？
你用的是我那个biaobei branch吗

**Comment by Rita-ritally** [comment]
> 作者使用aishell3数据集时是否出现这个问题？
> 你用的是我那个biaobei branch吗

没有选择分支诶，我看数据那里都是使用的general，AISHELL的数据集要用标贝的branch处理是嘛～

**Comment by babysor** [comment]
> > 作者使用aishell3数据集时是否出现这个问题？
> > 你用的是我那个biaobei branch吗
> 
> 没有选择分支诶，我看数据那里都是使用的general，AISHELL的数据集要用标贝的branch处理是嘛～

不对不对，我看错了，你用aishell就正常用aishell，我处理一下代码

**Comment by babysor** [comment]
最新代码已经修复。 https://github.com/babysor/MockingBird/commit/4178416385d88cc17516a12496130ffe6bed0d98
