### ISSUE TITLE
colab web ui使用指南

### ISSUE THREAD

**Issue by starkbtc** [babysor/MockingBird#862]
1.安装pyngrok 
```
!pip install pyngrok 
```
2.注册pyngrok 并配置Authtoken
```
!ngrok authtoken  <your token>
```
3.启动pyngrok
```
from pyngrok import ngrok

# Setup a tunnel to the streamlit port 2023
ngrok.kill()

public_url = ngrok.connect(2023)
print(public_url)
```
4.修改端口号为2023并启动streamlit，然后访问上一步pyngrok的地址就可以使用了

也可以直接在colab打开这个文件https://github.com/stark-eth/MockingBird-colab/blob/main/mockingbird.ipynb

**Comment by LmYjQ** [comment]
遇到了报错求助😭
<img width="1143" alt="image" src="https://github.com/babysor/MockingBird/assets/12581433/2fce544a-df3a-440f-8b84-78d2a6926c2f">


 ERROR: Could not build wheels for numpy, gevent, which is required to install pyproject.toml-based projects
