### ISSUE TITLE
Exception: Model folder data\ckpt\synthesizer doesn't exist. 请将模型文件位置移动到上述位置中进行重试！

### ISSUE THREAD

**Issue by netjune** [babysor/MockingBird#873]
看了好几个教程, 都没提到这个,

**Comment by babysor** [comment]
模型位置发生变化，要移动一下

**Comment by netjune** [comment]
昨天试出来了, 创建了文件夹`data\ckpt\synthesizer`, 然后又下载了几个推荐的别人训练好的数据, 放在该文件夹里. 好几个数据运行都报错, 提示数据不匹配什么的, 最后发现只有这个能用: `pretrained-11-7-21_75k.pt`.

我安装的是main分支最新版.

初步测试了下, 生成的音频效果不太理想, 再摸索摸索.

**Comment by jiangfd** [comment]
> 昨天试出来了, 创建了文件夹`data\ckpt\synthesizer`, 然后又下载了几个推荐的别人训练好的数据, 放在该文件夹里. 好几个数据运行都报错, 提示数据不匹配什么的, 最后发现只有这个能用: `pretrained-11-7-21_75k.pt`.
> 
> 我安装的是main分支最新版.
> 
> 初步测试了下, 生成的音频效果不太理想, 再摸索摸索.

pretrained-11-7-21_75k.pt 这个模型还有没有，哪里可以下载，求教
