### ISSUE TITLE
运行pip install -r requirements.txt的时候提示未能找到该文件

### ISSUE THREAD

**Issue by Taebost** [babysor/MockingBird#88]
如题，在运行这一命令时出现如下错误
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by babysor** [comment]
你所在路径是在root吗

**Comment by Taebost** [comment]
> 
> 
> 你所在路径是在root吗

如果您指的是打开Anaconda后的第一个目录的话是这样的。
请问应该进入哪个路径才对呢？

**Comment by babysor** [comment]
> > 你所在路径是在root吗
> 
> 如果您指的是打开Anaconda后的第一个目录的话是这样的。
> 请问应该进入哪个路径才对呢？

代码所在的目录
