### ISSUE TITLE
requirements里面的monotonic-align==0.0.3安装失败

### ISSUE THREAD

**Issue by xiaojunyang1** [babysor/MockingBird#884]
![image](https://user-images.githubusercontent.com/32406611/233461435-4e22eb0d-017f-424c-8de0-7765685b3f2b.png)

ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement monotonic-align==0.0.3 (from versions: 1.0.0)
ERROR: No matching distribution found for monotonic-align==0.0.3
换了好几个镜像 都不行 暂时没找到啥原因

**Comment by xiaojunyang1** [comment]
尝试安装这个 有报这个错误
![image](https://user-images.githubusercontent.com/32406611/233461805-28075c95-839c-42b2-81fd-6df485fd7dea.png)

**Comment by zhw0213** [comment]
去掉后面版本号重新安装即可

**Comment by xiaojunyang1** [comment]
> 去掉后面版本号重新安装即可

第二张截图就是去掉版本号的安装失败截图。这是啥问题呀？大佬帮忙看一下呀。谢谢。

**Comment by laishujie** [comment]
> 

下载一个Visual Studio ，打开后把c++桌面程序套件安装了即可

**Comment by laishujie** [comment]
> > 去掉后面版本号重新安装即可
> 
> 第二张截图就是去掉版本号的安装失败截图。这是啥问题呀？大佬帮忙看一下呀。谢谢。

下载一个 Visual Studio ,把c++桌面程序套件装了即可

**Comment by xiaojunyang1** [comment]
> 

嗯 那么大一行提示 给忽略了  昨晚发现了  。还是谢谢你呀

**Comment by 111zhangsan** [comment]
问题是怎么解决的呢？哪里有提示

**Comment by 111zhangsan** [comment]
![monotonic-align==0 0 3版本问题](https://user-images.githubusercontent.com/132746201/236614704-00a9b44e-5e76-4891-9066-90f0af088ec0.PNG)

**Comment by xiaojunyang1** [comment]
下载一个 Visual Studio ,把c++桌面程序套件装了即可



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [babysor/MockingBird] requirements里面的monotonic-align==0.0.3安装失败 (Issue #884)




 
问题是怎么解决的呢？哪里有提示

**Comment by 111zhangsan** [comment]
![image](https://user-images.githubusercontent.com/132746201/236617096-252900f9-bb6b-40c4-9ae6-2e771e5ee1a3.png)

**Comment by 111zhangsan** [comment]
是五个c++和Python六个全选吗？

**Comment by xiaojunyang1** [comment]
我也忘记了你装一个 再安装库试一下&nbsp; 最后不行&nbsp; 能装尽装吧&nbsp; 😂😂😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 下午5:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [babysor/MockingBird] requirements里面的monotonic-align==0.0.3安装失败 (Issue #884)




 
是五个c++和Python六个全选吗？

**Comment by 111zhangsan** [comment]
谢谢

**Comment by 111zhangsan** [comment]
安装了之后还是无法运行，同样的错误，还有什么步骤要注意的吗？

**Comment by 111zhangsan** [comment]
![monotonic-align==0 0 3版本问题](https://user-images.githubusercontent.com/132746201/236626203-b8c16ffe-1a7b-428a-a090-305b852f209a.PNG)

**Comment by xiaojunyang1** [comment]
我把那个安装之后就可以了&nbsp; 不报错了&nbsp; &nbsp;你是不是和我的报错原因不一样啊&nbsp; 你详细对比一下我发的报错截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 晚上9:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [babysor/MockingBird] requirements里面的monotonic-align==0.0.3安装失败 (Issue #884)




 
安装了之后还是无法运行，同样的错误，还有什么步骤要注意的吗？

**Comment by 111zhangsan** [comment]
pip install -r E:\布谷鸟声音克隆\MockingBird-main\requirements.txt -i https://pypi.douban.com/simple/镜像源是这个

**Comment by 111zhangsan** [comment]
![image](https://user-images.githubusercontent.com/132746201/236626280-c56e009c-bd98-4df7-8942-183658da3076.png)

**Comment by 111zhangsan** [comment]
Python 3.8

**Comment by 111zhangsan** [comment]
你有镜像源吗？我卸载vs了再安装试一下。

**Comment by xiaojunyang1** [comment]
我用的python3.9&nbsp; 清华 阿里的镜像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 晚上9:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [babysor/MockingBird] requirements里面的monotonic-align==0.0.3安装失败 (Issue #884)




 
pip install -r E:\布谷鸟声音克隆\MockingBird-main\requirements.txt -i https://pypi.douban.com/simple/镜像源是这个

**Comment by xiaojunyang1** [comment]
百度自己找一下&nbsp; &nbsp;在外面出差不方便



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 晚上9:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [babysor/MockingBird] requirements里面的monotonic-align==0.0.3安装失败 (Issue #884)




 
你有镜像源吗？我卸载vs了再安装试一下。

**Comment by zhw0213** [comment]
我是直接把后面版本信息删除掉安装的
已经跑通，不过效果不太理想










在 2023-05-06 17:05:37，"111zhangsan" ***@***.***> 写道：

问题是怎么解决的呢？哪里有提示

**Comment by zhw0213** [comment]
issue1:tools_demo闪退
win11系统，找到解决方案了， 1.pip install PyQt5==5.15.4 2.pip install sounddevice==0.4.3


issue2:报错信息如下： RuntimeError: Error(s) in loading state_dict for Tacotron: size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]). size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]). size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]). size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048])
solve:
使用main分支下载的zip文件,解压配置好预训练文件后运行出现的问题包括 : 2秒杂音, 无法编码(在98%后卡住)
如果你出现的问题和我一样,可以尝试和我一样步骤
首先是这个 #209 将文件 synthesizer/hparams.py 中的: use_gst 和 use_ser_for_gst 均设置为 False
然后是这个 #37 将文件synthesizer/utils/symbols.py 中的
_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? '
改为
_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '
由于我是直接使用 python .\demo_toolbox.py --cpu 命令直接运行的 所以我没有测试 #242 这个是否有效













在 2023-05-06 21:08:02，"111zhangsan" ***@***.***> 写道：

安装了之后还是无法运行，同样的错误，还有什么步骤要注意的吗？

**Comment by qq754667422** [comment]
![Snipaste_2024-06-11_22-17-23](https://github.com/babysor/MockingBird/assets/33661177/9478b5ef-e6ab-4c83-a6bd-85b2b47062b4)
这个是什么原因百度了半天没有找到结果
