### ISSUE TITLE
求助！启动时候失败

### ISSUE THREAD

**Issue by Maplexj** [babysor/MockingBird#889]
OSError: [WinError 126] 找不到指定的模块。Error loading "F:\python\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
![搜狗截图23年05月03日0833_1](https://user-images.githubusercontent.com/132413664/235813519-35f0002d-ceb6-46c6-b327-617782b1890c.png)

**Comment by Maplexj** [comment]
没有在anaconda中运行，直接windows环境运行的

**Comment by weishaogeng512** [comment]
把torch卸载了重新装
