### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-13: character maps to <undefined>

### ISSUE THREAD

**Issue by Udaroth** [babysor/MockingBird#90]
![image](https://user-images.githubusercontent.com/56278360/133972455-1e26b379-7c12-4f70-b5a0-c0d24e28fa60.png)

您好，请问这个问题如何解决？貌似卡在Synthesizer的模型那一步，可是我两个模型都试了都是同一个问题？

**Comment by babysor** [comment]
mp3把名字改成纯字母的试试？

**Comment by Udaroth** [comment]
![image](https://user-images.githubusercontent.com/56278360/133997875-16d14392-45f7-49b4-be13-0470f6ae3706.png)
![image](https://user-images.githubusercontent.com/56278360/133998027-257f9194-d66a-4b6a-ab97-17a4c601d42b.png)


好的，我试了一下我用另外一个文件用数字名字的也遇见同样的问题


> mp3把名字改成纯字母的试试？

**Comment by Udaroth** [comment]
> mp3把名字改成纯字母的试试？

![image](https://user-images.githubusercontent.com/56278360/133998185-89ef7f42-4cdd-47b5-a0b2-ec172d866c59.png)
![image](https://user-images.githubusercontent.com/56278360/133998207-044b3d2d-3a0b-417c-80f8-24f5820a2f00.png)

好的，我试了一下我用另外一个文件用数字名字的也遇见同样的问题

**Comment by babysor** [comment]
> > mp3把名字改成纯字母的试试？
> 
> ![image](https://user-images.githubusercontent.com/56278360/133998185-89ef7f42-4cdd-47b5-a0b2-ec172d866c59.png)
> ![image](https://user-images.githubusercontent.com/56278360/133998207-044b3d2d-3a0b-417c-80f8-24f5820a2f00.png)
> 
> 好的，我试了一下我用另外一个文件用数字名字的也遇见同样的问题

这个问题是第一次遇到，你有用anaconda吗？怀疑依赖包有被修改的情况

**Comment by Udaroth** [comment]
> > > mp3把名字改成纯字母的试试？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56278360/133998185-89ef7f42-4cdd-47b5-a0b2-ec172d866c59.png)
> > ![image](https://user-images.githubusercontent.com/56278360/133998207-044b3d2d-3a0b-417c-80f8-24f5820a2f00.png)
> > 好的，我试了一下我用另外一个文件用数字名字的也遇见同样的问题
> 
> 这个问题是第一次遇到，你有用anaconda吗？怀疑依赖包有被修改的情况

我有用anacdona, 我换成用普通 python venv就可以了! 谢谢babysor
