### ISSUE TITLE
No synthesizer models found in synthesizer\saved_models

### ISSUE THREAD

**Issue by QiYYZH** [babysor/MockingBird#92]
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/dev
        aidatatang_200zh/corpus/test
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "D:\Develop\Project\PycharmProjects\Languages\MockingBird-main\toolbox\__init__.py", line 74, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir, seed)
  File "D:\Develop\Project\PycharmProjects\Languages\MockingBird-main\toolbox\__init__.py", line 142, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "D:\Develop\Project\PycharmProjects\Languages\MockingBird-main\toolbox\ui.py", line 339, in populate_models
    raise Exception("No synthesizer models found in %s" % synthesizer_models_dir)
Exception: No synthesizer models found in synthesizer\saved_models

**Comment by babysor** [comment]
没有下载模型。请按教程放到指定位置

**Comment by QiYYZH** [comment]
OK，多谢，发现是程序中synthesizer目录下少了saved_models目录

**Comment by QiYYZH** [comment]
OK，多谢，发现是程序中synthesizer目录下少了saved_models目录
