### ISSUE TITLE
使用vc转换时，转换过程报错 TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by zhaojigang** [babysor/MockingBird#920]
**Summary[问题简述（一句话）]**
使用 VC 转换时，出现如题错误

**Env & To Reproduce[复现与环境]**
os: windows11
gpu: 4080
python: 3.9

**Screenshots[截图（如有）]**
![image](https://github.com/babysor/MockingBird/assets/14085645/cbd74fe5-634f-49ca-8eec-c26a85ea8e9e)
![image](https://github.com/babysor/MockingBird/assets/14085645/782a3fcb-0fbe-4903-8d5c-c61a3b3086d0)

**Comment by zhaojigang** [comment]
检查了代码，打印了参数，发现其中的 fmin=None
![image](https://github.com/babysor/MockingBird/assets/14085645/cfee600f-92b4-4726-a100-6efcb59f2285)
增加了判断后解决了问题，但是发现合成后的电音非常重，可能是另外一个问题，先关闭此 issue 了
![image](https://github.com/babysor/MockingBird/assets/14085645/91723fd5-67e0-49a1-9a83-99dc1506c426)

**Comment by L1590** [comment]
Thank you, this is useful, I also encountered this error, after adding this line of code can run！
