### ISSUE TITLE
我想问一下encoder数据集怎么生成或者在哪里下载？

### ISSUE THREAD

**Issue by kaleidosgu** [babysor/MockingBird#940]
**Summary[encoder_preprocess 使用到的数据集]**
在使用 
`python encoder_preprocess.py <datasets_root> -d {dataset}`
进行训练的时候，脚本提示
`e:\GameDev\Git\MockingBird\MockingBird\data\OriginalData\LibriSpeech\train-other-500, skipping this dataset.`
请问这个encoder数据集文件怎么生成，或者去哪里下载现有的？

**Comment by babysor** [comment]
LibriSpeech 可以google一下，是有现成的，英文数据集
