### ISSUE TITLE
预处理pre.py报错

### ISSUE THREAD

**Issue by tangzhimiao** [babysor/MockingBird#961]
请问大佬们运行pre.py的时候，需要huggingface的模型，下载后放在那个路径下能够保证正常运行？
![image](https://github.com/babysor/MockingBird/assets/33514716/735e690f-ccfd-4edf-9af6-8c48920b8b60)

**Comment by SpiderYsy** [comment]
大佬，请问一下你是怎么解决的？

**Comment by tangzhimiao** [comment]
> 大佬，请问一下你是怎么解决的？

本地下载下来，然后给在那个函数中写入你指定的路径
